/* Exhaustive endpoint-jet obstruction for the delta=9 cubic branch.
 *
 * This is NOT a finite-field search for curves or geometric coefficients.
 * Every possible endpoint jet is in the proved 116-element set. Two weighted
 * Fourier moments necessarily lie in F_(5^14). Their coefficients over
 * E=F_(5^7) satisfy eight linear equations in five unknowns. This program
 * checks those equations for all endpoint choices, modulo a proved symmetry,
 * and then checks the one remaining quadratic norm equation.
 *
 * Two elimination implementations are supplied:
 *   primary: quotient by E*rho, a 5x5-minor rejection filter, then 7x5 RREF;
 *   direct:  the original 8x6 augmented matrix, reverse row order, ordinary
 *            forward elimination and back substitution, with no minor filter.
 * All input tables in constants.h are regenerated by exact_data.py.
 */
#include <algorithm>
#include <array>
#include <cassert>
#include <chrono>
#include <cstdint>
#include <fstream>
#include <iostream>
#include <stdexcept>
#include <string>
#include <vector>
#include "constants.h"

using V = std::array<int,8>;
constexpr int FIELD_SIZE=78125, ORDER=FIELD_SIZE-1;
constexpr int ORBITS=333, ENDPOINTS=116, TRIPLES=266916;

// E elements are base-five integer codes in the basis 1,eta,...,eta^6.
// Tables implement carry-free addition and logarithmic multiplication.
static int add_low[125][125], add_high[625][625];
static int logarithm[FIELD_SIZE], exponential[2*ORDER], inverse[FIELD_SIZE];
static int negative[FIELD_SIZE], small[5][FIELD_SIZE];

inline int add(int a,int b) {
    return add_low[a%125][b%125]+125*add_high[a/125][b/125];
}
inline int sub(int a,int b) { return add(a,negative[b]); }
inline int mul(int a,int b) {
    return (!a || !b) ? 0 : exponential[logarithm[a]+logarithm[b]];
}
int slow_add(int a,int b) {
    int result=0, place=1;
    for (int i=0;i<7;i++,place*=5,a/=5,b/=5) result+=((a+b)%5)*place;
    return result;
}
int slow_mul(int a,int b) {
    int aa[7],bb[7],v[13]={};
    for (int i=0;i<7;i++,a/=5,b/=5) { aa[i]=a%5; bb[i]=b%5; }
    for (int i=0;i<7;i++) for (int j=0;j<7;j++)
        v[i+j]=(v[i+j]+aa[i]*bb[j])%5;
    for (int i=12;i>=7;i--) for (int j=0;j<7;j++)
        v[i-7+j]=(v[i-7+j]+(5-v[i])*EMOD[j])%5;
    int result=0;
    for (int i=6;i>=0;i--) result=5*result+v[i];
    return result;
}
int slow_power(int a,int n) {
    int result=1;
    while (n) {
        if (n&1) result=slow_mul(result,a);
        a=slow_mul(a,a); n>>=1;
    }
    return result;
}
int encode(const int* a,int length) {
    int result=0;
    for (int i=length-1;i>=0;i--) result=5*result+a[i];
    return result;
}
void initialize_field() {
    for (int a=0;a<125;a++) for (int b=0;b<125;b++)
        add_low[a][b]=slow_add(a,b);
    for (int a=0;a<625;a++) for (int b=0;b<625;b++)
        add_high[a][b]=slow_add(a,b);
    for (int a=0;a<FIELD_SIZE;a++) {
        negative[a]=slow_mul(a,4);
        for (int k=0;k<5;k++) small[k][a]=slow_mul(a,k);
    }
    std::vector<int> prime_factors;
    int remaining=ORDER;
    for (int p=2;p*p<=remaining;p++) if (remaining%p==0) {
        prime_factors.push_back(p);
        while (remaining%p==0) remaining/=p;
    }
    if (remaining>1) prime_factors.push_back(remaining);
    int generator=2;
    for (;;generator++) {
        bool primitive=true;
        for (int p:prime_factors)
            if (slow_power(generator,ORDER/p)==1) primitive=false;
        if (primitive) break;
    }
    std::fill(logarithm,logarithm+FIELD_SIZE,-1);
    int a=1;
    for (int i=0;i<ORDER;i++) {
        assert(a>0 && logarithm[a]==-1);
        exponential[i]=a; logarithm[a]=i;
        a=slow_mul(a,generator);
    }
    assert(a==1);
    for (int i=0;i<ORDER;i++) exponential[i+ORDER]=exponential[i];
    for (int i=1;i<FIELD_SIZE;i++) {
        inverse[i]=exponential[(ORDER-logarithm[i])%ORDER];
        assert(mul(i,inverse[i])==1);
        assert(add(i,negative[i])==0);
        assert(mul(i,generator)==slow_mul(i,generator));
    }
    assert(generator==8);
    std::cerr << "E arithmetic initialized and checked; generator=" << generator << '\n';
}

// L=E tensor_F5 F_(5^8), basis 1,a,a^2,a^3,beta,beta*a,beta*a^2,beta*a^3.
V vector_add(const V& a,const V& b) {
    V out; for (int i=0;i<8;i++) out[i]=add(a[i],b[i]); return out;
}
V vector_sub(const V& a,const V& b) {
    V out; for (int i=0;i<8;i++) out[i]=sub(a[i],b[i]); return out;
}
V vector_small(const V& a,int k) {
    V out; for (int i=0;i<8;i++) out[i]=small[k][a[i]]; return out;
}
V vector_scalar(const V& a,int k) {
    V out; for (int i=0;i<8;i++) out[i]=mul(k,a[i]); return out;
}
V times_beta(const V& a) {
    V out;
    for (int i=0;i<4;i++) {
        out[i]=small[3][a[i+4]];
        out[i+4]=add(a[i],a[i+4]);
    }
    return out;
}
V times_f25(const V& a,int constant,int beta_coefficient) {
    return vector_add(vector_small(a,constant),
                      vector_small(times_beta(a),beta_coefficient));
}
V vector_mul(const V& a,const V& b) {
    V out={};
    for (int i=0;i<8;i++) if (a[i]) for (int j=0;j<8;j++) if (b[j]) {
        int product=mul(a[i],b[j]);
        for (int k=0;k<8;k++) if (KMUL[i][j][k])
            out[k]=add(out[k],small[KMUL[i][j][k]][product]);
    }
    return out;
}
V frobenius_Q(const V& a) {
    V out={};
    for (int i=0;i<8;i++) for (int j=0;j<8;j++) if (FROB[i][j])
        out[j]=add(out[j],small[FROB[i][j]][a[i]]);
    return out;
}
bool zero_vector(const V& a) {
    return std::all_of(a.begin(),a.end(),[](int x){ return x==0; });
}
static V roots29[29], endpoint_c[ENDPOINTS], endpoint_u2[ENDPOINTS];
struct Triple { std::array<int,3> ids; V u2,c; };
static std::vector<Triple> triples;
void initialize_endpoints() {
    V zeta={}; zeta[0]=encode(ZA,7); zeta[4]=encode(ZB,7);
    roots29[0]={1,0,0,0,0,0,0,0};
    for (int j=1;j<29;j++) roots29[j]=vector_mul(roots29[j-1],zeta);
    assert(vector_mul(roots29[28],zeta)==roots29[0]);
    assert(frobenius_Q(zeta)==roots29[28]);
    for (int i=0;i<4;i++) {
        V c,u;
        for (int k=0;k<8;k++) { c[k]=CCONST[i][k]; u[k]=UCONST[i][k]; }
        for (int j=0;j<29;j++) {
            endpoint_c[29*i+j]=vector_mul(c,roots29[(5*j)%29]);
            endpoint_u2[29*i+j]=vector_mul(u,roots29[(8*j)%29]);
        }
    }
    triples.reserve(TRIPLES);
    for (int i=0;i<ENDPOINTS;i++) for (int j=i;j<ENDPOINTS;j++)
        for (int k=j;k<ENDPOINTS;k++) triples.push_back({{i,j,k},
            vector_add(vector_add(endpoint_u2[i],endpoint_u2[j]),endpoint_u2[k]),
            vector_add(vector_add(endpoint_c[i],endpoint_c[j]),endpoint_c[k])});
    assert(triples.size()==TRIPLES);
}

// rho=3+3*beta. This map L -> E^7 has kernel E*rho.
void project(const V& a,int* out) {
    out[0]=sub(a[0],a[4]); out[1]=a[1]; out[2]=a[2]; out[3]=a[3];
    out[4]=a[5]; out[5]=a[6]; out[6]=a[7];
}
// A nonzero augmented 5x5 minor proves inconsistency of four unknowns.
bool first_minor_zero(const int matrix[7][5]) {
    int a[5][5];
    for (int i=0;i<5;i++) for (int j=0;j<5;j++) a[i][j]=matrix[i][j];
    for (int k=0;k<4;k++) {
        int row=k;
        while (row<5 && !a[row][k]) row++;
        if (row==5) return true;
        if (row!=k) for (int j=k;j<5;j++) std::swap(a[k][j],a[row][j]);
        int inv=inverse[a[k][k]];
        for (int i=k+1;i<5;i++) {
            int factor=mul(a[i][k],inv);
            if (factor) for (int j=k+1;j<5;j++)
                a[i][j]=sub(a[i][j],mul(factor,a[k][j]));
        }
    }
    return a[4][4]==0;
}
// Return -1 for inconsistency, otherwise coefficient rank; equation is M*x+D=0.
int projected_rref(int matrix[7][5],std::array<int,5>& answer) {
    int height=0, pivots[4];
    for (int k=0;k<4;k++) {
        int row=height;
        while (row<7 && !matrix[row][k]) row++;
        if (row==7) continue;
        for (int j=k;j<5;j++) std::swap(matrix[height][j],matrix[row][j]);
        int inv=inverse[matrix[height][k]];
        for (int j=k;j<5;j++) matrix[height][j]=mul(matrix[height][j],inv);
        for (int i=0;i<7;i++) if (i!=height) {
            int factor=matrix[i][k];
            if (factor) for (int j=k;j<5;j++)
                matrix[i][j]=sub(matrix[i][j],mul(factor,matrix[height][j]));
        }
        pivots[height++]=k;
    }
    for (int i=height;i<7;i++) if (matrix[i][4]) return -1;
    if (height==4) for (int i=0;i<4;i++) answer[pivots[i]]=negative[matrix[i][4]];
    return height;
}
// Independent elimination on the original eight equations, including norm variable z.
int full_forward(const V columns[5],std::array<int,5>& answer) {
    int a[8][6];
    for (int i=0;i<8;i++) {
        int row=7-i;  // Deliberately different pivot order from primary mode.
        for (int j=0;j<4;j++) a[i][j]=columns[j][row];
        a[i][4]=(row==0 || row==4)?3:0;
        a[i][5]=columns[4][row];
    }
    int height=0,pivots[5];
    for (int k=0;k<5;k++) {
        int row=height;
        while (row<8 && !a[row][k]) row++;
        if (row==8) continue;
        for (int j=k;j<6;j++) std::swap(a[height][j],a[row][j]);
        int inv=inverse[a[height][k]];
        for (int j=k;j<6;j++) a[height][j]=mul(a[height][j],inv);
        for (int i=height+1;i<8;i++) {
            int factor=a[i][k];
            if (factor) for (int j=k;j<6;j++)
                a[i][j]=sub(a[i][j],mul(factor,a[height][j]));
        }
        pivots[height++]=k;
    }
    for (int i=height;i<8;i++) if (a[i][5]) return -1;
    if (height==5) for (int i=4;i>=0;i--) {
        int k=pivots[i], value=negative[a[i][5]];
        for (int j=k+1;j<5;j++) value=sub(value,mul(a[i][j],answer[j]));
        answer[k]=value;
    }
    return height;
}
int quadratic_norm(int constant,int beta_coefficient) {
    // Norm_(E(beta)/E)(a+b*beta)=a^2+a*b+2*b^2.
    return add(add(mul(constant,constant),mul(constant,beta_coefficient)),
               small[2][mul(beta_coefficient,beta_coefficient)]);
}
void print_ids(std::ostream& out,const std::array<int,3>& a) {
    out<<'['<<a[0]<<','<<a[1]<<','<<a[2]<<']';
}
void print_answer(std::ostream& out,const std::array<int,5>& a) {
    out<<'['; for (int i=0;i<5;i++) out<<(i?",":"")<<a[i]; out<<']';
}
struct Counts {
    long long pairs=0,minor_zero=0,linear=0,deficient=0,quadratic_pass=0;
    void accumulate(const Counts& other) {
        pairs+=other.pairs; minor_zero+=other.minor_zero; linear+=other.linear;
        deficient+=other.deficient; quadratic_pass+=other.quadratic_pass;
    }
};
void print_counts(std::ostream& out,const Counts& c,bool primary) {
    out<<"\"pairs\":"<<c.pairs<<",\"minor_zero\":";
    if (primary) out<<c.minor_zero; else out<<"null";
    out<<",\"linear_consistent\":"<<c.linear
       <<",\"rank_deficient_consistent\":"<<c.deficient
       <<",\"quadratic_compatible\":"<<c.quadratic_pass;
}
int main(int argc,char** argv) {
    try {
        if (argc!=5) throw std::runtime_error(
            "Usage: scan <primary|direct> <first-orbit> <end-exclusive> <output.jsonl>");
        std::string mode=argv[1];
        bool primary=(mode=="primary");
        if (!primary && mode!="direct") throw std::runtime_error("Unknown algorithm");
        int start=std::stoi(argv[2]), end=std::stoi(argv[3]);
        if (start<0 || start>=end || end>ORBITS) throw std::runtime_error("Invalid orbit range");
        std::ofstream out(argv[4]);
        if (!out) throw std::runtime_error("Cannot open output file");
        initialize_field(); initialize_endpoints();
        auto began=std::chrono::steady_clock::now();
        Counts totals;
        for (int ri=start;ri<end;ri++) {
            Counts count;
            V u0={},c0={};
            std::array<int,3> zero_ids={REPS[ri][0],REPS[ri][1],REPS[ri][2]};
            for (int id:zero_ids) {
                u0=vector_add(u0,endpoint_u2[id]); c0=vector_add(c0,endpoint_c[id]);
            }
            V beta_u0=times_beta(u0), rho_c0=times_f25(c0,3,3);
            V rho_beta_bar_c0=times_f25(c0,4,2); // rho*beta^Q=4+2*beta.
            V endpoint_D[ENDPOINTS];
            for (int j=0;j<ENDPOINTS;j++) endpoint_D[j]=vector_sub(
                vector_mul(endpoint_c[j],c0),vector_mul(u0,endpoint_u2[j]));
            for (const Triple& t:triples) {
                // D=C_infinity*C_zero-U_zero*U_infinity, by bilinearity.
                V D=vector_add(vector_add(endpoint_D[t.ids[0]],endpoint_D[t.ids[1]]),
                               endpoint_D[t.ids[2]]);
                V columns[5]={
                    vector_add(u0,times_f25(t.u2,3,3)),
                    vector_add(beta_u0,times_f25(t.u2,4,2)),
                    vector_small(vector_add(t.c,rho_c0),4),
                    vector_small(vector_add(times_beta(t.c),rho_beta_bar_c0),4),
                    D};
                count.pairs++;
                std::array<int,5> answer={};
                int rank;
                if (primary) {
                    int matrix[7][5];
                    for (int k=0;k<5;k++) {
                        int column[7]; project(columns[k],column);
                        for (int j=0;j<7;j++) matrix[j][k]=column[j];
                    }
                    if (!first_minor_zero(matrix)) continue;
                    count.minor_zero++;
                    int projected_rank=projected_rref(matrix,answer);
                    if (projected_rank<0) continue;
                    rank=projected_rank+1; // Restore the independent E*rho column.
                    if (rank==5) {
                        V residual=columns[4];
                        for (int j=0;j<4;j++) residual=vector_add(
                            residual,vector_scalar(columns[j],answer[j]));
                        assert(residual[0]==residual[4]);
                        for (int j=1;j<8;j++) if (j!=4) assert(residual[j]==0);
                        answer[4]=small[3][residual[0]]; // z=-(residual_0)/3.
                    }
                } else rank=full_forward(columns,answer);
                if (rank<0) continue;
                count.linear++;
                int norm_difference=-1,quadratic_residual=-1;
                if (rank<5) count.deficient++;
                else {
                    V residual=columns[4];
                    for (int j=0;j<4;j++) residual=vector_add(
                        residual,vector_scalar(columns[j],answer[j]));
                    residual[0]=add(residual[0],small[3][answer[4]]);
                    residual[4]=add(residual[4],small[3][answer[4]]);
                    assert(zero_vector(residual));
                    norm_difference=sub(quadratic_norm(answer[2],answer[3]),
                                        quadratic_norm(answer[0],answer[1]));
                    quadratic_residual=sub(answer[4],norm_difference);
                    if (!quadratic_residual) count.quadratic_pass++;
                }
                out<<"{\"record\":\"linear_case\",\"orbit\":"<<ri<<",\"zero\":";
                print_ids(out,zero_ids); out<<",\"infinity\":"; print_ids(out,t.ids);
                out<<",\"rank\":"<<rank<<",\"solution\":"; print_answer(out,answer);
                out<<",\"norm_difference\":"<<norm_difference
                   <<",\"quadratic_residual\":"<<quadratic_residual<<"}\n";
            }
            totals.accumulate(count);
            out<<"{\"record\":\"orbit\",\"orbit\":"<<ri<<",\"zero\":";
            print_ids(out,zero_ids); out<<','; print_counts(out,count,primary); out<<"}\n";
            out.flush();
            double elapsed=std::chrono::duration<double>(std::chrono::steady_clock::now()-began).count();
            std::cerr<<mode<<" orbit="<<ri<<" pairs="<<totals.pairs
                     <<" linear="<<totals.linear<<" deficient="<<totals.deficient
                     <<" quadratic_pass="<<totals.quadratic_pass<<" seconds="<<elapsed<<'\n';
        }
        out<<"{\"record\":\"summary\",\"algorithm\":\""<<mode
           <<"\",\"first_orbit\":"<<start<<",\"end_exclusive\":"<<end<<',';
        print_counts(out,totals,primary); out<<"}\n";
        if (!out) throw std::runtime_error("Failed to write output");
        return 0;
    } catch (const std::exception& error) {
        std::cerr<<"ERROR: "<<error.what()<<'\n'; return 1;
    }
}
