#include "pade.hpp"
#include <limits>
XP normalized_reversal(const XP&W){if(W.size()!=141||W[140].deg()!=0||!W[140].at(0))throw std::runtime_error("degree140");XP a(141);F c=ff::inv(W[140].at(0));for(int i=0;i<=140;i++)a[i]=scale(W[140-i],c);return a;}
XP reversal(const XP&a){XP W(141);for(int i=0;i<=140;i++)W[i]=atXP(a,140-i);return W;}
Poly gcdall(const std::vector<Poly>&a){Poly g;for(auto&p:a)g=gcd(g,p);return g;}
int valuation(const std::vector<Poly>&a,int N){int v=N;for(auto&p:a)for(int i=0;i<=p.deg()&&i<N;i++)if(p.at(i)){v=std::min(v,i);break;}return v;}
void artin(const XP&a,int N,int expected,const std::string&label){auto old=equations(reversal(a)),fresh=canonical_pade_equations(a);int x=valuation(old,N),y=valuation(fresh,N);if(x!=y||x!=expected)throw std::runtime_error("Artin ideal mismatch "+label);std::cout<<"ARTIN_IDEAL "<<label<<" modulus_epsilon_power "<<N<<" old_and_new_ideal_epsilon_power "<<x<<" PASS\n";}
int main(int argc,char**argv){try{ff::init();init_source();auto r=load(argc>1?argv[1]:"inputs/E_records.tsv");int count=0;for(auto [H,q]:std::vector<std::pair<F,F>>{{1,3},{5,15625},{31,48151},{2,17576},{625,14},{31,54853},{18,5},{50,26}}){if(!allowed(H,q,1))throw std::runtime_error("ratio outside chart");auto W=evaluateW(r,H,q),a=normalized_reversal(W);auto old=equations(W),fresh=canonical_pade_equations(a);auto g=gcdall(old),h=gcdall(fresh);if(!(g==h))throw std::runtime_error("full-scale ideal gcd mismatch");int od=0,nd=0;for(auto&p:old)od=std::max(od,p.deg());for(auto&p:fresh)nd=std::max(nd,p.deg());std::cout<<"BOUNDED_RATIO_FULL_MU_IDEAL H "<<H<<" q "<<q<<" gcd_degree "<<g.deg()<<" old_max_mu_degree "<<od<<" new_max_mu_degree "<<nd<<" PASS\n";count++;}
XP j(71);j[0]=Poly(1);j[9]=Poly({1,1});j[70]=Poly::mon(2);XP a=mulXP(j,j,141);artin(a,130,130,"polynomial_square_family");for(int r0:{1,2,3,25,26,125}){XP b=a;b[125]=b[125]+Poly::mon(r0);artin(b,r0+2,r0,"late125_deformation");}
for(int n:{75,100,125})for(int r0:{1,2,25}){XP b(141);b[0]=Poly(1);b[n]=Poly::mon(r0);artin(b,r0+2,r0,"Frobenius_block_deformation_T"+std::to_string(n));}
XP late(141);late[0]=late[125]=Poly(1);auto model=pade(late);for(auto&r0:model.linear)if(!leval(r0,Poly(),Poly()).zero())throw std::runtime_error("late fixture linear rows");for(int i=0;i<4;i++)if(!qeval(model.quadratic[i],Poly(),Poly()).zero())throw std::runtime_error("late fixture first four quadratics");if(qeval(model.quadratic[4],Poly(),Poly()).zero())throw std::runtime_error("late fixture missing fifth quadratic");std::cout<<"LATE_COEFFICIENT_FIXTURE all_67_linear_and_first_4_quadratic_vanish fifth_quadratic_nonzero PASS\n";
Poly jp=ppow(Poly({1,1}),70),ap=jp*jp;XP repeated=constantMu(ap);artin(repeated,2,2,"root_multiplicity140");std::cout<<"PADE_PRESENTATION_CHECKS PASS bounded_ratio_count "<<count<<" Artin_checks 17 late_fixture 1\nGLOBAL_SQUARE_LOCUS UNRESOLVED\n";
}catch(std::exception&e){std::cerr<<"ERROR "<<e.what()<<"\n";return 1;}return 0;}
