// Global pole-rank certificate. All H and q remain geometric variables.
#include "resultant_engine.hpp"
#include <tuple>
BP bt(BP a){while(!a.empty()&&a.back().zero())a.pop_back();return a;}
BP ba(const BP&a,const BP&b){BP z(std::max(a.size(),b.size()));for(size_t i=0;i<z.size();i++)z[i]=(i<a.size()?a[i]:Poly())+(i<b.size()?b[i]:Poly());return bt(z);}
BP bs(BP a,F c){for(auto&p:a)p=scale(p,c);return bt(a);}
BP bm(const BP&a,const BP&b){if(a.empty()||b.empty())return {};BP z(a.size()+b.size()-1);for(size_t i=0;i<a.size();i++)for(size_t j=0;j<b.size();j++)z[i+j]=z[i+j]+a[i]*b[j];return bt(z);}
BP bq(BP a,int n){for(auto&p:a)p=shift(p,n);return bt(a);}
int qval(const BP&a){int n=100000;for(auto&p:a)for(int i=0;i<=p.deg();i++)if(p.at(i)){n=std::min(n,i);break;}return n;}
BP removeq(BP a,int n){for(auto&p:a)if(!p.zero()){if(p.deg()<n)throw std::runtime_error("invalid q division");for(int i=0;i<n;i++)if(p.at(i))throw std::runtime_error("nonexact q division");p=Poly(std::vector<F>(p.v.begin()+n,p.v.end()));}return bt(a);}
struct Row{int j,h,q,m,x;F c;};
std::vector<Row> records(const std::string&p){std::ifstream in(p);std::string s;in>>s;if(s!="CONSTANT140_E_V1")throw std::runtime_error("E header");std::vector<Row>r;Row a;while(in>>a.j>>a.h>>a.q>>a.m>>a.x>>a.c)r.push_back(a);if(r.size()!=89481)throw std::runtime_error("E count");return r;}
BP evaluated(const std::vector<Row>&r,int j,int m,F x){BP a(13);for(auto&b:a)b.v.resize(61);F powers[47];powers[0]=1;for(int i=1;i<47;i++)powers[i]=ff::mul(powers[i-1],x);for(auto z:r)if(z.j==j&&z.m==m)a[z.h].v[z.q]=ff::add(a[z.h].v[z.q],ff::mul(z.c,powers[z.x]));for(auto&p:a)p.trim();return bt(a);}
std::tuple<Poly,Poly,Poly> xgcd(Poly a,Poly b){Poly u(1),v,u1,v1(1);while(!b.zero()){auto qr=divmod(a,b);auto un=u-qr.first*u1,vn=v-qr.first*v1;a=b;b=qr.second;u=u1;u1=un;v=v1;v1=vn;}F c=ff::inv(a.v.back());return {scale(a,c),scale(u,c),scale(v,c)};}
Poly interpolate_resultant(const BP&a,const BP&b,int index){int D=a.size()-1,E=b.size()-1,bound=D*qdegree(b)+E*qdegree(a),N=ff::ORD;for(int n=bound+1;n<=ff::ORD;n++)if(ff::ORD%n==0){N=n;break;}if(N<=bound)throw std::runtime_error("interpolation size");F root=ff::pow(25,ff::ORD/N);if(ff::pow(root,N)!=1)throw std::runtime_error("grid root order");int nleft=N;for(int p=2;p<=nleft;p++)if(nleft%p==0){if(ff::pow(root,N/p)==1)throw std::runtime_error("grid nodes not distinct");while(nleft%p==0)nleft/=p;}std::vector<std::vector<F>>av(D+1),bv(E+1);std::vector<F>values(N);
#pragma omp parallel for num_threads(4)
for(int h=0;h<D+E+2;h++){const Poly&p=h<=D?a[h]:b[h-D-1];std::vector<F>v(N);std::copy(p.v.begin(),p.v.end(),v.begin());auto z=fft(v,root);if(h<=D)av[h]=std::move(z);else bv[h-D-1]=std::move(z);}
#pragma omp parallel for num_threads(4)
for(int k=0;k<N;k++){Poly f,g;f.v.resize(D+1);g.v.resize(E+1);for(int h=0;h<=D;h++)f.v[h]=av[h][k];for(int h=0;h<=E;h++)g.v[h]=bv[h][k];f.trim();g.trim();values[k]=fixedres(f,D,g,E);}
auto v=fft(values,ff::inv(root));for(auto&c:v)c=ff::mul(c,ff::inv(N%5));Poly R(v);if(R.deg()>bound)throw std::runtime_error("degree bound");for(F q:{0,2,3,5,25,53,625,15383,48151,372885})if(eval(R,q)!=fixedres(evalq(a,q),D,evalq(b,q),E))throw std::runtime_error("off-grid resultant identity");std::cout<<"GLOBAL_RESULTANT "<<index<<" fixed_H_degrees "<<D<<" "<<E<<" q_bound "<<bound<<" grid "<<N<<" degree "<<R.deg()<<"\n";return R;}
void verify_stored(const std::string&path){std::ifstream in(path);std::string head;in>>head;if(head!="POLE_RANK_CERTIFICATE_V1")throw std::runtime_error("certificate header");std::array<Poly,3>S;for(int i=0;i<3;i++){int root,valuation,lead;in>>root>>valuation>>lead;if(valuation!=612||!lead)throw std::runtime_error("certificate metadata");S[i]=readpoly(in);if(S[i].deg()!=1728||S[i].v.back()!=1)throw std::runtime_error("certificate degree");}for(int n=0;n<3;n++){int i,j;in>>i>>j;Poly u=readpoly(in),v=readpoly(in);if(!(u*S[i]+v*S[j]==Poly(1)))throw std::runtime_error("Bezout identity");std::cout<<"STORED_BEZOUT "<<i<<" "<<j<<" PASS\n";}if(!in)throw std::runtime_error("truncated certificate");}
int main(int argc,char**argv){try{ff::init();init_source();if(argc>1&&std::string(argv[1])=="verify"){verify_stored(argc>2?argv[2]:"certificates/pole_rank.dat");return 0;}tests();auto r=records(argc>1?argv[1]:"inputs/E_records.tsv");std::ofstream out(argc>2?argv[2]:"regenerated/pole_rank.dat");if(!out)throw std::runtime_error("output path");out<<"POLE_RANK_CERTIFICATE_V1\n";std::array<Poly,3>S;
for(int k=0,p=25;k<3;k++,p*=25){F x=ff::pow(alpha,p);if(eval(t,x)||!eval(P,x))throw std::runtime_error("bad t root");std::vector<BP>e(3);for(int j=0;j<3;j++){e[j]=evaluated(r,j,1,x);if(!evaluated(r,j,2,x).empty())throw std::runtime_error("mu2 not zero at t root");}int common=std::min({qval(e[0]),qval(e[1]),qval(e[2])});if(common!=1)throw std::runtime_error("unexpected common q factor");for(auto&a:e)a=removeq(a,common);
BP f=ba(bm(e[1],e[1]),bs(bm(e[0],e[2]),4)),g=ba(bq(bm(e[0],e[1]),1),bs(bm(e[2],e[2]),ff::neg(eval(P,x))));int vf=qval(f),vg=qval(g);if(vf!=2||vg!=3)throw std::runtime_error("condition q factors");f=removeq(f,vf);g=removeq(g,vg);if(f.size()!=22||g.size()!=22||qdegree(f)!=105||qdegree(g)!=105)throw std::runtime_error("condition degree");std::cout<<"T_ROOT "<<x<<" mu2_vanishes_globally PASS condition_H_degree 21 q_degree 105\n";Poly R=interpolate_resultant(f,g,k);int v=0;while(!R.at(v)&&v<=R.deg())v++;if(v!=612||R.deg()!=2340)throw std::runtime_error("resultant shape");F lead=R.v.back();S[k]=scale(Poly(std::vector<F>(R.v.begin()+v,R.v.end())),ff::inv(lead));out<<x<<" "<<v<<" "<<lead<<"\n";writepoly(out,S[k]);}
for(int i=0;i<3;i++)for(int j=i+1;j<3;j++){auto[d,u,v]=xgcd(S[i],S[j]);if(!(d==Poly(1))||!(u*S[i]+v*S[j]==Poly(1)))throw std::runtime_error("pairwise coprimality");out<<i<<" "<<j<<"\n";writepoly(out,u);writepoly(out,v);std::cout<<"GLOBAL_BEZOUT "<<i<<" "<<j<<" degree "<<d.deg()<<" multiplier_degrees "<<u.deg()<<" "<<v.deg()<<" PASS\n";}out.close();std::cout<<"GLOBAL_POLE_RANK_CERTIFICATE PASS. For q!=0, at most one t-root has two or more vanishing cubic-conjugate mu coefficients.\nSQUARE_LOCUS_DECISION UNRESOLVED\n";
}catch(const std::exception&e){std::cerr<<"ERROR "<<e.what()<<"\n";return 1;}return 0;}
