#pragma once
// Global fixed-degree H-resultants by exact, degree-bounded interpolation in q.
#include "../src/source.hpp"
#include <omp.h>
#include <chrono>
using BP=std::vector<Poly>;
std::vector<BP> readminors(const std::string&path){std::ifstream in(path);std::string s;in>>s;int expected=6;if(s=="RANK_MINORS_V2"){int nr,nc;in>>nr>>nc>>expected;}else if(s!="RANK2_MINORS_V1")throw std::runtime_error("wrong minor file");std::vector<BP> out;int i,j,hv,qv,pv;while(in>>i>>j>>hv>>qv>>pv){BP a;while(in>>s&&s!="END"){int h=std::stoi(s),q,c;in>>q>>c;if((int)a.size()<=h)a.resize(h+1);if(a[h].deg()<q)a[h].v.resize(q+1);a[h].v[q]=c;}out.push_back(a);}if((int)out.size()!=expected)throw std::runtime_error("wrong minor count");return out;}
Poly evalq(const BP&a,F q){Poly p;for(auto&b:a)p.v.push_back(eval(b,q));p.trim();return p;}
F resultant(Poly a,Poly b){if(a.zero()||b.zero())return 0;F out=1;while(b.deg()>0){int n=a.deg(),m=b.deg();if(n<m){if(n*m%2)out=ff::neg(out);std::swap(a,b);continue;}Poly r=rem(a,b);if(r.zero())return 0;if(n*m%2)out=ff::neg(out);out=ff::mul(out,ff::pow(b.v.back(),n-r.deg()));a=b;b=r;}return ff::mul(out,ff::pow(b.at(0),a.deg()));}
F fixedres(const Poly&a,int D,const Poly&b,int E){if(a.zero()||b.zero())return 0;int d=a.deg(),e=b.deg();if(d>D||e>E)throw std::runtime_error("degree bound violation");if(d<D&&e<E)return 0;F out=resultant(a,b);if(d<D){out=ff::mul(out,ff::pow(b.v.back(),D-d));if((D-d)*E%2)out=ff::neg(out);}if(e<E)out=ff::mul(out,ff::pow(a.v.back(),E-e));return out;}
F determinant(std::vector<std::vector<F>> a){F z=1;int n=a.size();for(int i=0;i<n;i++){int k=i;while(k<n&&!a[k][i])k++;if(k==n)return 0;if(k!=i){std::swap(a[k],a[i]);z=ff::neg(z);}F v=a[i][i],iv=ff::inv(v);z=ff::mul(z,v);for(int j=i+1;j<n;j++)if(a[j][i]){F m=ff::mul(a[j][i],iv);for(int l=i;l<n;l++)a[j][l]=ff::sub(a[j][l],ff::mul(m,a[i][l]));}}return z;}
F sylvester(const Poly&a,int D,const Poly&b,int E){std::vector<std::vector<F>> m(D+E,std::vector<F>(D+E));for(int i=0;i<E;i++)for(int j=0;j<=D;j++)m[i][i+j]=a.at(D-j);for(int i=0;i<D;i++)for(int j=0;j<=E;j++)m[E+i][i+j]=b.at(E-j);return determinant(m);}
std::vector<F> fft(const std::vector<F>&a,F root){int n=a.size();if(n==1)return a;int p=2;while(n%p)p++;int m=n/p;if(m==1){std::vector<std::pair<int,F>> nz;for(int j=0;j<n;j++)if(a[j])nz.push_back({j,a[j]});if(nz.size()<size_t(n/2)){std::vector<F> out(n);for(auto [j,v]:nz){F step=ff::pow(root,j),w=1;for(int k=0;k<n;k++){out[k]=ff::add(out[k],ff::mul(v,w));w=ff::mul(w,step);}}return out;}}std::vector<std::vector<F>> sub(p);F rm=ff::pow(root,p);for(int j=0;j<p;j++){std::vector<F> aa(m);for(int i=0;i<m;i++)aa[i]=a[j+p*i];sub[j]=fft(aa,rm);}std::vector<F> out(n);F rk=1,omega=ff::pow(root,m);for(int k=0;k<m;k++){F rl=1;for(int l=0;l<p;l++){F z=0,w=1,r=ff::mul(rk,rl);for(int j=0;j<p;j++){z=ff::add(z,ff::mul(sub[j][k],w));w=ff::mul(w,r);}out[k+m*l]=z;rl=ff::mul(rl,omega);}rk=ff::mul(rk,root);}return out;}
void tests(){for(int D=1;D<=6;D++)for(int E=1;E<=6;E++)for(int d=-1;d<=D;d++)for(int e=-1;e<=E;e++){Poly a,b;for(int i=0;i<=d;i++)a.v.push_back(25+17*i+3*d);for(int i=0;i<=e;i++)b.v.push_back(107+11*i+e);if(fixedres(a,D,b,E)!=sylvester(a,D,b,E))throw std::runtime_error("fixed degree resultant fixture failed");}for(int n:{2,3,4,6,8,13,24,26,313}){std::vector<F>a(n);for(int i=0;i<n;i++)a[i]=i+1;F r=ff::pow(25,ff::ORD/n);auto b=fft(a,r);F x=1;for(int i=0;i<n;i++){if(b[i]!=eval(Poly(a),x))throw std::runtime_error("FFT direct check failed");x=ff::mul(x,r);}auto c=fft(b,ff::inv(r));for(int i=0;i<n;i++)if(ff::mul(c[i],ff::inv(n%5))!=a[i])throw std::runtime_error("FFT roundtrip failed");}}
int qdegree(const BP&a){int d=-1;for(auto&b:a)d=std::max(d,b.deg());return d;}
void writepoly(const std::string&path,const Poly&a){std::ofstream out(path);for(F x:a.v)out<<x<<' ';out<<'\n';}
