// Bounded independent comparisons, not a global exclusion or a substitute for interpolation.
#define main archived_scale_main
#include "../continuation/scale_algebra.cpp"
#undef main
using BP=std::vector<Poly>;
BP readbp(std::ifstream&in){BP a;std::string s;while(in>>s&&s!="END"){int h=std::stoi(s),q,c;in>>q>>c;if((int)a.size()<=h)a.resize(h+1);if(a[h].deg()<q)a[h].v.resize(q+1);a[h].v[q]=c;}return a;}
F value(const BP&a,F H,F q){F x=0;for(int i=int(a.size())-1;i>=0;i--)x=ff::add(ff::mul(x,H),eval(a[i],q));return x;}
F det3(const std::array<F,3>&a,const std::array<F,3>&b,const std::array<F,3>&c){return ff::add(ff::sub(ff::mul(a[0],ff::sub(ff::mul(b[1],c[2]),ff::mul(b[2],c[1]))),ff::mul(a[1],ff::sub(ff::mul(b[0],c[2]),ff::mul(b[2],c[0])))),ff::mul(a[2],ff::sub(ff::mul(b[0],c[1]),ff::mul(b[1],c[0]))));}
int main(int argc,char**argv){try{ff::init();init_source();auto E=load("inputs/E_records.tsv");std::ifstream in("build/rank3_rows.dat");std::string s;int nr,nc;in>>s>>nr>>nc;if(s!="RANK_ROWS_V3"||nr!=5||nc!=3)throw std::runtime_error("bad rows");std::array<std::array<BP,3>,5>rows;std::array<std::array<int,3>,5>units;for(int i=0;i<5;i++){int j;in>>s>>j>>units[i][0]>>units[i][1]>>units[i][2];if(s!="ROW"||j!=i)throw std::runtime_error("bad row label");for(int c=0;c<3;c++)rows[i][c]=readbp(in);}std::ifstream mi("build/rank3_minors.dat");int nm;mi>>s>>nr>>nc>>nm;if(s!="RANK_MINORS_V2"||nr!=5||nc!=3||nm!=10)throw std::runtime_error("bad minors");std::vector<BP>minors;std::vector<std::array<int,3>>munits;int a,b,h,q,p;while(mi>>a>>b>>h>>q>>p){if(a!=int(minors.size()))throw std::runtime_error("bad minor label");munits.push_back({h,q,p});minors.push_back(readbp(mi));}
 for(auto [H,q]:std::vector<std::pair<F,F>>{{1,3},{5,15625},{31,48151},{2,17576},{625,14},{31,54853},{18,5},{50,26}}){if(!allowed(H,q,1))throw std::runtime_error("bad diagnostic point");XP W=evaluateW(E,H,q);auto eq=equations(W);F L=W[140].at(0),psi=psieval(H,q);F k=ff::mul(3,ff::div(270402,242747));std::array<Poly,5>rr{eq[0],eq[1],eq[3]-scale(eq[2],k),scale(shift(eq[0],1),eq[2].at(48))-scale(eq[2],eq[0].at(47)),scale(shift(eq[1],1),eq[2].at(48))-scale(eq[2],eq[1].at(47))};std::array<std::array<F,3>,5>vv;for(int i=0;i<5;i++){if(rr[i].deg()>47)throw std::runtime_error("row did not have degree <=47");F den=ff::mul(ff::pow(L,i>=3?100:50),ff::mul(ff::pow(H,units[i][0]),ff::mul(ff::pow(q,units[i][1]),ff::pow(psi,units[i][2]))));for(int c=0;c<3;c++){vv[i][c]=ff::div(rr[i].at(47-c),den);if(vv[i][c]!=value(rows[i][c],H,q))throw std::runtime_error("symbolic row disagrees with complete square-equation circuit");}}
 int n=0;for(int i=0;i<5;i++)for(int j=i+1;j<5;j++)for(int k=j+1;k<5;k++){auto m=munits[n];F det=det3(vv[i],vv[j],vv[k]);F unit=ff::mul(ff::pow(H,m[0]),ff::mul(ff::pow(q,m[1]),ff::pow(psi,m[2])));if(ff::div(det,unit)!=value(minors[n],H,q))throw std::runtime_error("normalized minor check failed");n++;}std::cout<<"BOUNDED_RANK3_ROW_COMPARISON H "<<H<<" q "<<q<<" five_rows ten_minors PASS\n";}
 std::cout<<"ALL BOUNDED IMPLEMENTATION CHECKS PASS. Global proofs use symbolic coefficients and degree-bounded resultant interpolation, not these samples.\n";
}catch(std::exception&e){std::cerr<<e.what()<<std::endl;return 1;}}
