// Zero-divisor-aware quotient-algebra check. No irreducible-factor assumption.
#define main archived_frontier_main
#include "../continuation/frontier.cpp"
#undef main
struct Split{Poly factor;};
Poly MOD;long operations=0;
using HP=std::vector<Poly>;
Poly readrow(const std::string&p){std::ifstream in(p);std::vector<F>a;F v;while(in>>v)a.push_back(v);return Poly(a);}
std::tuple<Poly,Poly,Poly> egcd(Poly a,Poly b){Poly u(1),v,s,t(1);while(!b.zero()){auto qr=divmod(a,b);Poly un=u-qr.first*s,vn=v-qr.first*t;a=b;b=qr.second;u=s;v=t;s=un;t=vn;}F z=ff::inv(a.v.back());return {scale(a,z),scale(u,z),scale(v,z)};}
Poly ci(Poly a){a=rem(a,MOD);if(a.zero())throw std::runtime_error("zero inverse requested");auto [g,u,v]=egcd(a,MOD);if(g.deg()>0)throw Split{g};if(!(rem(a*u,MOD)==Poly(1)))throw std::runtime_error("inverse check failed");return rem(u,MOD);}
Poly cm(const Poly&a,const Poly&b){operations++;return rem(a*b,MOD);}
HP tr(HP a){for(auto&p:a)p=rem(p,MOD);while(!a.empty()&&a.back().zero())a.pop_back();return a;}
HP hs(HP a,const Poly&c){for(auto&p:a)p=cm(p,c);return tr(a);}
std::pair<HP,HP> hd(HP a,HP b){a=tr(a);b=tr(b);if(b.empty())throw std::runtime_error("zero polynomial divisor");HP q(std::max(0,int(a.size())-int(b.size())+1));Poly iv=ci(b.back());while(a.size()>=b.size()&&!a.empty()){int e=a.size()-b.size();Poly v=cm(a.back(),iv);q[e]=v;for(int j=0;j<(int)b.size();j++)a[e+j]=rem(a[e+j]-cm(v,b[j]),MOD);while(!a.empty()&&a.back().zero())a.pop_back();}return {tr(q),a};}
HP hg(HP a,HP b){a=tr(a);b=tr(b);while(!b.empty()){HP r=hd(a,b).second;a=b;b=r;}return a.empty()?a:hs(a,ci(a.back()));}
std::vector<HP> minors;
void loadmins(const std::string&path){std::ifstream in(path);std::string s;in>>s;if(s=="RANK_MINORS_V2"){int nr,nc,nm;in>>nr>>nc>>nm;}else if(s!="RANK2_MINORS_V1")throw std::runtime_error("bad minors");int i,j,h,q,p;while(in>>i>>j>>h>>q>>p){HP a;while(in>>s&&s!="END"){int h=std::stoi(s),qq,c;in>>qq>>c;if((int)a.size()<=h)a.resize(h+1);if(a[h].deg()<qq)a[h].v.resize(qq+1);a[h].v[qq]=c;}minors.push_back(a);}}
int leaves=0,openpositive=0;
void solve(Poly mod,int depth=0){MOD=mod;try{HP g;for(int i=0;i<(int)minors.size();i++){g=hg(g,tr(minors[i]));std::cout<<"branch_degree "<<mod.deg()<<" minor "<<i<<" H_gcd_degree "<<int(g.size())-1<<std::endl;if(g.size()==1)break;}HP known{rem(a0poly(),MOD),rem(Poly(std::vector<F>{0,299833,232505}),MOD)};known=hs(known,ci(known.back()));HP h{Poly(),Poly(1)};int removed=0;int tag=0;for(auto b:std::vector<HP>{h,known}){int removed_here=0;while(g.size()>1){HP c=hg(g,b);if(c.size()<2)break;auto qr=hd(g,c);if(!qr.second.empty())throw std::runtime_error("open division not exact");g=qr.first;removed+=c.size()-1;removed_here+=c.size()-1;}std::cout<<"OPEN_FACTOR "<<(tag++==0?"H":"Psi")<<" multiplicity_removed "<<removed_here<<std::endl;}std::cout<<"LEAF q_degree "<<mod.deg()<<" removed_open_H_factors "<<removed<<" surviving_H_degree "<<int(g.size())-1<<std::endl;show("q_modulus",mod);for(int i=0;i<(int)g.size();i++)show("H"+std::to_string(i),g[i]);leaves++;if(g.size()>1)openpositive++;}
 catch(Split s){Poly other=exactdiv(mod,s.factor);if(gcd(other,s.factor).deg()!=0)throw std::runtime_error("non-squarefree split");std::cout<<"SPLIT q_degree "<<mod.deg()<<" into "<<s.factor.deg()<<' '<<other.deg()<<std::endl;solve(s.factor,depth+1);solve(other,depth+1);}}
int main(int argc,char**argv){try{ff::init();init_source();loadmins(argc>1?argv[1]:"build/rank2_minors.dat");Poly r=readrow(argc>2?argv[2]:"build/rank2_candidate_radical.dat"),f=readrow(argc>3?argv[3]:"build/rank2_resultant_current_open_gcd.dat");if(gcd(r,derivative(r)).deg()!=0)throw std::runtime_error("radical not squarefree");int exponent=f.deg()/r.deg();if(f.deg()%r.deg())throw std::runtime_error("nonuniform radical multiplicity needs a different certificate");Poly power=ppow(r,exponent);if(!(power==f))throw std::runtime_error("candidate radical power identity failed");Poly known=Poly::mon(1)*a0poly()*Poly(std::vector<F>{4,1})*Poly(std::vector<F>{ff::neg(15383),1});if(gcd(r,known).deg()!=0)throw std::runtime_error("unremoved forbidden q factor");std::cout<<"CANDIDATE_POWER_IDENTITY degree "<<f.deg()<<" equals radical_degree "<<r.deg()<<" power "<<exponent<<" PASS\n";solve(r);std::cout<<"LEAVES "<<leaves<<" SURVIVING_RANK_DROP_LEAVES "<<openpositive<<" quotient_operations "<<operations<<"\nGLOBAL_SQUARE_LOCUS_UNRESOLVED\n";if(openpositive)throw std::runtime_error("rank-drop certificate has surviving open leaves");}catch(std::exception&e){std::cerr<<e.what()<<std::endl;return 1;}}
