#define RANK_FRONTIER_NO_MAIN
#include "rank2_frontier.cpp"
BP det3(const std::array<std::vector<BP>,3>&m){return addB(subB(mulB(m[0][0],subB(mulB(m[1][1],m[2][2]),mulB(m[1][2],m[2][1]))),mulB(m[0][1],subB(mulB(m[1][0],m[2][2]),mulB(m[1][2],m[2][0])))),mulB(m[0][2],subB(mulB(m[1][0],m[2][1]),mulB(m[1][1],m[2][0]))));}
int main(int argc,char**argv){try{ff::init();init_source();loadtable(argc>1?argv[1]:"inputs/E_records.tsv");std::map<std::pair<int,int>,BP>S;for(int T=71;T<=74;T++)for(int m=(T<=72?44:45);m<=48;m++){if(T<73&&m==48)continue;S[{T,m}]=stop(m,T);info("S"+std::to_string(T)+"_"+std::to_string(m),S[{T,m}]);}
 F k=ff::mul(3,ff::div(270402,242747));if(!subB(S[{74,48}],scB(S[{73,48}],k)).empty())throw std::runtime_error("global degree-48 cancellation failed");std::vector<std::vector<BP>>rows(5,std::vector<BP>(3));for(int c=0;c<3;c++){int m=47-c;rows[0][c]=S[{71,m}];rows[1][c]=S[{72,m}];rows[2][c]=subB(S[{74,m}],scB(S[{73,m}],k));rows[3][c]=subB(mulB(S[{73,48}],S[{71,m-1}]),mulB(S[{71,47}],S[{73,m}]));rows[4][c]=subB(mulB(S[{73,48}],S[{72,m-1}]),mulB(S[{72,47}],S[{73,m}]));}
 std::vector<std::array<int,3>>units;for(int i=0;i<5;i++){auto u=normalize(rows[i]);units.push_back(u);std::cout<<"ROW "<<i<<" units_removed "<<u[0]<<' '<<u[1]<<' '<<u[2]<<std::endl;for(int c=0;c<3;c++)info("column"+std::to_string(c),rows[i][c]);}
 std::string pref=argc>2?argv[2]:"build/rank3";std::ofstream out(pref+"_minors.dat");out<<"RANK_MINORS_V2 5 3 10\n";int n=0;for(int i=0;i<5;i++)for(int j=i+1;j<5;j++)for(int k=j+1;k<5;k++){std::vector<BP>v{det3({rows[i],rows[j],rows[k]})};auto u=normalize(v);out<<n<<" 0 "<<u[0]<<' '<<u[1]<<' '<<u[2]<<'\n';outputBP(out,v[0]);info("MINOR"+std::to_string(n)+" rows"+std::to_string(i)+std::to_string(j)+std::to_string(k),v[0]);n++;}
 std::ofstream ro(pref+"_rows.dat");ro<<"RANK_ROWS_V3 5 3\n";for(int i=0;i<5;i++){ro<<"ROW "<<i<<' '<<units[i][0]<<' '<<units[i][1]<<' '<<units[i][2]<<'\n';for(auto&b:rows[i])outputBP(ro,b);}std::cout<<"RANK3 MATRIX GENERATED; NO DECISION YET.\n";
}catch(std::exception&e){std::cerr<<e.what()<<std::endl;return 1;}return 0;}
