import Solutions.Deformations.OperatorPolynomialIntertwining

namespace Litt3.Deformations

variable {R K M N : Type*} [CommRing R] [AddCommGroup K] [Module R K]
    [AddCommGroup M] [Module R M] [AddCommGroup N] [Module R N]

/-- Actual intertwiners agreeing on the original coefficient
generators agree on every actual element generated by their powers.
This retains the original module and its original augmentation map. -/
theorem linear_map_eq_of_power_generators (q : ℕ) (constant : K →ₗ[R] M)
    (E : Module.End R M) (F : Module.End R N)
    (generated : ∀ v : M, ∃ c : Fin q → K,
      v = ∑ j : Fin q, (E ^ j.val) (constant (c j)))
    (A B : M →ₗ[R] N)
    (commuteA : ∀ v, A (E v) = F (A v))
    (commuteB : ∀ v, B (E v) = F (B v))
    (coefficients : ∀ eta, A (constant eta) = B (constant eta)) : A = B := by
  apply LinearMap.ext
  intro v
  obtain ⟨c, rfl⟩ := generated v
  rw [map_sum, map_sum]
  apply Finset.sum_congr rfl
  intro j member
  rw [linear_map_intertwining_powers A E F commuteA,
    linear_map_intertwining_powers B E F commuteB, coefficients]

end Litt3.Deformations
