// Direct replay from stored certificates with independent square-root recursion.
#include "quadratic.hpp"
#include "ratio.hpp"
#include <filesystem>
AE readA(std::istream&f){return AE(readpoly(f));}
EP readEP(std::istream&f){int n;f>>n;EP a;for(int i=0;i<n;i++)a.push_back(readA(f));return a;}
QE readQ(std::istream&f){AE a=readA(f),b=readA(f);return QE(a,b);}
template<class R>R root71(const GP<R>&W){if(W.size()!=141)throw std::runtime_error("root recursion needs degree 140");GP<R>A(72),J(72);R ilc=W[140].inverse();for(int k=0;k<72;k++)A[k]=W[140-k]*ilc;J[0]=R(1);for(int k=1;k<=71;k++){R sum;for(int i=1;i<k;i++)sum=sum+J[i]*J[k-i];J[k]=(A[k]-sum)*R(3);}return J[71];}
struct IC {F r;Poly b0,b1,c0,c1,g;};
IC readIC(std::string path){std::ifstream f(path);IC a;std::string s;f>>s>>a.r;if(s!="DOUBLE_CONTENT_V1")throw std::runtime_error("bad incidence file");a.b0=readpoly(f);a.b1=readpoly(f);a.c0=readpoly(f);a.c1=readpoly(f);a.g=readpoly(f);return a;}
void require(bool a,const std::string&s){if(!a)throw std::runtime_error(s);}
int main(int argc,char**argv){try{ff::init();init_source();std::string dir=argc>1?argv[1]:"certificates/endpoint_content";auto source=readRF("regenerated/ratio_source.dat");auto records=load("inputs/E_records.tsv");RF B=source[1]-scale(L0,3)*source[0],Ct=divRF(scale(L0*L0,3)*source[0]-scale(L0,2)*source[1]+source[2],t);int cases=0,linear=0,quadratic=0,normchecks=0;for(std::string type:{"double","critical"})for(F r:{145049,211895,211959}){std::string stem=type+"_"+std::to_string(r);IC a=readIC(dir+"/"+type+"_content_"+std::to_string(r)+".dat");require(a.r==r,"wrong endpoint");auto bv=atEndpoint(B,r),cv=atEndpoint(type=="double"?Ct:source[0],r);require(bv[0]==a.b0&&bv[1]==a.b1&&cv[0]==a.c0&&cv[1]==a.c1,"source/incidence mismatch");Poly resultant=a.b1*a.c0-a.b0*a.c1;Poly claimed=scale(shift(a.g,12),resultant.v.back());require(resultant==claimed,"exact degree-15 resultant identity failed");require(a.g.deg()==15&&a.g.at(15)==1&&a.g.at(0)!=0,"bad eliminant shape");require(gcd(a.g,derivative(a.g))==Poly(1),"inseparable eliminant");require(gcd(a.g,a.b1)==Poly(1),"pivot not unit");AE::modulus=a.g;AE v(Poly::mon(1)),H=-peval(a.b0,v)/peval(a.b1,v),q=scale(v.pow(-3),eval(P,r));require((peval(a.c0,v)+H*peval(a.c1,v)).zero(),"second incidence does not vanish");AE a0=peval(a0poly(),q),psi=a0+H*q*(AE(299833)+scale(q,232505));(H*q*psi*(q-AE(15383))*(q-AE(1))*a0).inverse();auto E=evalE(records,H,q);
std::ifstream f(dir+"/"+stem+"_jets_"+std::to_string(a.g.at(0))+".dat");std::string magic,name;int rr;f>>magic>>name>>rr;require(magic=="HIGH_CONTENT_JETS_V1"&&name==stem&&rr==r,"bad jet certificate header");require(readpoly(f)==a.g,"jet modulus mismatch");require(readA(f)==H&&readA(f)==q,"ratio reconstruction mismatch");std::array<EP,3>ell;for(int j=0;j<3;j++){int n;f>>n;require(n==(j==0?5:0),"unexpected content valuation");ell[j]=readEP(f);auto jets=endpointJets(E,r,scale(v,ff::pow(11,j)),21);for(int k=0;k<n;k++)for(int m=0;m<3;m++)require(ac(jets[m],k).zero(),"lower local jet is nonzero");require(jetLead(jets,n)==ell[j],"local leading polynomial mismatch");ell[j].back().inverse();}
require(ell[0].size()==(type=="double"?1:3)&&ell[1].size()==2&&ell[2].size()==2,"wrong leading mu degrees");
for(int mu0=0;mu0<7;mu0++){auto W=evalW(E,AE(mu0),q);auto jet=ajet(W,r,6);for(int k=0;k<5;k++)require(ac(jet,k).zero(),"norm has lower content");AE rhs=q*q;for(auto&l:ell)rhs=rhs*aeval(l,AE(mu0));require(ac(jet,5)==rhs,"norm leading jet identity fails");normchecks++;}
if(type=="critical"){std::string token;int sheet,index;f>>token>>sheet>>index;require(token=="quadratic_candidate"&&sheet==0&&index==71,"bad quadratic candidate");QE::S=-ell[0][1]/ell[0][2];QE::T=-ell[0][0]/ell[0][2];require(readA(f)==QE::S&&readA(f)==QE::T,"quadratic relation mismatch");QE error=readQ(f),inverse=readQ(f);require(root71(qevalW(E,q))==error,"quadratic recursion disagrees with C71 certificate");require(error*inverse==QE(1),"quadratic C71 inverse fails");quadratic++;}
for(int j=1;j<3;j++){std::string token;int sheet;f>>token>>sheet;require(token=="candidate"&&sheet==j,"bad linear candidate");AE mu=readA(f);require(aeval(ell[j],mu).zero(),"candidate does not annihilate leading factor");AE err=readA(f);readA(f);readA(f);require(readpoly(f)==Poly(1),"stored common gcd not one");int idx;f>>token>>idx;require(token=="unit"&&idx==71,"bad linear unit marker");AE inverse=readA(f);require(root71(evalW(E,mu,q))==err,"linear recursion disagrees with C71 certificate");require(err*inverse==AE(1),"linear C71 inverse fails");linear++;}std::string rest;require(!(f>>rest),"extra certificate trailing data");cases++;std::cout<<"DIRECT PASS "<<stem<<" all 15 geometric parameter roots, every geometric scale\n";}
std::cout<<"DIRECT CERTIFICATE PASS: "<<cases<<" exact incidence algebras, "<<linear<<" linear and "<<quadratic<<" quadratic scale unit identities; "<<normchecks<<" norm-jet evaluations give six degree-bounded polynomial identities.\nGLOBAL SQUARE LOCUS UNRESOLVED\n";}
catch(const std::exception&e){std::cerr<<"DIRECT CHECK FAILED: "<<e.what()<<"\n";return 1;}}
