"""Exact rank-six second-order example in the AMBIENT linear series.

The family Theta+a+b*x+c*y is NOT the prescribed G_i family. This script
certifies its local square algebra at the origin, by the theorem in REPORT.md.
No bounded or unbounded source-parameter search is performed.
"""
from __future__ import annotations
import json
import sys
from pathlib import Path
ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / 'src'))
import field as F
import poly as U


def determinant(matrix: list[list[int]]) -> int:
    m = [row[:] for row in matrix]
    result = 1
    for i in range(len(m)):
        pivot = next((j for j in range(i, len(m)) if m[j][i]), None)
        if pivot is None:
            return 0
        if pivot != i:
            m[pivot], m[i] = m[i], m[pivot]
            result = F.neg(result)
        value = m[i][i]
        result = F.mul(result, value)
        inverse = F.inv(value)
        for j in range(i + 1, len(m)):
            factor = F.mul(m[j][i], inverse)
            for k in range(i, len(m)):
                m[j][k] = F.sub(m[j][k], F.mul(factor, m[i][k]))
    return result


def main() -> None:
    if sys.flags.optimize:
        raise RuntimeError('Assertions must be enabled.')
    F.init()
    inputs = json.loads((ROOT / 'data/input.json').read_text())
    # P is retained here as the literal original row, checked against the
    # ambient witness generated by the preceding reproducibility stages.
    P = [11, 22, 18, 5, 19, 20, 15, 16, 9, 22, 1]
    assert inputs['P'] == P
    U.set_curve(P)
    witness = json.loads((ROOT / 'conceptual/data/ambient_example.json').read_text())
    u, theta, J = witness['u'], witness['theta_nonsquare_on_X'], witness['J']
    assert U.norm(u) == J
    assert U.cmul(u, theta) == [J, [], []]
    assert U.norm(theta) == U.mul(J, J)
    bez = witness['squarefree_J_bezout']
    assert U.add(U.mul(bez['s'], J), U.mul(bez['t'], U.deriv(J))) == [1]
    assert U.gcd(J, P) == [1]

    def quadratic(v: list[list[int]]) -> list[int]:
        a, b, c = U.cmul(u, v)
        return U.rem(U.scale(U.add(U.mul(a, a), U.mul(U.mul(b, c), P)), 2), J)

    directions = [U.monomial(0, 0), U.monomial(1, 0), U.monomial(0, 1)]
    diagonal = [quadratic(v) for v in directions]
    columns = diagonal + [U.sub(U.sub(quadratic(U.cadd(directions[i], directions[j])), diagonal[i]), diagonal[j])
                          for i, j in [(0, 1), (0, 2), (1, 2)]]
    expected = [[2], [0, 0, 2], U.scale(U.shift(P, 20), 2), [0, 4],
                U.scale(U.shift(P, 40), 2), U.scale(U.shift(P, 41), 2)]
    assert columns == expected
    assert [len(col) - 1 for col in columns] == [0, 2, 30, 1, 50, 51]
    rows = [0, 1, 2, 30, 50, 51]
    minor = [[U.coeff(col, i) for col in columns] for i in rows]
    det = determinant(minor)
    assert det == 3
    data = {
        'scope': 'Ambient diagnostic example ONLY; not an admissible source witness',
        'ambient_family': 'Theta+a+b*x+c*y',
        'Theta': theta, 'u': u, 'J': J,
        'source_of_squarefree_certificate': 'conceptual/data/ambient_example.json',
        'parameter_monomial_order': ['a^2', 'b^2', 'c^2', 'a*b', 'a*c', 'b*c'],
        'quadratic_obstruction': '2*((a+b*x)^2+P*c*x^40*(a+b*x)+P*c^2*x^20) mod J',
        'columns_ascending_x': columns,
        'minor_rows_zero_based': rows, 'minor': minor, 'minor_determinant_K_code': det,
        'rank': 6,
        'conclusion_using_REPORT_theorem': 'Completed local square algebra at a=b=c=0 is k[[a,b,c]]/(a,b,c)^2',
        'local_length': 4, 'tangent_dimension': 3, 'socle_dimension': 3,
    }
    (ROOT / 'intersection/data/hessian_example.json').write_text(json.dumps(data, indent=2) + '\n')
    summary = {'status': 'PASS', 'norm_identity': True, 'J_squarefree_and_coprime_P': True,
               'quadratic_columns_checked': 6, 'six_by_six_minor_determinant': 3,
               'rank_six': True, 'not_a_source_witness': True,
               'no_parameter_search': True,
               'conditional_theorem_application_to_this_ambient_example': 'local length 4'}
    (ROOT / 'intersection/evidence/hessian_checks.json').write_text(json.dumps(summary, indent=2) + '\n')
    print(json.dumps(summary, indent=2))


if __name__ == '__main__':
    main()
