import Mathlib.RingTheory.Ideal.Span
import Mathlib.Algebra.BigOperators.Group.List.Basic

namespace Litt3.CartierAndSpin

variable {A : Type*} [Ring A]

/-- Literal words in the two specified ring elements. -/
def twoGeneratorWord (U V : A) (w : List Bool) : A :=
  (w.map (fun b => if b then V else U)).prod

/-- The actual left ideal generated by all ordered commutator words
through the stated total word length. For matrices this retains exactly
the row module, rather than merely a vector span of whole matrices. -/
def orderedCommutatorIdeal (U V : A) (d : ℕ) : Ideal A :=
  Ideal.span {m : A | ∃ a b : ℕ, a + b ≤ d ∧ m = (U * V - V * U) * U ^ a * V ^ b}

/-- The actual left ideal generated by all literal commutator words
through the same word length. -/
def wordCommutatorIdeal (U V : A) (d : ℕ) : Ideal A :=
  Ideal.span {m : A | ∃ w : List Bool, w.length ≤ d ∧ m = (U * V - V * U) * twoGeneratorWord U V w}

end Litt3.CartierAndSpin
