import Mathlib.Algebra.MvPolynomial.Degrees
import Mathlib.Algebra.MvPolynomial.CommRing
import Mathlib.Algebra.MvPolynomial.Eval
import Mathlib.Data.Fin.VecNotation
import Mathlib.RingTheory.Ideal.Quotient.Operations

namespace Litt3.CartierAndSpin

variable {K : Type*} [CommRing K]

/-- A bivariate polynomial with pure-power top part and an explicit remainder. -/
noncomputable def purePowerPolynomial (m : ℕ) (a b : K) (R : MvPolynomial (Fin 2) K) :
    MvPolynomial (Fin 2) K :=
  MvPolynomial.C a * MvPolynomial.X 0 ^ m +
    MvPolynomial.C b * MvPolynomial.X 1 ^ m + R

/-- The actual ideal generated by both equations, without assuming a solution. -/
noncomputable def purePowerPairIdeal (m : ℕ) (a b c d : K) (R S : MvPolynomial (Fin 2) K) :
    Ideal (MvPolynomial (Fin 2) K) :=
  Ideal.span ({purePowerPolynomial m a b R, purePowerPolynomial m c d S} :
    Set (MvPolynomial (Fin 2) K))

/-- The actual simultaneous solution set in an arbitrary extension field. -/
noncomputable def purePowerPairSolutionSet {Ω : Type*} [Field Ω] [Algebra K Ω]
    (m : ℕ) (a b c d : K) (R S : MvPolynomial (Fin 2) K) : Set (Ω × Ω) :=
  {point | MvPolynomial.aeval ![point.1, point.2] (purePowerPolynomial m a b R) = 0 ∧
    MvPolynomial.aeval ![point.1, point.2] (purePowerPolynomial m c d S) = 0}

end Litt3.CartierAndSpin
