

# This file was *autogenerated* from the file scratch_enumerate_cross.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_414 = Integer(414)
load("routes/global/67_CUBIC_CROSS_ROSATI_GAP_CERTIFICATE.sage")

def count_lengths(gram, bound):
    transform = (_sage_const_2  * gram).LLL_gram()
    reduced_gram = transform.transpose() * gram * transform
    form = QuadraticForm(ZZ, _sage_const_2  * reduced_gram)
    by_norm = form.short_vector_list_up_to_length(bound + _sage_const_1 )
    return [(n, len(vs)) for n, vs in enumerate(by_norm) if n and vs]

print("I1 short lengths <=414:", count_lengths(gram_1, _sage_const_414 ))
print("I2 short lengths <=414:", count_lengths(gram_2, _sage_const_414 ))

