#include <algorithm>
#include <array>
#include <cassert>
#include <chrono>
#include <cstdint>
#include <fstream>
#include <iostream>
#include <numeric>
#include <set>
#include <stdexcept>
#include <string>
#include <vector>
using U=uint32_t; using P=std::vector<U>; using Row=std::vector<P>;
constexpr U Q=390625, HALF=625;
#ifndef AUXILIARIES
#define AUXILIARIES 0
#endif
constexpr int AUX=AUXILIARIES, PRODS=21, NT=PRODS+AUX, RAW=36+AUX, COLS=126+3*AUX, BASECOLS=105+2*AUX;
int baseoffset(int c){return c<PRODS?5*c:105+2*(c-PRODS);}int basewidth(int c){return c<PRODS?5:2;}int offset(int c){return c<PRODS?6*c:126+3*(c-PRODS);}
std::vector<int32_t> logs; std::vector<U> exps, adds, negs;
template<class T> std::vector<T> read(const std::string& p){std::ifstream f(p,std::ios::binary|std::ios::ate);if(!f)throw std::runtime_error(p);auto n=f.tellg();f.seekg(0);std::vector<T> a(size_t(n)/sizeof(T));f.read((char*)a.data(),n);return a;}
U add(U a,U b){return adds[(a%HALF)*HALF+b%HALF]+HALF*adds[(a/HALF)*HALF+b/HALF];}
U sub(U a,U b){return add(a,negs[b]);}
U mul(U a,U b){return !a||!b?0:exps[logs[a]+logs[b]];}
U inv(U a){assert(a);return exps[Q-1-logs[a]];}
void trim(P& a){while(!a.empty()&&!a.back())a.pop_back();}
P scale(P a,U c){for(auto& v:a)v=mul(v,c);trim(a);return a;}
P plus(P a,const P& b,bool minus=false){a.resize(std::max(a.size(),b.size()));for(size_t i=0;i<b.size();i++)a[i]=minus?sub(a[i],b[i]):add(a[i],b[i]);trim(a);return a;}
void accumulate(P& a,const P& b,size_t offset=0,bool minus=false){a.resize(std::max(a.size(),offset+b.size()));for(size_t i=0;i<b.size();i++)a[offset+i]=minus?sub(a[offset+i],b[i]):add(a[offset+i],b[i]);trim(a);}
P product(const P& a,const P& b){
 if(a.empty()||b.empty())return {};if(std::min(a.size(),b.size())<24){P r(a.size()+b.size()-1);for(size_t i=0;i<a.size();i++)if(a[i])for(size_t j=0;j<b.size();j++)if(b[j])r[i+j]=add(r[i+j],mul(a[i],b[j]));trim(r);return r;}
 if(std::max(a.size(),b.size())>2*std::min(a.size(),b.size())){const P &small=a.size()<b.size()?a:b,&large=a.size()<b.size()?b:a;P r;for(size_t k=0;k<large.size();k+=small.size()){P part(large.begin()+k,large.begin()+std::min(large.size(),k+small.size()));accumulate(r,product(small,part),k);}return r;}
 size_t h=(std::max(a.size(),b.size())+1)/2;P a0(a.begin(),a.begin()+std::min(h,a.size())),a1(a.begin()+std::min(h,a.size()),a.end()),b0(b.begin(),b.begin()+std::min(h,b.size())),b1(b.begin()+std::min(h,b.size()),b.end());auto z0=product(a0,b0),z2=product(a1,b1),z1=plus(plus(product(plus(a0,a1),plus(b0,b1)),z0,true),z2,true);P r=z0;accumulate(r,z1,h);accumulate(r,z2,2*h);return r;
}
std::pair<P,P> division(P a,const P& b){assert(!b.empty());if(a.size()<b.size())return {{},a};P q(a.size()-b.size()+1);U lc=inv(b.back());while(a.size()>=b.size()){size_t k=a.size()-b.size();U c=mul(a.back(),lc);q[k]=c;for(size_t j=0;j<b.size();j++)a[k+j]=sub(a[k+j],mul(c,b[j]));trim(a);}trim(q);return {q,a};}
P gcd(P a,P b){while(!b.empty()){auto r=division(a,b).second;a=b;b=r;}return a.empty()?a:scale(a,inv(a.back()));}
U evaluate(const P& a,U x=1){U r=0;for(size_t i=a.size();i-->0;)r=add(mul(r,x),a[i]);return r;}
void writeP(std::ostream& f,const P& p){U n=p.size();f.write((char*)&n,4);f.write((char*)p.data(),n*4);}
void writeU(std::ostream& f,U a){f.write((char*)&a,4);}
P readP(const std::vector<U>& a,size_t& k){U n=a[k++];P p(a.begin()+k,a.begin()+k+n);k+=n;return p;}
std::chrono::steady_clock::time_point start;double elapsed(){return std::chrono::duration<double>(std::chrono::steady_clock::now()-start).count();}
P unit;
P supported(P f){P result={1};while(f.size()>1){P g=gcd(f,unit);if(g.size()<=1)break;result=product(result,g);auto qr=division(f,g);assert(qr.second.empty());f=qr.first;}return result;}
P strip(Row& r){P content;for(auto& p:r)if(!p.empty()){content=gcd(content,p);if(content.size()==1)break;}if(content.empty())return {1};P d=supported(content);if(d.size()>1)for(auto& p:r){auto qr=division(p,d);assert(qr.second.empty());p=qr.first;}return d;}
int main(int argc,char**argv){try{
 if(argc<2)throw std::runtime_error("usage native_d10m6_module INPUTDIR [seconds=1200] [extra=25]");std::string dir=argv[1];int seconds=argc>2?atoi(argv[2]):1200,extra=argc>3?atoi(argv[3]):25;start=std::chrono::steady_clock::now();logs=read<int32_t>(dir+"/logs.bin");exps=read<U>(dir+"/exps.bin");auto addshort=read<uint16_t>(dir+"/addhalf.bin");adds.assign(addshort.begin(),addshort.end());assert(logs.size()==Q&&adds.size()==HALF*HALF);negs.resize(Q);for(U x=0;x<Q;x++){U a=x,n=0,p=1;for(int j=0;j<8;j++){n+=((5-a%5)%5)*p;a/=5;p*=5;}negs[x]=n;}
 auto fixtures=read<U>(dir+"/fixtures.bin");size_t fk=0;U count=fixtures[fk++];for(U i=0;i<count;i++){auto f=readP(fixtures,fk),g=readP(fixtures,fk),fg=readP(fixtures,fk),q=readP(fixtures,fk),r=readP(fixtures,fk),gg=readP(fixtures,fk);assert(product(f,g)==fg);assert(division(f,g)==std::make_pair(q,r));assert(gcd(f,g)==gg);}assert(fk==fixtures.size());std::cout<<"ARITHMETIC_FIXTURES_PASS "<<count<<std::endl;
 auto h=read<U>(dir+"/header.bin"),raw=read<U>(dir+"/matrix.bin"),kb=read<U>(dir+"/kernel.bin"),us=read<U>(dir+"/units.bin");assert(h.size()==7&&h[1]==RAW&&h[2]%3==0&&h[3]==8&&h[4]==6&&h[5]==2);int erange=h[2]/3,nrows=h[0],compatibility_start=nrows-16-(AUX?15:0);std::vector<int>original;for(int r=0;r<nrows;r++)if(r<compatibility_start||r>=compatibility_start+16)original.push_back(r);int nbase=original.size();size_t uk=0;unit={1};while(uk<us.size()){P p=readP(us,uk);assert(!p.empty());unit=product(unit,p);}assert(uk==us.size());
 std::vector<std::pair<int,int>> p8,p6;for(int i=0;i<8;i++)for(int j=i;j<8;j++)p8.push_back({i,j});for(int i=0;i<6;i++)for(int j=i;j<6;j++)p6.push_back({i,j});
 std::array<std::array<std::array<P,2>,6>,8>B;for(int i=0;i<8;i++)for(int j=0;j<6;j++)for(int l=0;l<2;l++){auto off=((i*6+j)*2+l)*h[6];B[i][j][l]=P(kb.begin()+off,kb.begin()+off+h[6]);trim(B[i][j][l]);}
 std::vector<std::vector<std::array<P,3>>>T(RAW,std::vector<std::array<P,3>>(NT));
 for(int a=0;a<36;a++){auto[i,j]=p8[a];for(int c=0;c<21;c++){auto[f,g]=p6[c];for(int l=0;l<2;l++)for(int m=0;m<2;m++){P z;if(i==j){z=product(B[i][f][l],B[i][g][m]);if(f!=g)z=scale(z,2);}else if(f==g)z=product(B[i][f][l],B[j][f][m]);else z=plus(product(B[i][f][l],B[j][g][m]),product(B[i][g][l],B[j][f][m]));T[a][c][l+m]=plus(T[a][c][l+m],z);}}}
 for(int j=0;j<AUX;j++)T[36+j][PRODS+j][0]={1};
 std::vector<std::vector<U>> numerical(nrows,std::vector<U>(BASECOLS));for(int r=0;r<nrows;r++)for(int a=0;a<RAW;a++){std::array<U,3> av={0,0,0};for(int ep=0;ep<erange;ep++)for(int l=0;l<3;l++)av[l]=add(av[l],raw[(r*RAW+a)*h[2]+ep*3+l]);for(int c=0;c<NT;c++)for(int l=0;l<3;l++)if(av[l])for(int m=0;m<3;m++)if(!T[a][c][m].empty()){assert(l+m<basewidth(c));numerical[r][baseoffset(c)+l+m]=add(numerical[r][baseoffset(c)+l+m],mul(av[l],evaluate(T[a][c][m])));}}
 for(int r=compatibility_start;r<compatibility_start+16;r++)for(U x:numerical[r])assert(!x);
 std::vector<std::vector<U>> echelon;std::vector<int>npiv,selected;std::set<int>selectedset;
 std::vector<int>equation_ids(2*nbase);std::iota(equation_ids.begin(),equation_ids.end(),0);if(AUX)for(int j=nbase-15;j<nbase;j++)equation_ids.push_back(2*nbase+j);
 for(int id:equation_ids){int r=original[id%nbase],shift=id/nbase;std::vector<U>v(COLS);for(int c=0;c<NT;c++)for(int l=0;l<basewidth(c);l++){U value=numerical[r][baseoffset(c)+l];if(l+shift>=basewidth(c)+1)assert(!value);else v[offset(c)+l+shift]=value;}for(size_t k=0;k<npiv.size();k++)if(v[npiv[k]]){U z=v[npiv[k]];for(int j=npiv[k];j<COLS;j++)v[j]=sub(v[j],mul(z,echelon[k][j]));}int pivot=-1;for(int j=0;j<COLS;j++)if(v[j]){pivot=j;break;}if(pivot<0)continue;U z=inv(v[pivot]);for(int j=pivot;j<COLS;j++)v[j]=mul(v[j],z);auto at=std::lower_bound(npiv.begin(),npiv.end(),pivot)-npiv.begin();npiv.insert(npiv.begin()+at,pivot);echelon.insert(echelon.begin()+at,v);selected.push_back(id);selectedset.insert(id);}
 assert(selected.size()==95+3*AUX);for(int c=0;c<PRODS;c++){std::vector<U>v(COLS);v[offset(c)]=1;for(size_t k=0;k<npiv.size();k++)if(v[npiv[k]]){U z=v[npiv[k]];for(int j=npiv[k];j<COLS;j++)v[j]=sub(v[j],mul(z,echelon[k][j]));}for(U x:v)assert(!x);}
 for(auto it=equation_ids.rbegin();it!=equation_ids.rend()&&extra>0;it++){int id=*it;if(selectedset.insert(id).second){selected.push_back(id);extra--;}}
 std::cout<<"SELECTED "<<selected.size()<<" NUMERICRANK95 SECONDS "<<elapsed()<<std::endl;
 std::set<int>needed;for(int id:selected)needed.insert(original[id%nbase]);std::vector<Row> base(nrows);std::ofstream cert(dir+"/native_module_operations.bin",std::ios::binary);writeU(cert,0x4c495433);writeU(cert,selected.size());for(int id:selected)writeU(cert,id);
 for(int r:needed){Row v(BASECOLS);for(int a=0;a<RAW;a++){std::array<P,3>av;for(int l=0;l<3;l++){av[l].resize(erange);for(int ep=0;ep<erange;ep++)av[l][ep]=raw[(r*RAW+a)*h[2]+ep*3+l];trim(av[l]);}for(int c=0;c<NT;c++)for(int l=0;l<3;l++)if(!av[l].empty())for(int m=0;m<3;m++)if(!T[a][c][m].empty()){assert(l+m<basewidth(c));v[baseoffset(c)+l+m]=plus(v[baseoffset(c)+l+m],product(av[l],T[a][c][m]));}}P divisor=strip(v);writeU(cert,1);writeU(cert,r);writeP(cert,divisor);base[r]=std::move(v);std::cout<<"PREPARED "<<r<<" SECONDS "<<elapsed()<<std::endl;}
 std::vector<Row> rows;for(int id:selected){Row row(COLS);int r=original[id%nbase],shift=id/nbase;for(int c=0;c<NT;c++)for(int l=0;l<basewidth(c);l++){if(l+shift>=basewidth(c)+1)assert(base[r][baseoffset(c)+l].empty());else row[offset(c)+l+shift]=base[r][baseoffset(c)+l];}rows.push_back(std::move(row));}base.clear();raw.clear();raw.shrink_to_fit();std::cout<<"MATRIX_READY "<<rows.size()<<" SECONDS "<<elapsed()<<std::endl;
 size_t rank=0;std::vector<int>pivots;size_t operations=0;auto opstrip=[&](size_t i){P d=strip(rows[i]);if(d.size()>1){writeU(cert,5);writeU(cert,i);writeP(cert,d);operations++;}};
 if(argc>4){auto history=read<U>(argv[4]);size_t hk=1;U count=history[hk++];hk+=count;bool found=false;while(hk<history.size()){U op=history[hk++];if(op==1||op==5){hk++;U n=history[hk++];hk+=n;}else if(op==2||op==4)hk+=2;else if(op==3){hk+=2;U n=history[hk++];hk+=n;}else if(op==10){U n=history[hk++];assert(n==rows.size());for(auto&r:rows)for(P&p:r)p=readP(history,hk);found=true;break;}else throw std::runtime_error("unexpected checkpoint opcode");}assert(found);cert.close();cert.open(dir+"/native_module_operations.bin",std::ios::binary|std::ios::trunc);cert.write((char*)history.data(),hk*4);std::cout<<"RESUMED_POPOV PREFIXWORDS "<<hk<<" SECONDS "<<elapsed()<<std::endl;}
 auto leading=[&](const Row&r){std::pair<size_t,int> result={0,-1};for(int j=0;j<COLS;j++)if(!r[j].empty()&&r[j].size()>=result.first)result={r[j].size(),j};return result;};
 size_t reductions=0;bool changed=true;while(changed){changed=false;for(size_t i=0;i<rows.size();i++){P d=strip(rows[i]);if(d.size()>1){writeU(cert,5);writeU(cert,i);writeP(cert,d);operations++;changed=true;std::cout<<"SATURATE_ROW "<<i<<" DEG "<<d.size()-1<<" SECONDS "<<elapsed()<<std::endl;}}
 while(true){std::array<int,COLS>owner;owner.fill(-1);int i=-1,k=-1;for(size_t j=0;j<rows.size();j++){auto [degree,position]=leading(rows[j]);if(position<0)continue;if(owner[position]>=0){i=j;k=owner[position];break;}owner[position]=j;}if(i<0)break;auto [di,pi]=leading(rows[i]);auto [dk,pk]=leading(rows[k]);assert(pi==pk);if(di<dk){std::swap(i,k);std::swap(di,dk);}U scalar=mul(rows[i][pi].back(),inv(rows[k][pk].back()));P multiplier(di-dk+1);multiplier.back()=scalar;for(int col=0;col<COLS;col++)if(!rows[k][col].empty()){P term=scale(rows[k][col],scalar);term.insert(term.begin(),di-dk,0);rows[i][col]=plus(rows[i][col],term,true);}writeU(cert,3);writeU(cert,i);writeU(cert,k);writeP(cert,multiplier);operations++;reductions++;if(reductions%1000==0){size_t nonzero=0,totaldegree=0,maxdegree=0;for(auto&r:rows){auto [d,p]=leading(r);if(p>=0){nonzero++;totaldegree+=d-1;maxdegree=std::max(maxdegree,d-1);}}std::cout<<"POPOV "<<reductions<<" ROWS "<<nonzero<<" TOTALDEG "<<totaldegree<<" MAXDEG "<<maxdegree<<" SECONDS "<<elapsed()<<std::endl;}if(elapsed()>seconds)throw std::runtime_error("bounded Popov time checkpoint");}}
 size_t nonzero=0,totaldegree=0,maxdegree=0;for(auto&r:rows){auto [d,p]=leading(r);if(p>=0){nonzero++;totaldegree+=d-1;maxdegree=std::max(maxdegree,d-1);}}std::cout<<"POPOV_COMPLETE ROWS "<<nonzero<<" TOTALDEG "<<totaldegree<<" MAXDEG "<<maxdegree<<" SECONDS "<<elapsed()<<std::endl;writeU(cert,10);writeU(cert,rows.size());for(auto&r:rows)for(P&p:r)writeP(cert,p);cert.flush();
 {
 std::array<int,COLS>owner;owner.fill(-1);std::vector<size_t>degrees(rows.size());for(size_t i=0;i<rows.size();i++){auto[d,p]=leading(rows[i]);if(p>=0){assert(owner[p]<0);owner[p]=i;degrees[i]=d;}}
 auto normalform=[&](Row t){Row rem(COLS);size_t reduction=0;while(true){auto[d,p]=leading(t);if(p<0)break;int i=owner[p];if(i>=0&&d>=degrees[i]){P q=division(t[p],rows[i][p]).first;assert(!q.empty());for(int j=0;j<COLS;j++)if(!rows[i][j].empty())t[j]=plus(t[j],product(q,rows[i][j]),true);reduction++;}else{if(rem[p].size()<d)rem[p].resize(d);rem[p][d-1]=add(rem[p][d-1],t[p].back());t[p].pop_back();trim(t[p]);}if(elapsed()>seconds)throw std::runtime_error("bounded normalform time checkpoint");}return rem;};
 std::vector<Row> targetnormal;bool direct=true;for(int c=0;c<PRODS;c++){Row t(COLS);t[offset(c)]={1};auto n=normalform(t);for(P&p:n)if(!p.empty())direct=false;targetnormal.push_back(n);}std::cout<<"DIRECT_CONSTANT_MEMBERSHIP "<<direct<<" SECONDS "<<elapsed()<<std::endl;
 if(direct){writeU(cert,12);writeP(cert,P{1});for(auto&r:targetnormal)for(P&p:r)writeP(cert,p);std::cout<<"SCALAR_RESULT PASS1 DEG0 BADDEG0 SECONDS "<<elapsed()<<std::endl;return 0;}
 int bound=argc>5?atoi(argv[5]):256;Row initial(COLS);for(int c=0;c<PRODS;c++)initial[offset(c)]={U((1237*c+19)%Q)};Row current=normalform(initial);std::vector<Row>sequence;P scalar;P C={1},BB={1};int L=0,mm=1;U discrepancy_old=1;
 for(int step=0;step<2*bound;step++){sequence.push_back(current);U projection=0;for(int j=0;j<COLS;j++)for(size_t e=0;e<current[j].size();e++)if(current[j][e])projection=add(projection,mul(current[j][e],U((uint64_t(j+1)*7777+uint64_t(e+1)*1237+19)%Q)));scalar.push_back(projection);U discrepancy=projection;for(size_t i=1;i<C.size();i++)if(i<=size_t(step))discrepancy=add(discrepancy,mul(C[i],scalar[step-i]));if(!discrepancy)mm++;else{P saved=C;U cc=mul(discrepancy,inv(discrepancy_old));P update=scale(BB,cc);::accumulate(C,update,size_t(mm),true);if(2*L<=step){L=step+1-L;BB=saved;discrepancy_old=discrepancy;mm=1;}else mm++;}if(step%16==0)std::cout<<"KRYLOV "<<step<<" RECURRENCEDEG "<<L<<" NORMALDEG "<<leading(current).first<<" SECONDS "<<elapsed()<<std::endl;for(P&p:current)if(!p.empty())p.insert(p.begin(),0);current=normalform(current);if(leading(current).first>512)throw std::runtime_error("normalform degree escaped finite torsion band");}
 C.resize(L+1);P annihilator(C.rbegin(),C.rend());trim(annihilator);Row mixedcheck(COLS);for(size_t i=0;i<annihilator.size();i++)for(int j=0;j<COLS;j++)mixedcheck[j]=plus(mixedcheck[j],scale(sequence[i][j],annihilator[i]));bool mixedpass=true;for(P&p:mixedcheck)if(!p.empty())mixedpass=false;std::cout<<"MIXED_SCALAR_CHECK "<<mixedpass<<" DEG "<<annihilator.size()-1<<" SECONDS "<<elapsed()<<std::endl;
 writeU(cert,12);writeP(cert,annihilator);bool allpass=mixedpass;for(int c=0;c<PRODS;c++){Row t(COLS);t[offset(c)]=annihilator;auto rem=normalform(t);bool pass=true;for(P&p:rem){if(!p.empty())pass=false;writeP(cert,p);}allpass&=pass;std::cout<<"SCALAR_TARGET "<<c<<" PASS "<<pass<<" SECONDS "<<elapsed()<<std::endl;}P allowed=supported(annihilator);auto qr=division(annihilator,allowed);assert(qr.second.empty());writeU(cert,13);writeP(cert,qr.first);writeU(cert,allpass);std::cout<<"SCALAR_RESULT PASS "<<allpass<<" DEG "<<annihilator.size()-1<<" BADDEG "<<qr.first.size()-1<<" SECONDS "<<elapsed()<<std::endl;return allpass?0:2;
 }
 for(int col=0;col<126;col++){size_t chosen=rows.size();for(size_t i=rank;i<rows.size();i++)if(!rows[i][col].empty()&&(chosen==rows.size()||rows[i][col].size()<rows[chosen][col].size()))chosen=i;if(chosen==rows.size())continue;
 auto swaprows=[&](size_t i,size_t j){std::swap(rows[i],rows[j]);writeU(cert,2);writeU(cert,i);writeU(cert,j);operations++;};if(chosen!=rank)swaprows(chosen,rank);
 while(true){chosen=rows.size();for(size_t i=rank+1;i<rows.size();i++)if(!rows[i][col].empty()&&(chosen==rows.size()||rows[i][col].size()<rows[chosen][col].size()))chosen=i;if(chosen==rows.size())break;auto qr=division(rows[chosen][col],rows[rank][col]);if(!qr.first.empty()){for(int j=col;j<126;j++)if(!rows[rank][j].empty())rows[chosen][j]=plus(rows[chosen][j],product(qr.first,rows[rank][j]),true);writeU(cert,3);writeU(cert,chosen);writeU(cert,rank);writeP(cert,qr.first);operations++;opstrip(chosen);}if(!rows[chosen][col].empty())swaprows(chosen,rank);
 size_t degree=0;for(const auto&p:rows[rank])degree=std::max(degree,p.size());if(elapsed()>seconds||degree>4000)throw std::runtime_error("bounded polynomial growth/time checkpoint");}
 U z=inv(rows[rank][col].back());if(z!=1){for(P&p:rows[rank])p=scale(p,z);writeU(cert,4);writeU(cert,rank);writeU(cert,z);operations++;}pivots.push_back(col);rank++;size_t degree=0;for(const auto&p:rows[rank-1])degree=std::max(degree,p.size());std::cout<<"PIVOT "<<rank<<" COLUMN "<<col<<" DEG "<<rows[rank-1][col].size()-1<<" MAX "<<degree<<" OPS "<<operations<<" SECONDS "<<elapsed()<<std::endl;}
 P bad={1};bool pass=true;for(int c=0;c<21;c++){Row t(126);t[c*6]={1};writeU(cert,6);writeU(cert,c);for(size_t i=0;i<rank;i++){int col=pivots[i];if(t[col].empty())continue;auto qr=division(t[col],rows[i][col]);if(qr.second.empty()){for(int j=col;j<126;j++)t[j]=plus(t[j],product(qr.first,rows[i][j]),true);writeU(cert,3);writeU(cert,0xffffffff);writeU(cert,i);writeP(cert,qr.first);}else{P p=rows[i][col],coefficient=t[col];for(int j=col;j<126;j++)t[j]=plus(product(p,t[j]),product(coefficient,rows[i][j]),true);writeU(cert,7);writeU(cert,i);writeP(cert,p);writeP(cert,coefficient);P allowed=supported(p),unknown=division(p,allowed).first;P gg=gcd(bad,unknown);bad=product(bad,division(unknown,gg).first);strip(t);}}for(const P&p:t)if(!p.empty())pass=false;writeU(cert,8);for(P&p:t)writeP(cert,p);std::cout<<"TARGET "<<c<<" BADDEG "<<bad.size()-1<<" PASS "<<pass<<" SECONDS "<<elapsed()<<std::endl;}
 writeU(cert,9);writeP(cert,bad);writeU(cert,pass);std::cout<<"RESULT PASS "<<pass<<" RANK "<<rank<<" BADDEG "<<bad.size()-1<<" SECONDS "<<elapsed()<<std::endl;return pass?0:2;
 }catch(const std::exception&e){std::cerr<<"ERROR "<<e.what()<<" SECONDS "<<elapsed()<<std::endl;return 1;}}
