#!/usr/bin/env python3
"""Verify a whole-curve unit-ideal certificate by polynomial multiplication.

This does not run a gcd or logarithmic-derivative factorization algorithm.
The input resultants must first be regenerated by the certified complete-
field Hermite procedure. Their exact canonical hashes are checked here.
"""
from pathlib import Path
import argparse, hashlib, json, time
import numpy as np
from ff import Poly
from gmp_poly import install
from known_unit_factorization import rebuild
install()
ROOT = Path(__file__).resolve().parents[1]


def digest(p):
    return hashlib.sha256(p.a.astype('<u4').tobytes()).hexdigest()


def verify(resultants):
    start = time.time()
    cert = json.loads((ROOT/'data/global_resultant_certificate.json').read_text())
    reconstruction = json.loads((ROOT/'checks/resultant_reconstruction.json').read_text())
    bounds = json.loads((ROOT/'data/resultant_pole_bounds.json').read_text())['resultants']
    assert cert['status'] == 'global ordinary-double-root square ideal is the unit ideal'
    assert cert['resultant_indices'] in ([72,73], [72,73,74])
    assert cert['tail_indices'] == [71] + cert['resultant_indices']
    fs, refs = [], []
    source = 'data/zero_scale_compact.json'
    old = json.loads((ROOT/source).read_text())['unit_factors']
    for i, f in enumerate(old):
        fs.append(Poly(f)); refs.append({'source':source, 'index':i})
    for name in ('plus','minus'):
        source = f'data/slope_{name}_model.json'
        model = json.loads((ROOT/source).read_text())
        product = Poly(1)
        for i, f in enumerate(model['factors']):
            f = Poly(f); fs.append(f); product = product*f
            refs.append({'source':source, 'index':i})
        assert product == Poly(model['norm_squarefree'])
    assert len(fs) == 51 and refs == cert['unit_factor_sources']
    product = Poly(1)
    for f in fs:
        assert f[f.degree()] == 1 and product.gcd(f) == 1
        product = product*f
    assert len(cert['unit_gcd_factorization']['exponents']) == len(fs)
    assert all(isinstance(e,int) and e >= 0 for e in cert['unit_gcd_factorization']['exponents'])
    assert cert['unit_gcd_factorization']['scalar'] != 0
    D0 = rebuild(cert['unit_gcd_factorization'], fs)
    data = np.load(resultants)
    ps = {n:Poly(data[str(n)]) for n in cert['resultant_indices']}
    for n,p in ps.items():
        assert p.degree() <= bounds[str(n)]['degree_bound']
        assert p.degree() == cert['reconstructed_resultant_degrees'][str(n)]
        assert p.degree() == reconstruction['resultants'][str(n)]['actual_degree']
        assert digest(p) == cert['reconstructed_resultant_hashes'][str(n)]
        assert digest(p) == reconstruction['resultants'][str(n)]['canonical_sha256']
    arrays = np.load(ROOT/cert['bezout_array_file'])
    U,V = Poly(arrays['U']),Poly(arrays['V'])
    G12 = U*ps[72] + V*ps[73]
    stage = cert['stages'][0]
    assert stage['left'] == 72 and stage['right'] == 73
    assert stage['coefficient_degrees'] == [U.degree(),V.degree()]
    assert stage['gcd_degree'] == G12.degree() and stage['gcd_sha256'] == digest(G12)
    if cert['resultant_indices'] == [72,73]:
        assert len(cert['stages']) == 1 and set(arrays.files) == {'U','V'}
        assert G12 == D0
    else:
        assert len(cert['stages']) == 2 and set(arrays.files) == {'U','V','Z','W'}
        Z,W = Poly(arrays['Z']),Poly(arrays['W'])
        final = Z*G12 + W*ps[74]
        stage = cert['stages'][1]
        assert stage['left'] == 'gcd12' and stage['right'] == 74
        assert stage['coefficient_degrees'] == [Z.degree(),W.degree()]
        assert stage['gcd_degree'] == final.degree() and stage['gcd_sha256'] == digest(final)
        assert final == D0
    result = {'status':'exact global unit-ideal certificate verified by multiplication',
              'tail_indices':cert['tail_indices'], 'unit_product_degree':D0.degree(),
              'nonzero_unit_factor_powers':sum(e!=0 for e in cert['unit_gcd_factorization']['exponents']),
              'known_q_unit_factors':len(fs), 'bezout_stages':len(cert['stages']),
              'gcd_algorithm_rerun':False, 'factorization_algorithm_rerun':False,
              'boundary_dependencies':['src/verify_all.py','src/verify_slopes.py','src/slope_companions.py --verify'],
              'identity_dependencies':['src/check_global_zero.py','src/check_resultant_bounds.py',
                                       'src/compute_resultant_samples.py','src/reconstruct_resultants.py'],
              'seconds':round(time.time()-start,3)}
    (ROOT/'checks/global_resultant_verification.json').write_text(json.dumps(result,indent=2)+'\n')
    print('GLOBAL_UNIT_IDEAL_CERTIFICATE_MULTIPLICATION_PASSED='+json.dumps(result),flush=True)
    return result


if __name__ == '__main__':
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--resultants',default=str(ROOT/'scratch/global_resultants.npz'))
    verify(parser.parse_args().resultants)
