"""Read-only verifier for the retained exact source and boundary certificates."""
from pathlib import Path
import json,hashlib,tempfile,sys,time,platform
import numpy as np
import reconstruct,cramer,c_zero,boundary_cases,check_resultant,random
from ff import *
from ext import EP,Element as E
import ext
from residual import RATIO,peval,check_open,residual,Tails
from factor import irreducible
from check_frobenius import run_checks
ROOT=Path(__file__).resolve().parents[1]

def check_hashes():
 manifest=ROOT/'SHA256SUMS'
 if not manifest.exists():print('Manifest not present in this working checkpoint; arithmetic checks continue.',flush=True);return
 count=0
 for line in manifest.read_text().splitlines():
  digest,name=line.split('  ',1);p=ROOT/name
  assert p.is_file(),name
  assert hashlib.sha256(p.read_bytes()).hexdigest()==digest,name
  count+=1
 print('SHA-256 manifest:',count,'files verified',flush=True)

def check_input_arithmetic():
 rng=random.Random(20260927)
 for _ in range(10000):
  a=rng.randrange(390625);b=rng.randrange(390625)
  assert mul(a,b)==lib.ff_rawmul(a,b)
  aa,bb=a,b;ss=0;place=1
  for j in range(8):
   ss+=place*((aa%5+bb%5)%5);aa//=5;bb//=5;place*=5
  assert add(a,b)==ss
 b,c,e,d,a0=[Poly(RATIO[k]) for k in ['b','c','e','d','a0']]
 assert c*c-3*b*e==Poly(RATIO['C'])
 assert Poly(RATIO['C']).gcd(Poly(RATIO['C']).derivative())==1
 assert d.eval(118020)==0 and a0.eval(10149)==0
 for degree in [1,2,5,14]:
  mm=Poly([rng.randrange(390625) for _ in range(degree)]+[1]);ext.context(mm)
  for _ in range(25):
   pa=Poly([rng.randrange(390625) for _ in range(degree)]);pb=Poly([rng.randrange(390625) for _ in range(degree)])
   ea,eb=E(pa),E(pb)
   assert ea*eb==E(pa*pb%mm)
   assert ea**5==E(pa.powmod(5,mm))
   try:assert ea*ea.inverse()==1
   except ext.NonUnit:assert pa.gcd(mm).degree()>0
 print('Input identities and 10,000 field/100 finite-algebra regression cases passed.',flush=True)

def check_reconstruction():
 originals={'source_affine6.json':(ROOT/'data/source_affine6.json').read_bytes(),'source_cramer.json':(ROOT/'data/source_cramer.json').read_bytes()}
 with tempfile.TemporaryDirectory() as td:
  temp=Path(td);(temp/'data').mkdir();(temp/'checks').mkdir()
  old1,old2=reconstruct.ROOT,cramer.ROOT
  try:
   reconstruct.ROOT=temp;cramer.ROOT=temp
   reconstruct.main();cramer.main()
  finally:reconstruct.ROOT=old1;cramer.ROOT=old2
  for name,blob in originals.items():assert (temp/'data'/name).read_bytes()==blob,name
 print('Source and Cramer data regenerated byte-for-byte.',flush=True)

def verify_identity(cert,q,u):
 check_open(q,u)
 _,A=residual(q,u);ts=Tails(A)
 lhs=EP()
 assert len(cert['tail_indices'])==len(cert['bezout_coefficients'])
 for n,coeffs,deg in zip(cert['tail_indices'],cert['bezout_coefficients'],cert['tail_degrees']):
  t=ts.tail(n);assert t.degree()==deg
  z=EP([E(row) for row in coeffs]);lhs=lhs+z*t
 assert lhs==EP([0]*cert['mu_power']+[1])


def verify_boundaries():
 ratios=0;cases=0;qmods=[]
 for case,original in boundary_cases.make_cases():
  start=time.time();summary=json.loads((ROOT/'checks'/(case+'.json')).read_text())
  allowed,regen=boundary_cases.allowed_modulus(case,original)
  for key,val in regen.items():assert summary[key]==val,(case,key)
  assert summary['status']=='excluded'
  total=Poly(1)
  for block in summary['blocks']:
   print('  replay',block['certificate'],flush=True)
   cert=json.loads((ROOT/block['certificate']).read_text());assert cert['case']==case
   mod=Poly(cert['modulus']);total=total*mod
   assert mod.degree()==block['degree']
   q,u=boundary_cases.point(case,mod);verify_identity(cert,q,u)
   ratios+=mod.degree();cases+=1
  assert total==allowed,(case,'coverage')
  assert allowed.gcd(allowed.derivative())==Poly(1)
  if case!='cubic_leading_companion':qmods.append(allowed)
  print(case+':',allowed.degree(),'allowed ratios, all certificate identities verified; '+str(round(time.time()-start,3))+'s',flush=True)
 model=json.loads((ROOT/'data/c_zero_primitive.json').read_text())
 mod,qrep,urep,regen=c_zero.primitive_model(save=False);assert regen==model
 summary=json.loads((ROOT/'checks/c_zero.json').read_text());total=Poly(1)
 for block in summary['factors']:
  cert=json.loads((ROOT/block['certificate']).read_text());f=Poly(cert['modulus']);total=total*f
  assert irreducible(f)
  ext.context(f);q=E(cert['q_representation']);u=E(cert['u_representation'])
  assert q==E(qrep) and u==E(urep) and peval(RATIO['c'],q)==0
  verify_identity(cert,q,u);ratios+=f.degree();cases+=1
 assert total==mod
 qmods.append(Poly(RATIO['c']).monic())
 assert all(a.gcd(b)==Poly(1) for i,a in enumerate(qmods) for b in qmods[:i])
 qcount=sum(p.degree() for p in qmods)
 assert ratios==77 and qcount==57 and cases==10,(ratios,qcount,cases)
 print('c_zero: primitive algebra isomorphism and all 12 ratio exclusions verified.',flush=True)
 return {'certificate_blocks':cases,'geometric_ratios_excluded':ratios,'distinct_geometric_q_values_excluded':qcount,'coverage':'five full q-divisors on the original ordinary-double-root chart','all_scale_fields':'arbitrary geometric scales; polynomial Bezout identity 1 in every block'}

def main():
 start=time.time();check_hashes();check_input_arithmetic();print('Field phase elapsed',round(time.time()-start,3),flush=True);check_reconstruction()
 rchecks=check_resultant.run_checks();assert rchecks['exact_finite_tests']==200
 print('All 200 fixed-degree Sylvester regression tests passed.',flush=True)
 frob=run_checks();print('Corrected Frobenius/nonreduced-ring tests passed; total elapsed',round(time.time()-start,3),flush=True)
 result=verify_boundaries()
 result.update({'python':platform.python_version(),'numpy':np.__version__,'status':'all retained arithmetic and coverage certificates verified; global ideal not decided','elapsed_seconds':round(time.time()-start,3),'frobenius_checks':{k:v for k,v in frob.items() if k!='elapsed_seconds'}})
 print('VERIFICATION_SUMMARY_JSON='+json.dumps(result,sort_keys=True),flush=True)
if __name__=='__main__':main()
