"""Independent exact substitution of the retained 43 msolve input polynomials.

No basis or reconstructed differential identities are used. Sparse recursive
Horner evaluation is memoized across input equations. No squarefree quotient
or field coercion is used in constructing the target algebra.
"""


# This file was *autogenerated* from the file tests/check_oper_original_input.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_5 = Integer(5); _sage_const_43 = Integer(43); _sage_const_19290 = Integer(19290); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1)
import hashlib, json, time
from pathlib import Path
from functools import lru_cache

source = Path('Research/computations/normalized_oper_msolve.in')
candidate = Path('Research/computations/normalized_oper_a9_parametrization.json')
raw = source.read_bytes()
assert hashlib.sha256(raw).hexdigest() == 'c378d97ee11e2f1e306402a47a90cca586316734df3475d0099d3eabe2253f2a'
names, characteristic, body = raw.decode().split('\n', _sage_const_2 )
assert characteristic == '5'
names = names.split(',')
M = PolynomialRing(GF(_sage_const_5 ), names=names)
equations = [M(s.strip().replace('^', '**')) for s in body.split(',') if s.strip()]
assert len(equations) == _sage_const_43 
data = json.loads(candidate.read_text())
R = PolynomialRing(GF(_sage_const_5 ), 'z', implementation='FLINT'); z = R.gen()
P = R(data['P'])
assert P.is_monic() and P.degree() == _sage_const_19290 
h = [R(data['coordinate_polynomials'][n]) % P for n in names]
assert h[names.index('a9')] == z
started = time.monotonic()

@lru_cache(maxsize=None)
def evaluate(terms):
    if not terms: return R.zero()
    active = [i for i in range(len(names)) if any(e[i] for e,c in terms)]
    if not active: return R(sum(c for e,c in terms))
    # Prefer a9=z (cheap multiplication) last; sparse early partitioning
    # allows repeated lower polynomials to share their modular evaluations.
    i = min(active, key=lambda j: (j == names.index('a9'), len(set(e[j] for e,c in terms))))
    groups = {}
    for e,c in terms:
        exponent = e[i]
        ee = list(e); ee[i] = _sage_const_0 
        groups.setdefault(exponent, []).append((tuple(ee),c))
    result = R.zero(); last = max(groups)
    for exponent in sorted(groups, reverse=True):
        if exponent != last:
            result = (result * power_mod(h[i],last-exponent,P)) % P
        result += evaluate(tuple(sorted(groups[exponent])))
        last = exponent
    if last: result = (result * power_mod(h[i],last,P)) % P
    return result % P

for index, equation in enumerate(equations, _sage_const_1 ):
    terms = tuple(sorted((tuple(e),int(c)) for e,c in equation.dict().items()))
    assert evaluate(terms) == _sage_const_0 , 'nonzero original input equation %d' % index
    print('PASS original input %d/43 elapsed %.2fs cached %d' %
          (index,time.monotonic()-started,evaluate.cache_info().currsize),flush=True)
assert P.gcd(P.derivative()) == _sage_const_1 
result = {'verdict':'PASS', 'date':'2026-09-07',
          'auditor':'/root/normalized_enumeration_certificate_audit',
          'input_sha256':hashlib.sha256(raw).hexdigest(),
          'parametrization_sha256':hashlib.sha256(candidate.read_bytes()).hexdigest(),
          'original_input_equations_verified':len(equations),
          'degree':int(P.degree()),'squarefree':True,'separator_a9_is_z':True,
          'elapsed_seconds':time.monotonic()-started}
Path('Research/computations/normalized_oper_original_input_audit.json').write_text(json.dumps(result,indent=_sage_const_2 )+'\n')
print(json.dumps(result),flush=True)

