#include "ntt.hpp"
#include "resultant.hpp"
F detF(vector<vector<F>>a){int n=a.size();F d(1);for(int j=0;j<n;j++){int k=j;while(k<n&&!a[k][j])k++;if(k==n)return F();if(k!=j){swap(a[k],a[j]);d=-d;}F c=a[j][j];d*=c;F ci=c.inverse();for(int i=j+1;i<n;i++){F m=a[i][j]*ci;for(int k=j+1;k<n;k++)a[i][k]-=m*a[j][k];}}return d;}
F direct_res(F a,F b,F c,F d,F Q,F T0,F lambda){PF U=PF::mon(5)+PF(Q),S=PF({d,c,F(3)*b,F(2)*a}),f=U*U*lambda+U*S+PF(T0),crit({c,b,a});vector<vector<F>>M(12,vector<F>(12));for(int i=0;i<2;i++)for(int j=0;j<=10;j++)M[i][i+j]=f[j];for(int i=0;i<10;i++)for(int j=0;j<=2;j++)M[2+i][i+j]=crit[j];return detF(M);}
PQ mulPQ(const PQ&a,const PQ&b,bool direct){if(direct)return a*b;if(!a||!b)return {};int n=ntt_length(a.deg()+b.deg()+1);vector<QE>x(n),y(n);copy(a.a.begin(),a.a.end(),x.begin());copy(b.a.begin(),b.a.end(),y.begin());dft(x,false);dft(y,false);for(int i=0;i<n;i++)x[i]*=y[i];dft(x,true);x.resize(a.deg()+b.deg()+1);return PQ(x);}
F evalLPF(const LP&p,F x,F y){F r;for(auto[e,c]:p.a){assert(!e[2]&&!e[3]);r+=c*fpow(x,e[0])*fpow(y,e[1]);}return r;}
F evalCLF(const CL&g,F h,F w,F x,F y){F r;for(int j=0;j<3;j++)for(int i=0;i<=g.a[j].deg();i++)r+=evalLPF(g.a[j][i],h,w)*fpow(x,i)*fpow(y,j);return r;}
array<array<PL,3>,3> readE(string path){ifstream in(path);string s;getline(in,s);if(s.find("UNIVERSAL_E_V1")!=0)throw runtime_error("bad E header");array<array<PL,3>,3>E;for(int k=0;k<9;k++){int i,j,d;in>>i>>j>>d;for(int x=0;x<=d;x++)E[i][j].a.push_back(readLP(in));}return E;}
int main(int argc,char**argv){try{F::init();string dir=argc>1?argv[1]:"evidence";bool direct=argc>2&&string(argv[2])=="--direct";mt19937 rng(27092026);
 // Independent 12 by 12 Sylvester determinant regressions, including degree drops.
 for(int k=0;k<96;k++){F a=F::raw(rng()%390625),b=F::raw(rng()%390625),c=F::raw(rng()%390625),d=F::raw(rng()%390625),Q=F::raw(rng()%390625),T0=F::raw(rng()%390625),l=F::raw(rng()%390625);if(k%4==0)a=F();if(k%7==0)b=F();if(k%11==0)c=F();if(k%5==0)l=F();auto R=critical_resultant(a,b,c,d,Q,T0);assert(direct_res(a,b,c,d,Q,T0,l)==R[0]+l*R[1]+l*l*R[2]);}cerr<<"96 fixed-degree resultant regressions passed (including a=0, b=0, lambda=0)\n";
 PF P=coded({11,22,18,5,19,20,15,16,9,22,1}),A=coded({1,21,14,22,13}),Q=coded({0,11,6,21,22,0,15,21,9,4,0,1,1,24,14,0,3,9,8,24}),B=coded({8,14,19,2,10,19,3,24,18,16});PF t=A.exact(PF({-F::raw(25),F(1)})*F::raw(13));auto G=readsource(dir+"/source.txt");auto E=readE(dir+"/universal_E.txt");
 int checked=0;for(int k=2;checked<48;k++){F x=F::raw(k),px=P.eval(x);if(!px||!t.eval(x)||F::lg[px.v]%3)continue;F y=F::raw(F::ex[F::lg[px.v]/3]),w=F::raw(17+31*checked),h=F::raw(2+53*checked),mu=checked%5==0?F():F::raw(71+19*checked);if(checked%3==0){F z0=evalCLF(G[0],F(),w,x,y),z1=evalCLF(G[0],F(1),w,x,y);if(z1!=z0)h=-z0/(z1-z0);}array<F,4>g;for(int i=0;i<4;i++)g[i]=evalCLF(G[i],h,w,x,y);F bb=B.eval(x),qb=(Q.eval(x)-fpow(bb,5))/fpow(y,5),a=F(3)*g[0]/fpow(y,2),b=F(2)*(g[1]-F(3)*bb*g[0])/fpow(y,3),c=(g[2]-F(2)*bb*g[1]+F(3)*bb*bb*g[0])/fpow(y,4),d=(g[3]-bb*g[2]+bb*bb*g[1]-fpow(bb,3)*g[0])/fpow(y,5);F directD=direct_res(a,b,c,d,qb,fpow(t.eval(x),3),w*mu);F evalue,H=h*w,q=fpow(w,3),z=y/w;for(int i=0;i<3;i++)for(int j=0;j<3;j++)for(int xx=0;xx<=E[i][j].deg();xx++)evalue+=evalLPF(E[i][j][xx],H,q)*fpow(x,xx)*fpow(z,j)*fpow(mu,i);assert(directD==fpow(w,-28)*fpow(t.eval(x),5)*evalue);checked++;}cerr<<"48 original-source versus compact-E Sylvester regressions passed\n";
 int identities=0,total=0;for(int rc:{145049,211895,211959}){string line;ifstream sp(dir+"/split_"+to_string(rc)+".txt");getline(sp,line);vector<PF>s;for(int i=0;i<8;i++)s.push_back(readPF(sp));PF rv=s[0],main=s[1],bad=s[2],Hpoly=s[5];assert(rv==main*bad);assert(pgcd(main,bad).deg()==0);assert(main.deg()==452&&bad.deg()==18);assert(pgcd(main,main.deriv()).deg()==0);assert(s[3]==main&&s[4]==PF(F(1)));assert(pgcd(main,s[7]).deg()==0);assert((Hpoly*s[7]+s[6])%main==PF());
 ifstream ep(dir+"/endpoint_"+to_string(rc)+".txt");getline(ep,line);int rr,pc,mc,zc;ep>>rr>>pc>>mc>>zc;vector<LP>ll;for(int i=0;i<8;i++)ll.push_back(readLP(ep));QE::setmod(main);QE v(PF::mon(1)),H(Hpoly),q=QE(F::raw(pc))/qpow(v,3);assert(!evaluateLP(ll[6],H,v));assert(!evaluateLP(ll[7],H,v));QE bb=evaluateLP(ll[1],H,v),bp=evaluateLP(ll[1],H,v*QE(F::raw(zc)));QE a0;int ac[]={89654,311173,214299,163299,315361,33043,356725,245794};for(int i=7;i>=0;i--)a0=a0*q+QE(F::raw(ac[i]));QE psi=a0+q*(QE(F::raw(299833))+QE(F::raw(232505))*q)*H;QE op=H*q*bb*bp*a0*psi*(q-QE(F::raw(15383)))*(q-QE(1));assert(pgcd(op.a,main).deg()==0);
 PF drop_product(F(1));vector<PF>dropmods;for(int j=0;j<2;j++){ifstream in(dir+"/drop_certificate_"+to_string(rc)+"_"+to_string(j)+".txt");getline(in,line);int power;in>>power;assert(power==0);PF m=readPF(in);QE::setmod(m);PQ U=readPQdata(in),V=readPQdata(in),f=evaluate_v(ll[6],QE(PF::mon(1))),g=evaluate_v(ll[7],QE(PF::mon(1)));assert(mulPQ(U,f,direct)+mulPQ(V,g,direct)==PQ(QE(1)));drop_product=drop_product*m;dropmods.push_back(m);}assert(drop_product==bad);assert(pgcd(dropmods[0],dropmods[1]).deg()==0);PF rad12=dropmods[0].exact(pgcd(dropmods[0],dropmods[0].deriv()));assert(rad12.deg()==3&&ppow(rad12,4)==dropmods[0]);assert(pgcd(dropmods[1],dropmods[1].deriv()).deg()==0);cerr<<"endpoint "<<rc<<": degree-drop identities over dimensions 12 and 6 verified, fourth-order nilpotents retained\n";
 ifstream df(dir+"/ddf_"+to_string(rc)+".txt");getline(df,line);int typ,idx=0,sum=0;PF prod(F(1));vector<PF>blocks;while(df>>typ){PF m=readPF(df);prod=prod*m;sum+=m.deg();for(auto n:blocks)assert(pgcd(m,n).deg()==0);blocks.push_back(m);QE::setmod(m);string tag=to_string(rc)+"_"+to_string(idx);ifstream eqf(dir+"/square_equations_"+tag+".txt");getline(eqf,line);assert(readPF(eqf)==m);assert(readPF(eqf)==Hpoly%m);assert(readPF(eqf)==(QE(F::raw(pc))/qpow(QE(PF::mon(1)),3)).a);PQ C71=readPQdata(eqf),C72=readPQdata(eqf);assert(C71.deg()==47&&C72.deg()==47);PF leafprod(F(1));int leaf=0;while(filesystem::exists(dir+"/square_certificate_"+tag+"_"+to_string(leaf)+".txt")){ifstream cf(dir+"/square_certificate_"+tag+"_"+to_string(leaf)+".txt");getline(cf,line);int unit,power;cf>>unit>>power;assert(unit==1&&power==0);PF lm=readPF(cf);leafprod=leafprod*lm;QE::setmod(lm);PQ a,b;for(auto c:C71.a)a.a.push_back(QE(c.a));for(auto c:C72.a)b.a.push_back(QE(c.a));a.trim();b.trim();PQ U=readPQdata(cf),V=readPQdata(cf),g=readPQdata(cf);assert(g==PQ(QE(1)));assert(mulPQ(U,a,direct)+mulPQ(V,b,direct)==g);identities++;leaf++;}assert(leafprod==m);cerr<<"square certificate "<<tag<<": algebra dimension "<<m.deg()<<", C71/C72 degrees 47/47, Bezout identity 1 verified\n";idx++;}assert(prod==main);assert(sum==452);total+=sum;cerr<<"endpoint "<<rc<<": complete ordinary coverage, dimension "<<sum<<"\n";}
 assert(identities==17&&total==1356);cerr<<"AUDIT PASSED: 17 square unit identities, 6 unreduced degree-drop unit identities, ordinary dimension 1356\n";
}catch(exception&e){cerr<<"ERROR "<<e.what()<<"\n";return 1;}}
