#include "io.hpp"
F determinant(vector<vector<F>>a){int n=a.size();F d(1);for(int j=0;j<n;j++){int k=j;while(k<n&&!a[k][j])k++;if(k==n)return F();if(k!=j){swap(a[k],a[j]);d=-d;}F p=a[j][j];d*=p;F pinv=p.inverse();for(int k=j+1;k<n;k++)if(a[k][j]){F m=a[k][j]*pinv;for(int l=j+1;l<n;l++)a[k][l]-=m*a[j][l];}}return d;}
array<F,3> vals(const vector<PF>&f,const vector<PF>&g,F v){vector<F>a(7),b(7);for(int i=0;i<7;i++){a[i]=f[i].eval(v);b[i]=g[i].eval(v);}vector<vector<F>>S(12,vector<F>(12)),T(10,vector<F>(11));for(int i=0;i<6;i++)for(int j=0;j<7;j++){S[i][i+j]=a[j];S[i+6][i+j]=b[j];}for(int i=0;i<5;i++)for(int j=0;j<7;j++){T[i][i+j]=a[j];T[i+5][i+j]=b[j];}array<F,3> r;r[0]=determinant(S);for(int idx=0;idx<2;idx++){vector<vector<F>>U(10,vector<F>(10));for(int i=0;i<10;i++){U[i][0]=T[i][idx];for(int j=1;j<10;j++)U[i][j]=T[i][j+1];}r[idx+1]=determinant(U);}return r;}
vector<PF> toH(const LP&f){vector<PF>a(7);for(auto[e,c]:f.a){assert(e[0]>=0&&e[0]<=6&&e[1]>=0&&e[2]==0&&e[3]==0);a[e[0]]+=PF::mon(e[1],c);}return a;}
PF interpolate(vector<F>y,const vector<F>&x){int n=x.size();for(int d=1;d<n;d++)for(int i=n-1;i>=d;i--)y[i]=(y[i]-y[i-1])/(x[i]-x[i-d]);PF p(y[n-1]);for(int i=n-2;i>=0;i--)p=p*PF({-x[i],F(1)})+PF(y[i]);return p;}
void savePF(ostream&o,const PF&p){o<<p.a.size();for(F c:p.a)o<<" "<<c.v;o<<"\n";}
int main(int argc,char**argv){try{F::init();string dir=argc>1?argv[1]:"evidence";vector<int>rs={145049,211895,211959};if(argc>2)rs={stoi(argv[2])};for(int rc:rs){ifstream in(dir+"/endpoint_"+to_string(rc)+".txt");string line;getline(in,line);getline(in,line);for(int i=0;i<6;i++)readLP(in);LP f=readLP(in),g=readLP(in);auto fa=toH(f),ga=toH(g);int n=1081;vector<F>x;array<vector<F>,3>y;for(int j=0;j<n;j++){F v=F::raw(j);x.push_back(v);auto ys=vals(fa,ga,v);for(int k=0;k<3;k++)y[k].push_back(ys[k]);}array<PF,3>pol;for(int k=0;k<3;k++){pol[k]=interpolate(y[k],x);cerr<<"endpoint "<<rc<<" determinant "<<k<<" degree "<<pol[k].deg()<<"\n";}assert(pol[0]);assert(pol[1].deg()<=900&&pol[2].deg()<=900);for(int i=0;i<32;i++){F v=F::raw(1300+997*i);auto ys=vals(fa,ga,v);for(int k=0;k<3;k++)assert(pol[k].eval(v)==ys[k]);}
 ofstream out(dir+"/elimination_"+to_string(rc)+".txt");out<<"ELIMINATION_V1 resultant s0 s1\n";for(auto p:pol)savePF(out,p);
 PF squarefree=pol[0].exact(pgcd(pol[0],pol[0].deriv()));PF gs=pgcd(pol[0],pol[2]);cerr<<"resultant / gcd(resultant,resultant') degree "<<squarefree.deg()<<"; gcd(resultant,s1) degree "<<gs.deg()<<"\n";
 }}catch(exception&e){cerr<<"ERROR "<<e.what()<<"\n";return 1;}}
