#include "ntt.hpp"
struct Context {string dir,work,tag;int rc;PF modulus;QE H,q;array<array<PL,3>,3>E;};
array<array<PL,3>,3> loadE(string dir){ifstream in(dir+"/universal_E.txt");string header;getline(in,header);if(header.find("UNIVERSAL_E_V1")!=0)throw runtime_error("bad universal E");array<array<PL,3>,3>E;for(int a=0;a<9;a++){int i,j,d;in>>i>>j>>d;for(int k=0;k<=d;k++)E[i][j].a.push_back(readLP(in));}return E;}
void writeBi(string path,const Bi&R){ofstream out(path);out<<"REVERSED_SERIES_V1\n"<<R.a.size()<<"\n";for(auto p:R.a)writePQdata(out,p);}
Bi readBi(string path){ifstream in(path);string h;getline(in,h);if(h!="REVERSED_SERIES_V1")throw runtime_error("bad/missing reversed series "+path);int n;in>>n;Bi R;for(int i=0;i<n;i++)R.a.push_back(readPQdata(in));R.trim();return R;}
Bi generate(Context&ctx){int prec=73;array<Bi,3>A;int ds[3]={46,43,40};auto start=chrono::steady_clock::now();map<pair<int,int>,QE>mon;vector<QE>hp(13);hp[0]=QE(1);for(int i=1;i<13;i++)hp[i]=hp[i-1]*ctx.H;map<int,QE>qp;qp[0]=QE(1);for(int i=1;i<=54;i++)qp[i]=qp[i-1]*ctx.q;QE qi=ctx.q.inverse();for(int i=-1;i>=-6;i--)qp[i]=qp[i+1]*qi;
 for(int i=0;i<3;i++)for(int j=0;j<3;j++)for(auto co:ctx.E[i][j].a)for(auto[e,c]:co.a)if(!mon.count({e[0],e[1]}))mon[{e[0],e[1]}]=hp[e[0]]*qp[e[1]];
 for(int j=0;j<3;j++)A[j].a.resize(ds[j]+1);int dim=ctx.modulus.deg();for(int i=0;i<3;i++)for(int j=0;j<3;j++)for(int x=0;x<=ctx.E[i][j].deg();x++){vector<F>v(dim);for(auto[e,c]:ctx.E[i][j].a[x].a){const auto&m=mon.at({e[0],e[1]}).a.a;for(int k=0;k<(int)m.size();k++)v[k]+=m[k]*c;}A[j].a[ds[j]-x]+=PQ::mon(i,QE(PF(v)));}
 for(auto&a:A)a.trim();cerr<<ctx.tag<<" E specialized, monomial cache "<<mon.size()<<"; elapsed "<<chrono::duration<double>(chrono::steady_clock::now()-start).count()<<"\n";
 vector<F>p=coded({11,22,18,5,19,20,15,16,9,22,1}).a;reverse(p.begin(),p.end());PF Pr(p),Pr2=Pr*Pr;Bi R;
 for(int j=0;j<3;j++){Bi cube=bmul(bmul(A[j],A[j],prec),A[j],prec);if(j==0)R+=bscale(cube.shift(2).trunc(prec),qpow(ctx.q,2));if(j==1)R+=bscale(bconstmul(cube,Pr,prec).shift(1).trunc(prec),ctx.q);if(j==2)R+=bconstmul(cube,Pr2,prec);cerr<<ctx.tag<<" norm cube "<<j<<" elapsed "<<chrono::duration<double>(chrono::steady_clock::now()-start).count()<<"\n";}
 Bi cross=bmul(bmul(A[0],A[1],prec),A[2],prec);R-=bscale(bconstmul(cross,Pr,prec).shift(1).trunc(prec),ctx.q*QE(3));
 // Here R=q^2 reverse(Norm E). Its leading coefficient is the cube
 // of the leading z^2 coefficient of E. This extra q^2 is a unit.
 assert(R[0].deg()==0);QE lc=R[0][0];assert(lc==qpow(A[2][0][0],3));
 F alpha=F::raw(25),eps=F::raw(24)+F::raw(4)*alpha+F::raw(23)*fpow(alpha,3);int codes[]={89654,311173,214299,163299,315361,33043,356725,245794};QE a0;for(int i=7;i>=0;i--)a0=a0*ctx.q+QE(F::raw(codes[i]));QE Psi=a0+ctx.q*(QE(F::raw(299833))+QE(F::raw(232505))*ctx.q)*ctx.H;QE F6=Psi/(ctx.q*QE(fpow(F::raw(299619),2)));QE expected=qpow(ctx.q,27)*qpow(QE(F(3)*fpow(eps,8))*qpow(ctx.H,3)*F6,3);assert(lc==expected);
 R=bscale(R,lc.inverse());assert(R[0]==PQ(QE(1)));assert(mudeg(R)<=6);writeBi(ctx.work+"/R_"+ctx.tag+".txt",R);cerr<<ctx.tag<<" normalized reversed R saved; elapsed "<<chrono::duration<double>(chrono::steady_clock::now()-start).count()<<"\n";return R;
}
array<PQ,2> circuit(Context&ctx,const Bi&R){int prec=73;auto start=chrono::steady_clock::now();Bi R2,R3;string p2=ctx.work+"/R2_"+ctx.tag+".txt",p3=ctx.work+"/R3_"+ctx.tag+".txt";if(filesystem::exists(p2))R2=readBi(p2);else{R2=bmul(R,R,prec);writeBi(p2,R2);}cerr<<ctx.tag<<" R^2 ready elapsed "<<chrono::duration<double>(chrono::steady_clock::now()-start).count()<<"\n";if(filesystem::exists(p3))R3=readBi(p3);else{R3=bmul(R2,R,prec);writeBi(p3,R3);}cerr<<ctx.tag<<" R^3 ready elapsed "<<chrono::duration<double>(chrono::steady_clock::now()-start).count()<<"\n";
 array<PQ,15>B;array<PQ,3>C;for(int j=0;j<15;j++)B[j]=pfrob(R2[j],5);for(int j=0;j<3;j++)C[j]=pfrob(R2[j],25);array<PQ,2>out;
 for(int n:{71,72}){PQ sum;for(int k=0;k<=n/25;k++){PQ inner;for(int j=0;j<=(n-25*k)/5;j++)inner+=R3[n-25*k-5*j]*B[j];sum+=inner*C[k];}out[n-71]=sum;cerr<<ctx.tag<<" C"<<n<<" mu degree "<<sum.deg()<<" elapsed "<<chrono::duration<double>(chrono::steady_clock::now()-start).count()<<"\n";}
 ofstream fo(ctx.dir+"/square_equations_"+ctx.tag+".txt");fo<<"SQUARE_EQUATIONS_V1 C71 C72\n";writePF(fo,ctx.modulus);writePF(fo,ctx.H.a);writePF(fo,ctx.q.a);for(auto p:out)writePQdata(fo,p);return out;
}
struct Bez {PQ g,u,v;};
Bez bezout(PQ a,PQ b){PQ u(QE(1)),uu,v,vv(QE(1));while(b){PF fail=pgcd(b.a.back().a,QE::mod);if(fail.deg()>0)throw fail;auto [q,r]=a.divrem(b);a=b;b=r;PQ t=u-q*uu;u=uu;uu=t;t=v-q*vv;v=vv;vv=t;}if(a){PF fail=pgcd(a.a.back().a,QE::mod);if(fail.deg()>0)throw fail;QE inv=a.a.back().inverse();a=a*inv;u=u*inv;v=v*inv;}return {a,u,v};}
void certify(Context&ctx,const array<PQ,2>&eqs){vector<PF> todo={ctx.modulus};int leaf=0;while(!todo.empty()){PF m=todo.back();todo.pop_back();QE::setmod(m);array<PQ,2>eq;for(int i=0;i<2;i++)for(auto c:eqs[i].a)eq[i].a.push_back(QE(c.a));for(auto&p:eq)p.trim();try{auto z=bezout(eq[0],eq[1]);assert(z.u*eq[0]+z.v*eq[1]==z.g);int n=z.g.deg();bool muonly=n>=0&&z.g[n]==QE(1);for(int i=0;i<n;i++)if(z.g[i])muonly=false;ofstream out(ctx.dir+"/square_certificate_"+ctx.tag+"_"+to_string(leaf)+".txt");out<<"SQUARE_CERTIFICATE_V1 g=U C71+V C72\n"<<muonly<<" "<<n<<"\n";writePF(out,m);writePQdata(out,z.u);writePQdata(out,z.v);writePQdata(out,z.g);cerr<<ctx.tag<<" leaf "<<leaf<<" dimension "<<m.deg()<<" gcd degree "<<n<<" mu-power only "<<muonly<<"; identity verified\n";if(!muonly)throw runtime_error("NONTRIVIAL COMMON SCALE ROOT remains");leaf++;}catch(const PF&factor){auto [a,b]=split_support(m,factor);if(a.deg()==0||b.deg()==0)throw runtime_error("coefficient algebra requires nonreduced pivot handling");todo.push_back(a);todo.push_back(b);cerr<<ctx.tag<<" coefficient-pivot split "<<a.deg()<<" + "<<b.deg()<<"\n";}}
}
int main(int argc,char**argv){try{F::init();if(argc<5)throw runtime_error("usage: square evidence endpoint ddf_block_index mode [work]");Context ctx;ctx.dir=argv[1];ctx.rc=stoi(argv[2]);int idx=stoi(argv[3]);string mode=argv[4];ctx.work=argc>5?argv[5]:"work";filesystem::create_directories(ctx.work);ctx.tag=to_string(ctx.rc)+"_"+to_string(idx);ifstream dd(ctx.dir+"/ddf_"+to_string(ctx.rc)+".txt");string header;getline(dd,header);int d;for(int i=0;i<=idx;i++){dd>>d;ctx.modulus=readPF(dd);}assert(pgcd(ctx.modulus,ctx.modulus.deriv()).deg()==0);QE::setmod(ctx.modulus);ifstream sp(ctx.dir+"/split_"+to_string(ctx.rc)+".txt");getline(sp,header);for(int i=0;i<5;i++)readPF(sp);ctx.H=QE(readPF(sp));PF P=coded({11,22,18,5,19,20,15,16,9,22,1});ctx.q=QE(P.eval(F::raw(ctx.rc)))/qpow(QE(PF::mon(1)),3);cerr<<"START "<<ctx.tag<<" coefficient algebra dimension "<<ctx.modulus.deg()<<" mode "<<mode<<"\n";
 array<PQ,2>eq;if(mode=="verify"||mode=="certify"){ifstream in(ctx.dir+"/square_equations_"+ctx.tag+".txt");getline(in,header);PF m=readPF(in);assert(m==ctx.modulus);assert(readPF(in)==ctx.H.a);assert(readPF(in)==ctx.q.a);for(auto&p:eq)p=readPQdata(in);certify(ctx,eq);}else{Bi R;if(mode=="circuit"||filesystem::exists(ctx.work+"/R_"+ctx.tag+".txt"))R=readBi(ctx.work+"/R_"+ctx.tag+".txt");else{ctx.E=loadE(ctx.dir);R=generate(ctx);}if(mode!="norm"){eq=circuit(ctx,R);certify(ctx,eq);}}cerr<<"COMPLETE "<<ctx.tag<<"\n";
}catch(exception&e){cerr<<"ERROR "<<e.what()<<"\n";return 1;}}
