import Mathlib.Algebra.Algebra.Subalgebra.Lattice
import Mathlib.Data.Fintype.Card
import Mathlib.Tactic

namespace Litt3.Atlases

variable {K ι : Type*} [Field K] [Fintype K] [Fintype ι]

/-- A product with more coordinates than field elements cannot be
generated by one element. This includes F_q^(q+1), with no coordinate census. -/
theorem finite_field_product_not_monogenic (hcard : Fintype.card K < Fintype.card ι)
    (a : ι → K) : Algebra.adjoin K ({a} : Set (ι → K)) ≠ ⊤ := by
  classical
  have hnon : ¬Function.Injective a := fun hi =>
    (Nat.not_le_of_lt hcard) (Fintype.card_le_of_injective a hi)
  obtain ⟨i, j, heq, hne⟩ := Function.not_injective_iff.mp hnon
  let S : Subalgebra K (ι → K) :=
    { carrier := {x | x i = x j}
      zero_mem' := rfl
      one_mem' := rfl
      add_mem' := by
        intro x y hx hy
        change x i + y i = x j + y j
        rw [hx, hy]
      mul_mem' := by
        intro x y hx hy
        change x i * y i = x j * y j
        rw [hx, hy]
      algebraMap_mem' := fun _ => rfl }
  have hS : Algebra.adjoin K ({a} : Set (ι → K)) ≤ S :=
    Algebra.adjoin_le (by intro x hx; simpa only [Set.mem_singleton_iff.mp hx] using heq)
  intro ht
  rw [ht] at hS
  have htest : (Pi.single i (1 : K) : ι → K) ∈ S := hS trivial
  change (Pi.single i (1 : K) : ι → K) i = (Pi.single i (1 : K) : ι → K) j at htest
  have hj : j ≠ i := Ne.symm hne
  exact one_ne_zero (by simpa only [Pi.single_eq_same, Pi.single_eq_of_ne hj] using htest)

end Litt3.Atlases
