import Solutions.Atlases.StableSpanCertificates
import Mathlib.Algebra.MvPolynomial.Basic
import Mathlib.Algebra.MvPolynomial.CommRing
import Mathlib.RingTheory.Ideal.Quotient.Operations

namespace Litt3.Atlases

variable {K σ ι : Type*} [Field K] [Fintype ι]

/-- The original polynomial quotient is generated by its actual variable
images, without assuming a completed border table or a presented algebra. -/
theorem quotient_variables_generate (I : Ideal (MvPolynomial σ K)) :
    Algebra.adjoin K (Set.range (fun i : σ =>
      Ideal.Quotient.mkₐ K I (MvPolynomial.X i))) = ⊤ := by
  change Algebra.adjoin K (Set.range ((Ideal.Quotient.mkₐ K I) ∘
    (MvPolynomial.X : σ → MvPolynomial σ K))) = ⊤
  rw [Set.range_comp, ← AlgHom.map_adjoin, MvPolynomial.adjoin_range_X,
    Algebra.map_top]
  exact (AlgHom.range_eq_top _).mpr (Ideal.Quotient.mkₐ_surjective K I)

theorem polynomial_quotient_border_basis_certificate
    (I : Ideal (MvPolynomial σ K)) (b : ι → MvPolynomial σ K ⧸ I)
    (h1 : (1 : MvPolynomial σ K ⧸ I) ∈ Submodule.span K (Set.range b))
    (stable : ∀ i : σ, ∀ x ∈ Submodule.span K (Set.range b),
      Ideal.Quotient.mkₐ K I (MvPolynomial.X i) * x ∈ Submodule.span K (Set.range b))
    (hcard : Fintype.card ι ≤ Module.finrank K (MvPolynomial σ K ⧸ I)) :
    Submodule.span K (Set.range b) = ⊤ ∧
      Fintype.card ι = Module.finrank K (MvPolynomial σ K ⧸ I) ∧ LinearIndependent K b := by
  apply stable_generator_span_basis_certificate b
    (Set.range (fun i : σ => Ideal.Quotient.mkₐ K I (MvPolynomial.X i)))
    (quotient_variables_generate I) h1 ?_ hcard
  rintro _ ⟨i, rfl⟩
  exact stable i

end Litt3.Atlases
