import Definitions.Deformations.RankOneQuadraticRemainder
import Definitions.Deformations.SplitQuadraticAlgebra
import Mathlib.LinearAlgebra.Dimension.Finrank

namespace Litt3.Deformations.Specifications

variable (K : Type*) [Field K]

/-- The literal relative split rank-one length statement, retaining
the actual ideal generated by y³, yz, z² and both original truncation powers.
The geometric formal splitting theorem is a separate obligation. -/
def RankOneQuadraticTruncationLength (Q T : ℕ) : Prop :=
  ∀ g : TruncatedMonomialAlgebra K (Fin 2) ![Q, T],
    g ∈ rankOneQuadraticRemainderIdeal K Q T →
      Module.finrank K ((Polynomial (TruncatedMonomialAlgebra K (Fin 2) ![Q, T])) ⧸
        Ideal.span ({splitQuadraticPolynomial g, Polynomial.X ^ Q} :
          Set (Polynomial (TruncatedMonomialAlgebra K (Fin 2) ![Q, T])))) = 2 * Q * T

end Litt3.Deformations.Specifications
