#!/usr/bin/env python3
"""Verify retained SHA-256 hashes. Extra generated bytecode does not matter."""
from pathlib import Path
import hashlib

ROOT=Path(__file__).resolve().parents[1]
def main():
    entries=(ROOT/'SHA256SUMS').read_text().splitlines()
    checked=0
    for line in entries:
        if not line.strip():continue
        expected,name=line.split('  ',1)
        path=ROOT/name
        if not path.is_file():raise SystemExit(f'MISSING: {name}')
        h=hashlib.sha256()
        with path.open('rb') as stream:
            for chunk in iter(lambda:stream.read(1024*1024),b''):h.update(chunk)
        if h.hexdigest()!=expected:raise SystemExit(f'HASH MISMATCH: {name}')
        checked+=1
    print(f'PASS SHA-256 manifest: {checked} retained files.')
if __name__=='__main__':main()
