"""Generate exact data for the COMPLETE mixed-phase endpoint certificate.

The only inputs are inputs/data.json and the retained finite-field layer.
No large table or external data is required. All polynomial rows ascend.
"""
import argparse
import hashlib
import json
from pathlib import Path
from exact import F, Extension, evaluate, determinant

ROOT = Path(__file__).resolve().parent.parent


def cpp_array(name, values, ctype='int'):
    dims = []
    cursor = values
    while isinstance(cursor, (list, tuple)):
        dims.append(len(cursor))
        cursor = cursor[0] if cursor else None
    def render(value):
        if isinstance(value, (list, tuple)):
            return '{' + ','.join(render(v) for v in value) + '}'
        return str(value)
    return f'const {ctype} {name}' + ''.join(f'[{n}]' for n in dims) + '=' + render(values) + ';\n'


def make_data():
    raw = (ROOT / 'inputs/data.json').read_bytes()
    data = json.loads(raw)
    E = Extension(data['A_monic'])
    K = Extension(data['zeta_minimal_over_F25'])
    alpha = E.element([0, 1])
    roots = [E.pow(alpha, 25**i) for i in range(4)]
    zeta = K.element([0, 1])
    phases = [K.pow(zeta, j) for j in range(29)]
    assert K.pow(zeta, 29) == K.one and zeta != K.one
    encode = lambda a: sum(c * 25**i for i, c in enumerate(a))
    values = {}
    components = {}
    for name, key in [('c', 'c_row'), ('e', 'e_row'),
                      ('f0', 'f0_row'), ('f1', 'f1_row')]:
        row = [E.embed(c) for c in data[key]]
        values[name] = [evaluate(row, a, E) for a in roots]
        components[name] = []
        for ell in range(4):
            part = E.zero
            for r in range(4):
                weight = pow(2, (-ell * r) % 4, 5)
                part = E.add(part, E.mul(E.integer(weight), values[name][r]))
            # 1/4=4 in F5. These are genuine, normalized projections.
            components[name].append(E.mul(E.integer(4), part))
    assert all(x != E.zero for x in components['f0'][1:])
    assert components['f1'][3] == E.zero
    assert all(x != E.zero for x in components['f1'][1:3])
    basis = [E.one] + components['f0'][1:]
    assert determinant([[basis[j][i] for j in range(4)] for i in range(4)]) != 0
    trace = {}
    for name in values:
        ss = E.zero
        for x in values[name]:
            ss = E.add(ss, x)
        normalized = E.div(ss, E.embed(data['eta0']))
        assert all(c == 0 for c in normalized[1:])
        trace[name] = normalized[0]
    assert trace['c'] == 17 and trace['e'] == 1
    assert F.pow(17, 5) == 10 and F.pow(17, 5) != 17
    text = ('// Generated by mixed_phase_data.py from the exact retained inputs.\n'
            '#pragma once\n')
    for name, value in [
        ('add25', [[F.add(a, b) for b in range(25)] for a in range(25)]),
        ('mul25', [[F.mul(a, b) for b in range(25)] for a in range(25)]),
        ('neg25', [F.neg(a) for a in range(25)]),
        ('inv25', [0] + [F.inv(a) for a in range(1, 25)]),
        ('phase', phases), ('Amonic', data['A_monic']),
        ('f0_values', [encode(x) for x in values['f0']]),
        ('f1_values', [encode(x) for x in values['f1']]),
        ('c_values', [encode(x) for x in values['c']]),
        ('e_values', [encode(x) for x in values['e']]),
    ]:
        text += cpp_array(name, value)
    evidence = {
        'input_sha256': hashlib.sha256(raw).hexdigest(),
        'field8_encoding': 'sum of four F25 coefficient codes times 25**i',
        'normalized_root_character_components': {
            key: [list(x) for x in row] for key, row in components.items()},
        'root_values': {key: [list(x) for x in row] for key, row in values.items()},
        'root_trace_divided_by_eta0': trace,
        'c_trace_bar': F.pow(17, 5),
        'nonzero_trace_difference': F.sub(17, F.pow(17, 5)),
        'phase_vectors_F25': [list(x) for x in phases],
        'status': 'exact data identities verified; not a standalone geometric decision'
    }
    return text, evidence


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--output', type=Path, required=True)
    parser.add_argument('--output-json', type=Path, required=True)
    args = parser.parse_args()
    text, evidence = make_data()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output_json.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(text)
    args.output_json.write_text(json.dumps(evidence, indent=2, sort_keys=True) + '\n')
    print('PASS: root characters, phase data, normalized traces 17 and 1, and 17^5=10.')


if __name__ == '__main__':
    main()
