#include "source.hpp"
#include <chrono>
constexpr int NH=13,NQ=61,NX=47;
using Grid=std::vector<F>;
inline size_t id(int j,int k,int x,int h,int q){return ((((j*3+k)*NX+x)*NH+h)*NQ+q);}
inline std::vector<Poly> lagrange(const std::vector<F>&nodes){std::vector<Poly>r;for(int i=0;i<(int)nodes.size();i++){Poly p(1);F d=1;for(int j=0;j<(int)nodes.size();j++)if(i!=j){p=p*Poly(std::vector<F>{ff::neg(nodes[j]),1});d=ff::mul(d,ff::sub(nodes[i],nodes[j]));}r.push_back(scale(p,ff::inv(d)));}return r;}
inline std::array<std::array<Poly,3>,3> Enumeric(const std::vector<Source>&basis,F H,F w){F q=ff::pow(w,3);auto ch=chart(basis,ff::div(H,w),w);auto d=compactD(ch.s);std::array<std::array<Poly,3>,3>E;for(int j=0;j<3;j++)for(int k=0;k<3;k++)E[j][k]=scale(d[k].a[j],ff::mul(ff::pow(q,16),ff::pow(w,j-2+k)));return E;}
inline Grid readE(const std::string&path){std::ifstream in(path);std::string magic;in>>magic;if(magic!="CONSTANT140_E_V1")throw std::runtime_error("E header");Grid a(9*NX*NH*NQ);int j,k,x,h,q,c;while(in>>j>>h>>q>>k>>x>>c){if(j<0||j>2||h<0||h>=NH||q<0||q>=NQ||k<0||k>2||x<0||x>=NX||c<=0||c>=ff::N)throw std::runtime_error("E malformed record");if(a[id(j,k,x,h,q)])throw std::runtime_error("duplicate E record");a[id(j,k,x,h,q)]=c;}return a;}
inline std::array<std::array<Poly,3>,3> evaluateE(const Grid&a,F H,F q){std::array<std::array<Poly,3>,3>out;for(int j=0;j<3;j++)for(int k=0;k<3;k++){std::vector<F>co(NX);for(int x=0;x<NX;x++){F v=0;for(int h=NH-1;h>=0;h--){F z=0;for(int l=NQ-1;l>=0;l--)z=ff::add(ff::mul(z,q),a[id(j,k,x,h,l)]);v=ff::add(ff::mul(v,H),z);}co[x]=v;}out[j][k]=Poly(co);}return out;}
int main(int argc,char**argv){try{ff::init();init_source();std::string mode=argc>1?argv[1]:"build",ap=argc>2?argv[2]:"inputs/source_affine.dat",ep=argc>3?argv[3]:"inputs/E_records.tsv";auto basis=read_affine(ap);if(mode=="build"){
 std::vector<F>hs,qs,ws;for(int i=1;i<=NH;i++)hs.push_back(i);for(int i=1;i<=NQ;i++){F w=ff::pow(alpha,i);ws.push_back(w);qs.push_back(ff::pow(w,3));}auto lh=lagrange(hs),lq=lagrange(qs);Grid vals(9*NX*NH*NQ);std::cout<<"grid "<<NH<<" "<<NQ<<"\n";
 for(int qi=0;qi<NQ;qi++){for(int hi=0;hi<NH;hi++){auto E=Enumeric(basis,hs[hi],ws[qi]);for(int j=0;j<3;j++)for(int k=0;k<3;k++){if(E[j][k].deg()>46-3*j)throw std::runtime_error("x bound exceeded");for(int x=0;x<NX;x++)vals[id(j,k,x,hi,qi)]=E[j][k].at(x);}}if(qi%10==0)std::cout<<"grid_q_completed "<<qi+1<<std::endl;}
 Grid stage(vals.size()),co(vals.size());for(int j=0;j<3;j++)for(int k=0;k<3;k++)for(int x=0;x<NX;x++)for(int q=0;q<NQ;q++)for(int h=0;h<NH;h++)for(int hi=0;hi<NH;hi++)stage[id(j,k,x,h,q)]=ff::add(stage[id(j,k,x,h,q)],ff::mul(lh[hi].at(h),vals[id(j,k,x,hi,q)]));
 for(int j=0;j<3;j++)for(int k=0;k<3;k++)for(int x=0;x<NX;x++)for(int h=0;h<NH;h++)for(int q=0;q<NQ;q++)for(int qi=0;qi<NQ;qi++)co[id(j,k,x,h,q)]=ff::add(co[id(j,k,x,h,q)],ff::mul(lq[qi].at(q),stage[id(j,k,x,h,qi)]));
 std::ofstream out(ep);out<<"CONSTANT140_E_V1\n";int total=0;std::array<int,3>counts{};for(int j=0;j<3;j++)for(int h=0;h<NH;h++)for(int q=0;q<NQ;q++)for(int k=0;k<3;k++)for(int x=0;x<NX;x++)if(F c=co[id(j,k,x,h,q)]){out<<j<<' '<<h<<' '<<q<<' '<<k<<' '<<x<<' '<<c<<'\n';total++;counts[j]++;}out.close();std::cout<<"E_records "<<total<<" by_component "<<counts[0]<<" "<<counts[1]<<" "<<counts[2]<<"\n";if(total!=89481)throw std::runtime_error("record count differs from supplied 89481");
 }
 Grid E=readE(ep);int passed=0;F zz=ff::pow(alpha,ff::ORD/3);for(F H:{1,18,50,400,625})for(F w:{2,5,25,172,626}){F q=ff::pow(w,3);auto direct=Enumeric(basis,H,w),got=evaluateE(E,H,q),conjug=Enumeric(basis,H,ff::mul(w,zz));if(direct!=got)throw std::runtime_error("off-grid E evaluation mismatch");if(direct!=conjug)throw std::runtime_error("cube root invariance mismatch");for(F mu:{1,5,51}){std::array<Poly,3>es;for(int j=0;j<3;j++)es[j]=got[j][0]+scale(got[j][1],mu)+scale(got[j][2],ff::mul(mu,mu));Poly W=scale(ppow(es[0],3),ff::mul(q,q))+scale(P*ppow(es[1],3),q)+P*P*ppow(es[2],3)-scale(P*es[0]*es[1]*es[2],ff::mul(3,q));auto ch=chart(basis,ff::div(H,w),w);Poly R=residual(compactD(ch.s),ff::mul(w,mu));if(!(W==scale(R,ff::pow(q,48))))throw std::runtime_error("norm identity mismatch");passed++;}}
 std::cout<<"off_grid_E_checks 25 cube_root_checks 25 norm_checks "<<passed<<" PASS\n";
 }catch(const std::exception&e){std::cerr<<"ERROR "<<e.what()<<"\n";return 1;}return 0;}
