#include "source.hpp"
constexpr int NNQ=109,NNS=13,NNX=47;
inline size_t tt(int j,int mu,int x,int s,int q){return ((((j*3+mu)*NNX+x)*NNS+s)*NNQ+q);}
inline int choose5(int n,int k){int v=1;for(int i=1;i<=k;i++)v=v*(n-i+1)/i;return v%5;}
std::vector<F> square_errors(const Poly&R){if(R.deg()!=140)throw std::runtime_error("square_errors requires degree140");Poly ah;ah.v.resize(141);for(int i=0;i<=140;i++)ah.v[i]=R.at(140-i);Poly a2=trunc(ah*ah,125),a3=trunc(a2*ah,125);Poly C=trunc(trunc(a3*frob(a2),125)*frob(a2,25),125);Poly B=trunc(C,71),late=B*B-scale(ah,ff::pow(ah.at(0),125));std::vector<F>out;for(int m=71;m<=124;m++)out.push_back(C.at(m));for(int m=125;m<=140;m++)out.push_back(late.at(m));if(out.size()!=70)throw std::runtime_error("square error count");return out;}
int main(int argc,char**argv){try{ff::init();init_source();std::string inpath=argc>1?argv[1]:"inputs/E_records.tsv",outpath=argc>2?argv[2]:"regenerated/T_records.tsv",ap=argc>3?argv[3]:"inputs/source_affine.dat";auto basis=read_affine(ap);Poly aa=scale(a0poly(),2),bb=scale(Poly(std::vector<F>{0,299833,232505}),3); // -2 a1
std::array<std::array<Poly,13>,13> factors;for(int h=0;h<=12;h++)for(int s=0;s<=12-h;s++)factors[h][s]=scale(ppow(aa,h)*ppow(bb,12-h-s),choose5(12-h,s));
std::vector<F>T(9*NNX*NNS*NNQ);std::ifstream in(inpath);std::string magic;in>>magic;if(magic!="CONSTANT140_E_V1")throw std::runtime_error("bad E header");int j,h,n,mu,x,c;while(in>>j>>h>>n>>mu>>x>>c)for(int s=0;s<=12-h;s++){const Poly&f=factors[h][s];for(int q=0;q<=f.deg();q++)if(F v=f.at(q)){if(n+q>=NNQ)throw std::runtime_error("T q degree bound exceeded");auto ix=tt(j,mu,x,s,n+q);T[ix]=ff::add(T[ix],ff::mul(c,v));}}
std::ofstream out(outpath);if(!out)throw std::runtime_error("cannot write output");out<<"CONSTANT140_T_V1\n";int count=0;std::array<int,3>counts{};for(int j=0;j<3;j++)for(int s=0;s<NNS;s++)for(int q=0;q<NNQ;q++)for(int m=0;m<3;m++)for(int x=0;x<NNX;x++)if(F v=T[tt(j,m,x,s,q)]){out<<j<<' '<<s<<' '<<q<<' '<<m<<' '<<x<<' '<<v<<'\n';count++;counts[j]++;}out.close();std::cout<<"T_records "<<count<<" by_component "<<counts[0]<<' '<<counts[1]<<' '<<counts[2]<<"\n";
// Exact coefficient-array identity, with q and s both symbolic.
F lc=ff::div(ff::mul(4,ff::pow(epsilon,8)),ff::pow(299619,2));
std::array<Poly,13> leading;
for(int k=0;k<=8;k++)leading[k+1]=scale(shift(ppow(a0poly(),4)*ppow(bb,8-k),14),ff::mul(lc,choose5(8,k)));
for(int m=0;m<3;m++)for(int s=0;s<NNS;s++)for(int q=0;q<NNQ;q++)if(T[tt(2,m,40,s,q)]!=(m==0?leading[s].at(q):0))throw std::runtime_error("symbolic T2 leading identity mismatch");
std::cout<<"global_T2_leading_identity PASS\n";
int cases=0;for(F w:{2,5,25,172})for(F s:{1,2,5,26,625})for(F muv:{1,5}){F q=ff::pow(w,3),a0=eval(a0poly(),q),d=ff::sub(s,ff::mul(2,a1eval(q)));if(!d||!s||!a0||q==1||q==15383)continue;F H=ff::div(ff::mul(2,a0),d);if(!allowed(H,q,muv))throw std::runtime_error("open set mismatch");if(psieval(H,q)!=ff::div(ff::mul(a0,s),d))throw std::runtime_error("Psi change mismatch");std::array<Poly,3>tv;for(int j=0;j<3;j++){std::vector<F>cs(NNX);for(int x=0;x<NNX;x++){F r=0;for(int m=2;m>=0;m--){F v=0;for(int u=NNS-1;u>=0;u--){F z=0;for(int n=NNQ-1;n>=0;n--)z=ff::add(ff::mul(z,q),T[tt(j,m,x,u,n)]);v=ff::add(ff::mul(v,s),z);}r=ff::add(ff::mul(r,muv),v);}cs[x]=r;}tv[j]=Poly(cs);}Poly V=scale(scale(ppow(tv[0],3),ff::mul(q,q))+scale(P*ppow(tv[1],3),q)+P*P*ppow(tv[2],3)-scale(P*tv[0]*tv[1]*tv[2],ff::mul(3,q)),s);auto ch=chart(basis,ff::div(H,w),w);Poly R=residual(compactD(ch.s),ff::mul(w,muv));F scalar=ff::mul(s,ff::mul(ff::pow(d,36),ff::pow(q,48)));if(!(V==scale(R,scalar)))throw std::runtime_error("full transformed norm mismatch");F ell=ff::mul(ff::div(ff::mul(2,ff::pow(epsilon,12)),ff::pow(299619,3)),ff::mul(ff::pow(q,21),ff::mul(ff::pow(a0,6),ff::mul(ff::pow(s,2),ff::pow(d,12)))));if(V.deg()!=140||V.v.back()!=ff::mul(ell,ell))throw std::runtime_error("square leading coefficient mismatch");auto er=square_errors(R),ev=square_errors(V);for(int i=0;i<70;i++)if(ev[i]!=ff::mul(er[i],ff::pow(scalar,i<54?63:126)))throw std::runtime_error("70 equation rescaling mismatch");cases++;}
// A positive fixture is synthetic and is NOT from the requested family.
Poly J=Poly::mon(70,alpha)+Poly::mon(16,7)+Poly::mon(3,alpha)+Poly(3);auto good=square_errors(J*J);for(F v:good)if(v)throw std::runtime_error("synthetic square fixture failed");
// x^140+1 passes all 54 early conditions, but fails the final condition.
auto late=square_errors(Poly::mon(140)+Poly(1));for(int i=0;i<69;i++)if(late[i])throw std::runtime_error("late-only fixture unexpected early failure");if(late[69]!=4)throw std::runtime_error("late-only fixture failed to detect nonsquare");
std::cout<<"transformed_full_norm_checks "<<cases<<" square_leading_checks "<<cases<<" all70_rescaling_checks "<<cases<<"\nsynthetic_square_fixture PASS\nlate_only_nonsquare_fixture PASS\n";
}catch(const std::exception&e){std::cerr<<"ERROR "<<e.what()<<"\n";return 1;}return 0;}
