#!/usr/bin/env python3
"""Verify the complete companion unit certificate, or compare regenerated projections."""
from __future__ import annotations
import argparse, array, hashlib, json, pathlib, struct, subprocess, sys
ROOT=pathlib.Path(__file__).resolve().parent.parent

def run(cmd):
    print('EXECUTE '+' '.join(map(str,cmd)),flush=True)
    subprocess.run(list(map(str,cmd)),cwd=ROOT,check=True)

def rows():
    with (ROOT/'data/global_unit_certificate.bin').open('rb') as f:
        assert f.read(8)==b'CMP140C1' and struct.unpack('<II',f.read(8))==(1,5)
        out=[]
        for _ in range(5):
            n=struct.unpack('<Q',f.read(8))[0];assert 0<n<3000000
            a=array.array('I');assert a.itemsize==4;a.fromfile(f,n)
            if sys.byteorder!='little':a.byteswap()
            assert a[-1] and all(x<390625 for x in a);out.append(a)
        assert not f.read(1)
    return out

def main():
    ap=argparse.ArgumentParser(description=__doc__)
    group=ap.add_mutually_exclusive_group()
    group.add_argument('--certificate',action='store_true')
    group.add_argument('--compare-projection',type=pathlib.Path)
    group.add_argument('--compare-gcd',type=pathlib.Path)
    args=ap.parse_args()
    from verify import manifest
    manifest()
    meta=json.loads((ROOT/'data/global_unit_certificate.json').read_text())
    with (ROOT/'data/global_unit_certificate.bin').open('rb') as f:
        assert hashlib.file_digest(f,'sha256').hexdigest()==meta['certificate_sha256']
    if args.compare_projection or args.compare_gcd:
        p=args.compare_projection or args.compare_gcd
        z=json.loads(p.read_text());r=rows()
        keys=[('P12',0),('P13',1)] if args.compare_projection else [('U',2),('V',3),('G',4)]
        for key,index in keys:
            assert len(z[key])==len(r[index]) and all(a==b for a,b in zip(z[key],r[index])),key
        print('Regenerated polynomial rows agree exactly with the archived global certificate: PASS',flush=True)
        return
    from verify import identities
    from verify_boundary import run as leading,run_norm,run_opposites
    identities();leading();run_norm();run_opposites()
    run([sys.executable,'src/verify_projection_duals.py'])
    (ROOT/'work').mkdir(exist_ok=True)
    run(['g++','-std=c++20','-O3','-fopenmp','-DBOOST_BIND_GLOBAL_PLACEHOLDERS',
         'src/native/verify_global_certificate.cpp','-lgmp','-o','work/verify_global_certificate'])
    run([ROOT/'work/verify_global_certificate',ROOT])
    print('COMPLETE COMPANION UNIT CERTIFICATE: PASS. All stored boundary and global identities verified.',flush=True)
    print('The source-to-projection computation is regenerated by the separate stages in README.md.',flush=True)

if __name__=='__main__':main()
