import Mathlib.RingTheory.DedekindDomain.Different
import Mathlib.RingTheory.Localization.Module

namespace Litt3.QuotientGeometry

/-- A genuine integral power basis generates the entire fraction field
after localizing its coefficients. -/
theorem integral_power_basis_fraction_field_generation
    {A K B L : Type*} [CommRing A] [Field K] [CommRing B] [Field L]
    [IsDomain A] [Algebra A K] [IsFractionRing A K]
    [Algebra A B] [Algebra B L] [Algebra K L] [Algebra A L]
    [IsScalarTower A K L] [IsScalarTower A B L]
    [IsIntegralClosure B A L] [Algebra.IsAlgebraic K L]
    (pb : PowerBasis A B) :
    Algebra.adjoin K {algebraMap B L pb.gen} = ⊤ := by
  letI := IsIntegralClosure.isLocalization A K L B
  let pbl : PowerBasis K L :=
    { gen := algebraMap B L pb.gen
      dim := pb.dim
      basis := pb.basis.localizationLocalization K (nonZeroDivisors A) L
      basis_eq_pow := fun j => by
        rw [Module.Basis.localizationLocalization_apply, pb.basis_eq_pow, map_pow] }
  exact pbl.adjoin_gen_eq_top

/-- The genuine trace-defined different ideal is generated by the
actual minimal-polynomial derivative when the integral ring has a
power basis. Field generation and conductor one are consequences. -/
theorem integral_power_basis_different_ideal
    {A K B L : Type*} [CommRing A] [Field K] [CommRing B] [Field L]
    [IsDomain A] [IsIntegrallyClosed A] [Algebra A K] [IsFractionRing A K]
    [Algebra A B] [Algebra B L] [Algebra K L] [Algebra A L]
    [IsScalarTower A K L] [IsScalarTower A B L]
    [IsDedekindDomain B] [NoZeroSMulDivisors A B]
    [FiniteDimensional K L] [Algebra.IsSeparable K L] [IsIntegralClosure B A L]
    (pb : PowerBasis A B) :
    differentIdeal A B = Ideal.span {Polynomial.aeval pb.gen
      (Polynomial.derivative (minpoly A pb.gen))} := by
  have hgen := integral_power_basis_fraction_field_generation (K := K) (L := L) pb
  have hd := conductor_mul_differentIdeal A K L pb.gen hgen
  rwa [conductor_eq_top_of_powerBasis pb, ← Ideal.one_eq_top, one_mul] at hd

end Litt3.QuotientGeometry
