#include "cubic_field.hpp"
static std::vector<E>cof;
E rc(int t,int m,int h){return cof[(t*7+m)*37+h];}
std::vector<std::vector<F>> lagrange(const std::vector<F>&nodes){Poly p{1};for(F z:nodes)p=p*Poly{FF::neg(z),1};auto dp=derivative(p);std::vector<std::vector<F>>M(nodes.size(),std::vector<F>(nodes.size()));for(int i=0;i<int(nodes.size());i++){Poly a=scale(exactdiv(p,Poly{FF::neg(nodes[i]),1}),FF::inv(eval(dp,nodes[i])));for(int j=0;j<int(nodes.size());j++)M[j][i]=a.coef(j);}return M;}
std::vector<E> amul(const std::vector<E>&a,const std::vector<E>&b,int cut){std::vector<E>c(cut);for(int i=0;i<int(a.size())&&i<cut;i++)for(int j=0;j<int(b.size())&&i+j<cut;j++)c[i+j]=c[i+j]+a[i]*b[j];return c;}
std::vector<E> source_series(E h,E l,int cut){std::vector<E>a(cut);for(int t=0;t<cut;t++){E z;for(int m=6;m>=0;m--){E v;for(int i=36;i>=0;i--)v=v*h+rc(t,m,i);z=z*l+v;}a[t]=z;}return a;}
std::vector<E> square_series(const std::vector<E>&a){int cut=a.size();std::vector<E>b(cut);b[0]=E(1);E iv=EF::inv(a[0]);for(int t=1;t<cut;t++){E sum;for(int j=1;2*j<t;j++)sum=sum+b[j]*b[t-j];sum=EF::scale(sum,2);if(t%2==0)sum=sum+b[t/2]*b[t/2];b[t]=EF::scale(a[t]*iv-sum,3);}E sc=EF::pow(a[0],63);for(auto&v:b)v=v*sc;return b;}
int main(int argc,char**argv){try{if(argc!=3)throw std::runtime_error("usage: cubic_tails factor-index input-output-directory");EF::init(std::stoi(argv[1]));std::string dir=argv[2];constexpr int first=71,last=73,cut=74,NE=3,INF=100000;cof.resize(141*7*37);std::ifstream in(dir+"/input.bin",std::ios::binary);in.read((char*)cof.data(),cof.size()*sizeof(E));if(!in||in.peek()!=EOF)throw std::runtime_error("input binary size");auto conv=[&](const std::vector<int>&a,const std::vector<int>&b,bool low){std::vector<int>c(cut,low?INF:-INF);for(int i=0;i<cut;i++)for(int j=0;i+j<cut;j++)if(abs(a[i])<INF&&abs(b[j])<INF)c[i+j]=low?std::min(c[i+j],a[i]+b[j]):std::max(c[i+j],a[i]+b[j]);return c;};std::array<std::vector<int>,3>b1,b2,b3;for(int k=0;k<3;k++)b1[k].assign(cut,k==0?INF:-INF);for(int t=0;t<cut;t++)for(int m=0;m<7;m++)for(int h=0;h<37;h++)if(rc(t,m,h)){b1[0][t]=std::min(b1[0][t],h);b1[1][t]=std::max(b1[1][t],h);b1[2][t]=std::max(b1[2][t],m);}for(int k=0;k<3;k++){b2[k]=conv(b1[k],b1[k],k==0);b3[k]=conv(b1[k],b2[k],k==0);}std::array<int,NE>v,dh,dl;int NH=0,NL=0;for(int e=0;e<NE;e++){int t=first+e;std::array<int,3>b{INF,-INF,-INF};for(int j=0;5*j<=t;j++)for(int k=0;5*j+25*k<=t;k++){int i=t-5*j-25*k;for(int z=0;z<3;z++)if(abs(b3[z][i])<INF&&abs(b2[z][j])<INF&&abs(b2[z][k])<INF){int a=b3[z][i]+5*b2[z][j]+25*b2[z][k];b[z]=z==0?std::min(b[z],a):std::max(b[z],a);}}v[e]=b[0];dh[e]=b[1]-b[0];dl[e]=b[2];NH=std::max(NH,dh[e]+1);NL=std::max(NL,dl[e]+1);std::cout<<"tail="<<t<<"; divide H^"<<v[e]<<"; (H,mu) degrees <=("<<dh[e]<<","<<dl[e]<<")\n";}
std::vector<F>hn(NH),ln(NL);std::iota(hn.begin(),hn.end(),1);std::iota(ln.begin(),ln.end(),0);auto LH=lagrange(hn),LL=lagrange(ln);auto ix=[&](int e,int h,int l){return (size_t(e)*NH+h)*NL+l;};std::vector<E>vals(size_t(NE)*NH*NL),tmp(vals.size()),out(vals.size());
#pragma omp parallel for schedule(dynamic)
for(int ih=0;ih<NH;ih++){F h=hn[ih];std::vector<E>a(cut*7);for(int t=0;t<cut;t++)for(int m=0;m<7;m++){E z;for(int i=36;i>=0;i--)z=EF::scale(z,h)+rc(t,m,i);a[t*7+m]=z;}E iv=EF::inv(a[0]),L63=EF::pow(a[0],63);std::array<E,NE>sc;for(int e=0;e<NE;e++)sc[e]=EF::scale(L63,FF::pow(FF::inv(h),v[e]));for(int il=0;il<NL;il++){F l=ln[il];std::vector<E>b(cut);b[0]=E(1);for(int t=1;t<cut;t++){E z;for(int m=6;m>=0;m--)z=EF::scale(z,l)+a[t*7+m];E sum;for(int j=1;2*j<t;j++)sum=sum+b[j]*b[t-j];sum=EF::scale(sum,2);if(t%2==0)sum=sum+b[t/2]*b[t/2];b[t]=EF::scale(z*iv-sum,3);}for(int e=0;e<NE;e++)vals[ix(e,ih,il)]=sc[e]*b[first+e];}}
std::cout<<"grid="<<NH<<" x "<<NL<<" complete; exact tensor interpolation\n"<<std::flush;
#pragma omp parallel for schedule(dynamic)
for(int e=0;e<NE;e++)for(int ih=0;ih<NH;ih++)for(int l=0;l<NL;l++){E z;for(int il=0;il<NL;il++)z=z+EF::scale(vals[ix(e,ih,il)],LL[l][il]);tmp[ix(e,ih,l)]=z;}
bool bad=false;
#pragma omp parallel for reduction(||:bad) schedule(dynamic)
for(int e=0;e<NE;e++)for(int h=0;h<NH;h++)for(int l=0;l<NL;l++){E z;for(int ih=0;ih<NH;ih++)z=z+EF::scale(tmp[ix(e,ih,l)],LH[h][ih]);out[ix(e,h,l)]=z;if(z&&(h>dh[e]||l>dl[e]))bad=true;}if(bad)throw std::runtime_error("tail support");
#pragma omp parallel for reduction(||:bad) schedule(dynamic)
for(int e=0;e<NE;e++)for(int ih=0;ih<NH;ih++)for(int l=0;l<NL;l++){E z;for(int h=NH-1;h>=0;h--)z=EF::scale(z,hn[ih])+out[ix(e,h,l)];if(z!=tmp[ix(e,ih,l)])bad=true;}
#pragma omp parallel for reduction(||:bad) schedule(dynamic)
for(int e=0;e<NE;e++)for(int ih=0;ih<NH;ih++)for(int il=0;il<NL;il++){E z;for(int l=NL-1;l>=0;l--)z=EF::scale(z,ln[il])+tmp[ix(e,ih,l)];if(z!=vals[ix(e,ih,il)])bad=true;}if(bad)throw std::runtime_error("tail tensor roundtrip");
std::array<std::pair<E,E>,3>extras{{{E(1024),E(1024)},{E(0,1),E(1,1)},{E(25,0,1),E(5,0,1)}}};for(auto[h,l]:extras){auto a=source_series(h,l,cut),c=square_series(a),a2=amul(a,a,cut),a3=amul(a,a2,cut);for(int e=0;e<NE;e++){int m=first+e;E literal;for(int j=0;5*j<=m;j++)for(int k=0;5*j+25*k<=m;k++)literal=literal+a3[m-5*j-25*k]*EF::pow(a2[j],5)*EF::pow(a2[k],25);if(literal!=c[m])throw std::runtime_error("literal Frobenius circuit comparison");E z;for(int ih=NH-1;ih>=0;ih--){E row;for(int il=NL-1;il>=0;il--)row=row*l+out[ix(e,ih,il)];z=z*h+row;}if(z*EF::pow(h,v[e])!=c[m])throw std::runtime_error("extra geometric-extension tail check");}}
std::ofstream b(dir+"/tails.bin",std::ios::binary);uint32_t head[]={first,last,uint32_t(NH),uint32_t(NL)};b.write((char*)head,16);b.write((char*)out.data(),out.size()*sizeof(E));std::ofstream t(dir+"/tails.jsonl");std::array<int,NE>terms{};for(int e=0;e<NE;e++)for(int h=0;h<NH;h++)for(int l=0;l<NL;l++)if(E a=out[ix(e,h,l)]){t<<"["<<first+e<<","<<h<<","<<l<<",";EF::json(t,a);t<<"]\n";terms[e]++;}std::ofstream meta(dir+"/tails.meta.json");meta<<"{\"factor_index\":"<<EF::factor_index<<",\"variables\":[\"H\",\"mu\"],\"first\":71,\"last\":73,\"NH\":"<<NH<<",\"NL\":"<<NL<<",\"grid_roundtrip_entries\":"<<out.size()<<",\"extra_checks\":3,\"literal_circuit_checks\":9,\"polynomials\":[";for(int e=0;e<NE;e++){if(e)meta<<",";meta<<"{\"index\":"<<first+e<<",\"H_divisor_exponent\":"<<v[e]<<",\"H_degree_bound\":"<<dh[e]<<",\"mu_degree_bound\":"<<dl[e]<<",\"terms\":"<<terms[e]<<"}";}meta<<"]}\n";std::cout<<"PASS: all tensor entries, support bounds, three extension-valued checks and literal Frobenius-circuit comparisons\n";return 0;}catch(const std::exception&e){std::cerr<<"FAIL: "<<e.what()<<"\n";return 1;}}
