#include "cubic_field.hpp"
using EB=std::vector<EP>;
EB ba(const EB&a,const EB&b){EB c(std::max(a.size(),b.size()));for(int i=0;i<int(c.size());i++)c[i]=(i<int(a.size())?a[i]:EP{})+(i<int(b.size())?b[i]:EP{});return c;}
EB bs(EB a,E b){for(auto&p:a)p=escale(p,b);return a;}
EB bx(EB a,const EP&b){for(auto&p:a)p=p*b;return a;}
EB bm(const EB&a,const EB&b){EB c(a.size()+b.size()-1);for(int i=0;i<int(a.size());i++)for(int j=0;j<int(b.size());j++)c[i+j]=c[i+j]+a[i]*b[j];return c;}
EB bc(const EB&a){return bm(bm(a,a),a);}
std::vector<E> coeff;
size_t id(int j,int m,int h,int x){return ((j*3+m)*13+h)*47+x;}
EB residual(F H){std::array<EB,3>B;for(int j=0;j<3;j++){B[j].resize(3);for(int m=0;m<3;m++){B[j][m].resize(47);for(int x=0;x<47;x++){E a;for(int h=12;h>=0;h--)a=EF::scale(a,H)+coeff[id(j,m,h,x)];B[j][m][x]=a;}B[j][m].trim();}}EP p;for(F c:P)p.push_back(E(c));E q(0,1);EB r=ba(ba(bs(bc(B[0]),q*q),bs(bx(bc(B[1]),p),q)),ba(bx(bc(B[2]),p*p),bs(bx(bm(bm(B[0],B[1]),B[2]),p),EF::scale(q,2))));for(auto&a:r)if(a.deg()>140)throw std::runtime_error("residual x-degree exceeds 140");return r;}
int main(int argc,char**argv){try{if(argc!=4)throw std::runtime_error("usage: cubic_input factor-index compact-binary output-directory");EF::init(std::stoi(argv[1]));EF::check();std::string path=argv[2],dir=argv[3];std::filesystem::create_directories(dir);coeff.resize(3*3*13*47);std::ifstream in(path,std::ios::binary);uint32_t n;in.read((char*)&n,4);if(n!=89481)throw std::runtime_error("compact record count");std::array<E,61>qp;qp[0]=E(1);for(int k=1;k<=60;k++)qp[k]=EF::times_q(qp[k-1]);for(unsigned i=0;i<n;i++){uint32_t r[6];in.read((char*)r,24);auto[j,m,h,k,x,c]=std::tuple{r[0],r[1],r[2],r[3],r[4],r[5]};if(j>2||m>2||h>12||k>60||x>46||c>=FF::N)throw std::runtime_error("invalid compact record");coeff[id(j,m,h,x)]=coeff[id(j,m,h,x)]+EF::scale(qp[k],c);}if(!in||in.peek()!=EOF)throw std::runtime_error("compact input size");E q(0,1),a0;for(F c:std::vector<F>{245794,356725,33043,315361,163299,214299,311173,89654})a0=a0*q+E(c);if(a0)throw std::runtime_error("a0 not zero");E a1=q*(E(299833)+EF::scale(q,232505));if(!a1||q==E(1)||q==E(15383))throw std::runtime_error("not on allowed q chart");F cw=FF::mul(2,FF::div(FF::pow(359499,24),FF::pow(299619,6)));E lead=EF::scale(EF::pow(q,42)*EF::pow(a1,3),cw);
constexpr int N=37,CN=141*7;std::vector<std::vector<E>>vals(N,std::vector<E>(CN));
#pragma omp parallel for schedule(dynamic)
for(int h=0;h<N;h++){auto R=residual(h);for(int m=0;m<7;m++)for(int t=0;t<141;t++)vals[h][t*7+m]=R[m].coef(140-t);}
std::vector<E>out(CN*N);Poly base{1};for(int k=0;k<N;k++){for(int z=0;z<CN;z++)for(int h=0;h<int(base.size());h++)out[z*N+h]=out[z*N+h]+EF::scale(vals[k][z],base[h]);for(int j=N-1;j>k;j--){F iv=FF::inv(FF::sub(j,j-k-1));for(int z=0;z<CN;z++)vals[j][z]=EF::scale(vals[j][z]-vals[j-1][z],iv);}base=base*Poly{FF::neg(k),1};}
for(int m=0;m<7;m++)for(int h=0;h<N;h++){E wanted=(m==0&&h==12)?lead:E();if(out[m*N+h]!=wanted)throw std::runtime_error("global leading coefficient mismatch");}
std::vector<F> checks;for(F h=0;h<N;h++)checks.push_back(h);for(F h:{73u,105u,11111u})checks.push_back(h);for(F h:checks){auto R=residual(h);for(int t=0;t<141;t++)for(int m=0;m<7;m++){E z;for(int i=N-1;i>=0;i--)z=EF::scale(z,h)+out[(t*7+m)*N+i];if(z!=R[m].coef(140-t))throw std::runtime_error("extra compact/source check");}}
std::ofstream bin(dir+"/input.bin",std::ios::binary);bin.write((char*)out.data(),out.size()*sizeof(E));std::ofstream o(dir+"/input.json");o<<"{\"factor_index\":"<<EF::factor_index<<",\"modulus_ascending_K_codes\":["<<EF::mod[0]<<","<<EF::mod[1]<<","<<EF::mod[2]<<",1],\"variables\":[\"H\",\"mu\",\"T\"],\"convention\":\"T^140 W(1/T), q is the cubic extension generator\",\"leading_H12_coefficient\":";EF::json(o,lead);o<<",\"terms\":[";bool first=true;int terms=0;for(int h=0;h<N;h++)for(int m=0;m<7;m++)for(int t=0;t<141;t++)if(E a=out[(t*7+m)*N+h]){if(!first)o<<",";first=false;o<<"["<<h<<","<<m<<","<<t<<",";EF::json(o,a);o<<"]";terms++;}o<<"]}\n";std::cout<<"PASS: exact compact specialization and H interpolation; full 37-node roundtrip; a0=0, a1!=0, leading coefficient and all-scale/all-x extra checks; terms="<<terms<<"\n";return 0;}catch(const std::exception&e){std::cerr<<"FAIL: "<<e.what()<<"\n";return 1;}}
