#define CUBIC_RESULTANT_FUNCTIONS_ONLY
#include "cubic_tests.cpp"
struct Gen{int index,dl;std::vector<EP>lc;std::vector<int>lv;};
EP at(const Gen&g,F h){EP a(g.dl+1);for(int l=0;l<=g.dl;l++)a[l]=EF::scale(keval(g.lc[l],h),FF::pow(h,g.lv[l]));a.trim();return a;}
EP atE(const Gen&g,E h){EP a(g.dl+1);for(int l=0;l<=g.dl;l++)a[l]=eeval(g.lc[l],h)*EF::pow(h,g.lv[l]);a.trim();return a;}
int degree_bound(const Gen&g,const Gen&h){int best=10000000;for(int w=-20;w<=20;w++){int dg=-100000,dh=-100000;for(int l=0;l<=g.dl;l++)if(!g.lc[l].empty())dg=std::max(dg,g.lc[l].deg()+g.lv[l]+w*l);for(int l=0;l<=h.dl;l++)if(!h.lc[l].empty())dh=std::max(dh,h.lc[l].deg()+h.lv[l]+w*l);best=std::min(best,h.dl*dg+g.dl*dh-w*g.dl*h.dl);}return best;}
EP interpolate(std::vector<E>v,const std::vector<F>&nodes,const std::vector<F>&ip,const std::vector<F>&id){int N=v.size();for(int k=0;k<N-1;k++)for(int j=N-1;j>k;j--)v[j]=EF::scale(v[j]-v[j-1],KF::mul(ip[j-k-1],id[k+1]));EP p{v.back()};for(int k=N-2;k>=0;k--){p.push_back(p.back());for(int j=int(p.size())-2;j>0;j--)p[j]=p[j-1]-EF::scale(p[j],nodes[k]);p[0]=v[k]-EF::scale(p[0],nodes[k]);}p.trim();return p;}
int main(int argc,char**argv){try{if(argc<3||argc>4)throw std::runtime_error("usage: cubic_resultants factor-index input-output-directory [from-verified-nodes]");EF::init(std::stoi(argv[1]));std::string dir=argv[2];std::ifstream in(dir+"/tails.bin",std::ios::binary);uint32_t hd[4];in.read((char*)hd,16);int start=hd[0],end=hd[1],NH=hd[2],NL=hd[3];if(start!=71||end!=73||NH<=0||NL<=0)throw std::runtime_error("bad tail header");std::vector<E>raw(size_t(end-start+1)*NH*NL);in.read((char*)raw.data(),raw.size()*sizeof(E));if(!in||in.peek()!=EOF)throw std::runtime_error("tail binary size");std::vector<Gen>gs;for(int i=0;i<3;i++){Gen g;g.index=start+i;g.dl=0;g.lc.resize(NL);g.lv.resize(NL);for(int l=0;l<NL;l++){EP a(NH);for(int h=0;h<NH;h++)a[h]=raw[(size_t(i)*NH+h)*NL+l];a.trim();int v=0;while(v<int(a.size())&&!a[v])v++;if(v)a.erase(a.begin(),a.begin()+v);g.lc[l]=a;g.lv[l]=v;if(!a.empty())g.dl=l;}g.lc.resize(g.dl+1);g.lv.resize(g.dl+1);gs.push_back(g);}
int D1=degree_bound(gs[0],gs[1]),D2=degree_bound(gs[0],gs[2]),N=std::max(D1,D2)+1;std::cout<<"factor="<<EF::factor_index<<"; fixed mu degrees="<<gs[0].dl<<","<<gs[1].dl<<","<<gs[2].dl<<"; H-degree bounds="<<D1<<","<<D2<<"; nodes="<<N<<"\n"<<std::flush;std::vector<F>nodes(N),ip(N),id(N),seen(FF::N);F z=25,zi=FF::inv(z);nodes[0]=ip[0]=1;for(int i=1;i<N;i++){nodes[i]=KF::mul(nodes[i-1],z);ip[i]=KF::mul(ip[i-1],zi);id[i]=FF::inv(KF::sub(nodes[i],1));}for(F h:nodes)if(seen[h]++)throw std::runtime_error("node collision");std::array<std::vector<E>,2>vals;for(auto&v:vals)v.resize(N);
if(argc==4){if(std::string(argv[3])!="from-verified-nodes")throw std::runtime_error("unknown option");std::ifstream s(dir+"/resultant_nodes.bin",std::ios::binary);uint32_t header[4];s.read((char*)header,16);if(header[0]!=unsigned(EF::factor_index)||header[1]!=unsigned(N)||header[2]!=unsigned(D1)||header[3]!=unsigned(D2))throw std::runtime_error("node metadata mismatch");for(auto&v:vals)s.read((char*)v.data(),v.size()*sizeof(E));if(!s||s.peek()!=EOF)throw std::runtime_error("bad node file");std::cout<<"Restarting from retained node evaluations; caller must verify their input/output hashes.\n"<<std::flush;
}else{
#pragma omp parallel for schedule(dynamic,16)
for(int i=0;i<N;i++){EP a=at(gs[0],nodes[i]),b=at(gs[1],nodes[i]),c=at(gs[2],nodes[i]);vals[0][i]=eresultant(a,b,gs[0].dl,gs[1].dl);vals[1][i]=eresultant(a,c,gs[0].dl,gs[2].dl);if(i%4096==0){
#pragma omp critical
std::cout<<"resultant node index="<<i<<" / "<<N<<"\n"<<std::flush;}}
std::ofstream s(dir+"/resultant_nodes.bin",std::ios::binary);uint32_t header[]={unsigned(EF::factor_index),unsigned(N),unsigned(D1),unsigned(D2)};s.write((char*)header,16);for(auto&v:vals)s.write((char*)v.data(),v.size()*sizeof(E));}
std::cout<<"nodes complete; exact interpolation\n"<<std::flush;std::array<EP,2>polys;
#pragma omp parallel for
for(int k=0;k<2;k++){polys[k]=interpolate(vals[k],nodes,ip,id);
#pragma omp critical
std::cout<<"interpolated resultant="<<k<<"; degree="<<polys[k].deg()<<"\n"<<std::flush;}
if(polys[0].deg()>D1||polys[1].deg()>D2)throw std::runtime_error("resultant degree bound");bool bad=false;
#pragma omp parallel for reduction(||:bad) schedule(dynamic,16)
for(int i=0;i<N;i++)for(int k=0;k<2;k++)if(keval(polys[k],nodes[i])!=vals[k][i])bad=true;if(bad)throw std::runtime_error("full resultant roundtrip");std::cout<<"all nodes roundtripped; extra extension-valued checks\n"<<std::flush;for(E h:{E(),E(11111),E(0,1),E(25,1,1)}){auto a=atE(gs[0],h),b=atE(gs[1],h),c=atE(gs[2],h);if(eeval(polys[0],h)!=eresultant(a,b,gs[0].dl,gs[1].dl)||eeval(polys[1],h)!=eresultant(a,c,gs[0].dl,gs[2].dl))throw std::runtime_error("extra fixed-degree resultant check");}
std::ofstream o(dir+"/resultants.json");o<<"{\"factor_index\":"<<EF::factor_index<<",\"generator_indices\":[71,72,73],\"mu_degrees\":["<<gs[0].dl<<","<<gs[1].dl<<","<<gs[2].dl<<"],\"H_degree_bounds\":["<<D1<<","<<D2<<"],\"node_count\":"<<N<<",\"node_generator_K_code\":25,\"extra_checks\":4,\"polynomials\":[";json_ep(o,polys[0]);o<<",";json_ep(o,polys[1]);o<<"]}\n";for(int k=0;k<2;k++)write_ep(dir+"/res"+std::to_string(k)+".bin",polys[k]);std::cout<<"PASS: fixed-degree resultants over the cubic extension; no geometric exclusion claimed before the gcd step\n";return 0;}catch(const std::exception&e){std::cerr<<"FAIL: "<<e.what()<<"\n";return 1;}}
