#include "../../src/residual.hpp"
#include <filesystem>
#include <omp.h>
static std::vector<F> a625;
inline F addf(F a,F b){return a625[(a%625)*625+b%625]+625*a625[(a/625)*625+b/625];}
inline F mulf(F a,F b){return a&&b?FF::ex[FF::lg[a]+FF::lg[b]]:0;}
static std::vector<std::vector<F>> lagrange(const std::vector<F>& nodes){Poly p{1};for(F z:nodes)p=p*Poly{FF::neg(z),1};auto dp=derivative(p);std::vector<std::vector<F>> M(nodes.size(),std::vector<F>(nodes.size()));for(int i=0;i<int(nodes.size());i++){Poly l=scale(exactdiv(p,Poly{FF::neg(nodes[i]),1}),FF::inv(eval(dp,nodes[i])));for(int j=0;j<int(nodes.size());j++)M[j][i]=l.coef(j);}return M;}
static std::vector<F> cof;
F rc(int t,int m,int h){return cof[(t*7+m)*37+h];}
std::vector<F> square_series(F h,F l,int cut){std::vector<F>a(cut),b(cut);for(int t=0;t<cut;t++){F z=0;for(int m=6;m>=0;m--){F c=0;for(int i=36;i>=0;i--)c=addf(mulf(c,h),rc(t,m,i));z=addf(mulf(z,l),c);}a[t]=z;}F iv=FF::inv(a[0]);b[0]=1;for(int t=1;t<cut;t++){F sum=0;for(int j=1;j*2<t;j++)sum=addf(sum,mulf(b[j],b[t-j]));sum=mulf(sum,2);if(t%2==0)sum=addf(sum,mulf(b[t/2],b[t/2]));b[t]=mulf(3,FF::sub(mulf(a[t],iv),sum));}F L63=FF::pow(a[0],63);for(auto&v:b)v=mulf(v,L63);return b;}
int main(int argc,char**argv){try{if(argc!=4)throw std::runtime_error("usage: fiber_tails input-directory first-index last-index");std::string dir=argv[1];int first=std::stoi(argv[2]),last=std::stoi(argv[3]);if(first<71||last>124||last<first)throw std::runtime_error("invalid range");init_curve();a625.resize(625*625);for(F a=0;a<625;a++)for(F b=0;b<625;b++)a625[a*625+b]=FF::add(a,b);cof.resize(141*7*37);std::ifstream in(dir+"/fiber_input.bin",std::ios::binary);in.read((char*)cof.data(),cof.size()*4);if(!in||in.peek()!=EOF)throw std::runtime_error("bad input size");int cut=last+1,NE=last-first+1,INF=100000;
 auto conv=[&](const std::vector<int>&a,const std::vector<int>&b,bool low){std::vector<int>c(cut,low?INF:-INF);for(int i=0;i<cut;i++)for(int j=0;i+j<cut;j++)if(abs(a[i])<INF&&abs(b[j])<INF)c[i+j]=low?std::min(c[i+j],a[i]+b[j]):std::max(c[i+j],a[i]+b[j]);return c;};
 std::array<std::vector<int>,3> b1,b2,b3;for(int k=0;k<3;k++)b1[k].assign(cut,k==0?INF:-INF);for(int t=0;t<cut;t++)for(int m=0;m<7;m++)for(int h=0;h<37;h++)if(rc(t,m,h)){b1[0][t]=std::min(b1[0][t],h);b1[1][t]=std::max(b1[1][t],h);b1[2][t]=std::max(b1[2][t],m);}for(int k=0;k<3;k++){b2[k]=conv(b1[k],b1[k],k==0);b3[k]=conv(b1[k],b2[k],k==0);}
 std::vector<int> v(NE),dh(NE),dl(NE);int NH=0,NL=0;for(int e=0;e<NE;e++){int t=first+e;std::array<int,3>b{INF,-INF,-INF};for(int j=0;5*j<=t;j++)for(int k=0;5*j+25*k<=t;k++){int i=t-5*j-25*k;for(int z=0;z<3;z++)if(abs(b3[z][i])<INF&&abs(b2[z][j])<INF&&abs(b2[z][k])<INF){int a=b3[z][i]+5*b2[z][j]+25*b2[z][k];b[z]=z==0?std::min(b[z],a):std::max(b[z],a);}}v[e]=b[0];dh[e]=b[1]-b[0];dl[e]=b[2];NH=std::max(NH,dh[e]+1);NL=std::max(NL,dl[e]+1);std::cout<<"tail="<<t<<" divide h^"<<v[e]<<"; degrees <=("<<dh[e]<<","<<dl[e]<<")\n";}
 std::vector<F>hn,ln(NL);for(F h=1;int(hn.size())<NH;h++){F z=0;for(int i=36;i>=0;i--)z=addf(mulf(z,h),rc(0,0,i));if(z)hn.push_back(h);}std::iota(ln.begin(),ln.end(),0);auto LH=lagrange(hn),LL=lagrange(ln);auto ix=[&](int e,int h,int l){return (size_t(e)*NH+h)*NL+l;};std::vector<F>vals(size_t(NE)*NH*NL),tmp(vals.size()),out(vals.size());
 #pragma omp parallel for schedule(dynamic)
 for(int ih=0;ih<NH;ih++){F h=hn[ih];std::vector<F>a(cut*7);for(int t=0;t<cut;t++)for(int m=0;m<7;m++){F z=0;for(int i=36;i>=0;i--)z=addf(mulf(z,h),rc(t,m,i));a[t*7+m]=z;}F iv=FF::inv(a[0]),L63=FF::pow(a[0],63);std::vector<F>sc(NE);for(int e=0;e<NE;e++)sc[e]=mulf(L63,FF::pow(FF::inv(h),v[e]));for(int il=0;il<NL;il++){F l=ln[il];std::vector<F>b(cut);b[0]=1;for(int t=1;t<cut;t++){F z=0;for(int m=6;m>=0;m--)z=addf(mulf(z,l),a[t*7+m]);F sum=0;for(int j=1;j*2<t;j++)sum=addf(sum,mulf(b[j],b[t-j]));sum=mulf(sum,2);if(t%2==0)sum=addf(sum,mulf(b[t/2],b[t/2]));b[t]=mulf(3,FF::sub(mulf(z,iv),sum));}for(int e=0;e<NE;e++)vals[ix(e,ih,il)]=mulf(sc[e],b[first+e]);}}
 std::cout<<"grid evaluations="<<NH*NL<<"; interpolating\n"<<std::flush;
 #pragma omp parallel for schedule(dynamic)
 for(int e=0;e<NE;e++)for(int ih=0;ih<NH;ih++)for(int l=0;l<NL;l++){F z=0;for(int il=0;il<NL;il++)z=addf(z,mulf(LL[l][il],vals[ix(e,ih,il)]));tmp[ix(e,ih,l)]=z;}
 #pragma omp parallel for schedule(dynamic)
 for(int e=0;e<NE;e++)for(int h=0;h<NH;h++)for(int l=0;l<NL;l++){F z=0;for(int ih=0;ih<NH;ih++)z=addf(z,mulf(LH[h][ih],tmp[ix(e,ih,l)]));out[ix(e,h,l)]=z;if(z&&(h>dh[e]||l>dl[e]))throw std::runtime_error("support failure");}
 std::cout<<"interpolation complete; full grid roundtrip\n"<<std::flush;bool bad=false;
 #pragma omp parallel for reduction(||:bad) schedule(dynamic)
 for(int e=0;e<NE;e++)for(int ih=0;ih<NH;ih++)for(int l=0;l<NL;l++){F z=0;for(int h=NH-1;h>=0;h--)z=addf(mulf(z,hn[ih]),out[ix(e,h,l)]);if(z!=tmp[ix(e,ih,l)])bad=true;}
 #pragma omp parallel for reduction(||:bad) schedule(dynamic)
 for(int e=0;e<NE;e++)for(int ih=0;ih<NH;ih++)for(int il=0;il<NL;il++){F z=0;for(int l=NL-1;l>=0;l--)z=addf(mulf(z,ln[il]),tmp[ix(e,ih,l)]);if(z!=vals[ix(e,ih,il)])bad=true;}
 if(bad)throw std::runtime_error("grid roundtrip failure");
 for(auto[h,l]:std::vector<std::pair<F,F>>{{1024,1024},{11111,12345},{FF::N-1,FF::N-2}}){auto c=square_series(h,l,cut);for(int e=0;e<NE;e++){F z=0;for(int hidx=NH-1;hidx>=0;hidx--){F t=0;for(int lidx=NL-1;lidx>=0;lidx--)t=addf(mulf(t,l),out[ix(e,hidx,lidx)]);z=addf(mulf(z,h),t);}if(z!=FF::div(c[first+e],FF::pow(h,v[e])))throw std::runtime_error("extra tail check failed");}}
 std::string pref=dir+"/tails_"+std::to_string(first)+"_"+std::to_string(last);std::ofstream bin(pref+".bin",std::ios::binary);uint32_t head[]={uint32_t(first),uint32_t(last),uint32_t(NH),uint32_t(NL)};bin.write((char*)head,16);bin.write((char*)out.data(),out.size()*4);std::ofstream text(pref+".jsonl");std::vector<int>terms(NE);for(int e=0;e<NE;e++)for(int h=0;h<NH;h++)for(int l=0;l<NL;l++)if(F c=out[ix(e,h,l)]){text<<"["<<first+e<<","<<h<<","<<l<<","<<c<<"]\n";terms[e]++;}
 std::ofstream meta(pref+".meta.json");meta<<"{\"variables\":[\"h\",\"lambda\"],\"first\":"<<first<<",\"last\":"<<last<<",\"NH\":"<<NH<<",\"NL\":"<<NL<<",\"grid_roundtrip_entries\":"<<out.size()<<",\"extra_checks\":3,\"polynomials\":[";for(int e=0;e<NE;e++){if(e)meta<<",";meta<<"{\"index\":"<<first+e<<",\"h_divisor_exponent\":"<<v[e]<<",\"h_degree_bound\":"<<dh[e]<<",\"lambda_degree_bound\":"<<dl[e]<<",\"terms\":"<<terms[e]<<"}";}meta<<"]}\n";std::cout<<"PASS: all coefficient grid entries, support bounds and three extra checks; output "<<pref<<"\n";return 0;
 }catch(const std::exception&e){std::cerr<<"FAIL: "<<e.what()<<"\n";return 1;}}
