#include "../../src/residual.hpp"
#include <filesystem>
static std::vector<F> addtab,negate;
inline F fa(F a,F b){return addtab[(a%625)*625+b%625]+625*addtab[(a/625)*625+b/625];}
inline F fs(F a,F b){return fa(a,negate[b]);}
inline F fm(F a,F b){return a&&b?FF::ex[FF::lg[a]+FF::lg[b]]:0;}
Poly sm(Poly a,F c){for(auto&v:a)v=fm(v,c);a.trim();return a;}
Poly ps(const Poly&a,const Poly&b){Poly c(std::max(a.size(),b.size()));for(int i=0;i<int(c.size());i++)c[i]=fs(a.coef(i),b.coef(i));c.trim();return c;}
Poly pm(const Poly&a,const Poly&b){if(a.empty()||b.empty())return {};Poly c(a.size()+b.size()-1);for(int i=0;i<int(a.size());i++)if(a[i])for(int j=0;j<int(b.size());j++)if(b[j])c[i+j]=fa(c[i+j],fm(a[i],b[j]));c.trim();return c;}
std::pair<Poly,Poly> pd(Poly a,const Poly&b){if(b.empty())throw std::runtime_error("division by zero");Poly q(std::max(0,a.deg()-b.deg()+1));F iv=FF::inv(b.back());for(int i=a.deg()-b.deg();i>=0;i--){F v=fm(a[i+b.deg()],iv);q[i]=v;if(v)for(int j=0;j<=b.deg();j++)a[i+j]=fs(a[i+j],fm(v,b[j]));}a.resize(std::min(a.size(),b.size()-1));a.trim();q.trim();return {q,a};}
Poly read(const std::string&path){auto n=std::filesystem::file_size(path);if(n%4)throw std::runtime_error("bad size");Poly p(n/4);std::ifstream f(path,std::ios::binary);f.read((char*)p.data(),n);if(!f)throw std::runtime_error("read failure");p.trim();return p;}
int main(int argc,char**argv){try{if(argc!=2)throw std::runtime_error("usage: fiber_gcd resultants-directory");std::string dir=argv[1];init_curve();addtab.resize(625*625);for(F a=0;a<625;a++)for(F b=0;b<625;b++)addtab[a*625+b]=FF::add(a,b);negate.resize(FF::N);for(F a=0;a<FF::N;a++)negate[a]=FF::neg(a);Poly a=read(dir+"/res0.bin"),b=read(dir+"/res1.bin");if(a.empty()||b.empty())throw std::runtime_error("zero resultant not handled");int va=0,vb=0;while(!a[va])va++;while(!b[vb])vb++;a.erase(a.begin(),a.begin()+va);b.erase(b.begin(),b.begin()+vb);Poly aa=a,bb=b;std::cout<<"resultant degrees after h factors "<<a.deg()<<","<<b.deg()<<"; removed h valuations "<<va<<","<<vb<<"\n"<<std::flush;
 Poly u{1},v{},s{},z{1};int step=0;while(!b.empty()){auto[q,r]=pd(a,b);auto uu=ps(u,pm(q,s)),vv=ps(v,pm(q,z));a=std::move(b);b=std::move(r);u=std::move(s);v=std::move(z);s=std::move(uu);z=std::move(vv);step++;if(step%2048==0)std::cout<<"Euclidean steps="<<step<<" remainder degree="<<b.deg()<<"\n"<<std::flush;}
 F iv=FF::inv(a.back());a=sm(a,iv);u=sm(u,iv);v=sm(v,iv);std::cout<<"gcd degree="<<a.deg()<<"; verifying full Bezout identity\n"<<std::flush;auto check=ps(pm(aa,u),sm(pm(bb,v),4));if(check!=a)throw std::runtime_error("Bezout identity failed");std::ofstream o(dir+"/gcd_certificate.json");o<<"{\"h_valuations\":["<<va<<","<<vb<<"],\"reduced_resultant_degrees\":["<<aa.deg()<<","<<bb.deg()<<"],\"euclidean_steps\":"<<step<<",\"gcd\":";json_poly(o,a);o<<",\"multipliers\":[";json_poly(o,u);o<<",";json_poly(o,v);o<<"],\"identity\":\"u*(res0/h^v0)+v*(res1/h^v1)=gcd\"}\n";std::cout<<"PASS: exact polynomial Bezout identity; ";if(a.deg()==0)std::cout<<"entire h!=0 fiber excluded for all geometric lambda\n";else std::cout<<"remaining h candidates have degree "<<a.deg()<<"; no complete exclusion yet\n";return 0;
 }catch(const std::exception&e){std::cerr<<"FAIL: "<<e.what()<<"\n";return 1;}}
