import Mathlib.RingTheory.FiniteType
import Mathlib.RingTheory.Localization.FractionRing
import Mathlib.FieldTheory.IntermediateField.Adjoin.Basic

namespace Litt3.SharedTensors

variable {k R K : Type*} [Field k] [CommRing R] [IsDomain R] [Field K]
  [Algebra k R] [Algebra k K] [Algebra R K] [IsScalarTower k R K]
  [IsFractionRing R K] [Algebra.FiniteType k R]

include R

/-- The genuine fraction field of any finite-type domain is generated by
the same finite algebra generators as a field. This does not falsely assert
that the fraction field is a finite-type algebra. -/
theorem actual_finite_type_fraction_field_finitely_generated :
    IntermediateField.FG (F := k) (E := K) ⊤ := by
  obtain ⟨s, hs⟩ := Algebra.FiniteType.out (R := k) (A := R)
  let t : Set K := (algebraMap R K) '' (↑s : Set R)
  let E : IntermediateField k K := IntermediateField.adjoin k t
  have hR : ∀ r : R, algebraMap R K r ∈ E := by
    have hle : Algebra.adjoin k (↑s : Set R) ≤
        E.toSubalgebra.comap (IsScalarTower.toAlgHom k R K) := by
      apply Algebra.adjoin_le
      intro r hr
      exact IntermediateField.subset_adjoin k t ⟨r, hr, rfl⟩
    rw [hs] at hle
    intro r
    exact hle (by trivial)
  apply IntermediateField.fg_def.mpr
  refine ⟨t, s.finite_toSet.image _, ?_⟩
  apply top_unique
  intro x _
  obtain ⟨n, d, _, hnd⟩ := IsFractionRing.div_surjective (A := R) x
  rw [← hnd]
  exact E.div_mem (hR n) (hR d)

end Litt3.SharedTensors
