import Solutions.SharedTensors.PowerSeriesPBasisDigits
import Solutions.SharedTensors.PBasisParameterGeneration
import Solutions.CartierAndSpin.LaurentDerivation
import Mathlib.Algebra.CharP.Algebra

namespace Litt3.SharedTensors

open scoped LaurentSeries BigOperators
open IntermediateField Polynomial Module

variable {k : Type*} [Field k] [PerfectField k]
  {p : ℕ} [Fact p.Prime] [CharP k p]

noncomputable local instance : Module k (LaurentSeries k) := Algebra.toModule

instance laurentSeriesCharP (k : Type*) [Field k] (p : ℕ) [CharP k p] :
    CharP (LaurentSeries k) p :=
  charP_of_injective_algebraMap (algebraMap k (LaurentSeries k)).injective p

noncomputable def laurentParameter (k : Type*) [Field k] : LaurentSeries k :=
  HahnSeries.single 1 1

/-- Every entire power series belongs to the subfield generated by the
actual p-th powers and the actual Laurent uniformizer. -/
theorem power_series_mem_laurent_pth_parameter_field (f : PowerSeries k) :
    (f : LaurentSeries k) ∈
      IntermediateField.adjoin (frobeniusSubfield (LaurentSeries k) p)
        {laurentParameter k} := by
  let J := IntermediateField.adjoin (frobeniusSubfield (LaurentSeries k) p)
    {laurentParameter k}
  have ht : laurentParameter k ∈ J :=
    subset_adjoin (frobeniusSubfield (LaurentSeries k) p) _ (by simp)
  rw [power_series_full_p_basis_expansion (p := p) f]
  simp only [map_sum, map_mul, map_pow, HahnSeries.ofPowerSeries_X]
  apply J.sum_mem
  intro i _
  apply J.mul_mem
  · apply J.algebraMap_mem
      (frobeniusImageEquiv (LaurentSeries k) p
        (powerSeriesPBasisDigit f i : LaurentSeries k))
  · exact pow_mem ht i.val

/-- The full Laurent field is generated by its actual p-th powers and
the actual uniformizer, including all negative powers. -/
theorem laurent_pth_parameter_field_eq_top :
    IntermediateField.adjoin (frobeniusSubfield (LaurentSeries k) p)
      {laurentParameter k} = ⊤ := by
  let J := IntermediateField.adjoin (frobeniusSubfield (LaurentSeries k) p)
    {laurentParameter k}
  have ht : laurentParameter k ∈ J :=
    subset_adjoin (frobeniusSubfield (LaurentSeries k) p) _ (by simp)
  apply le_antisymm le_top
  intro f _
  rw [← LaurentSeries.single_order_mul_powerSeriesPart f,
    RatFunc.single_zpow]
  apply J.mul_mem
  · exact J.pow_mem ht f.order
  · exact power_series_mem_laurent_pth_parameter_field f.powerSeriesPart

/-- The normalized continuous derivative is also an actual algebraic
derivation on the entire Laurent field. -/
theorem laurent_derivation_parameter :
    Litt3.CartierAndSpin.laurentDerivation k (laurentParameter k) = 1 := by
  change LaurentSeries.derivative k (HahnSeries.single 1 1) = 1
  ext n
  simp only [LaurentSeries.derivative_apply, HahnSeries.coeff_one]
  by_cases h : n = 0
  · subst n
    simp
  · simp [h]

theorem laurent_parameter_not_in_pth_field :
    laurentParameter k ∉ frobeniusSubfield (LaurentSeries k) p := by
  rintro ⟨a, ha⟩
  change a ^ p = laurentParameter k at ha
  let D := Litt3.CartierAndSpin.laurentDerivation k
  have hz : D (a ^ p) = 0 := by
    rw [D.leibniz_pow, nsmul_eq_mul, CharP.cast_eq_zero (LaurentSeries k) p, zero_mul]
  rw [ha, laurent_derivation_parameter] at hz
  exact one_ne_zero hz

/-- The literal p-basis of the whole Laurent field is constructed,
without a finite-generation or continuous-differentials premise. -/
theorem laurent_power_p_basis_exists :
    ∃ b : PowerPBasis (LaurentSeries k) p, b.parameter = laurentParameter k := by
  exact generated_nonpth_power_p_basis_exists (laurentParameter k)
    laurent_parameter_not_in_pth_field laurent_pth_parameter_field_eq_top

end Litt3.SharedTensors
