"""Write transparent claim/certificate indexes; not a proof checker."""
import hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
def digest(path):
 h=hashlib.sha256()
 with open(path,'rb') as f:
  for block in iter(lambda:f.read(1<<20),b''):h.update(block)
 return h.hexdigest()
def evidence(path,section=None):
 d={'path':path}
 if section:d['section']=section
 return d
claims=[
 {'id':'A0','status':'supplied_assumption','statement':'The sixteen-coordinate atlas is exhaustive for nonzero middle-character f; the pure-v locus and f=0 maps cannot occur in the requested Hom window.','evidence':[evidence('REPORT.md','2.3')],'independently_reproved':False},
 {'id':'A1','status':'supplied_assumption','statement':'The stated Laurent gluing equations characterize actual global maps, and the stated connecting-image criterion characterizes geometric stability.','evidence':[evidence('REPORT.md','3'),evidence('REPORT.md','8.3')],'independently_reproved':False},
 {'id':'C1','status':'computationally_checked','statement':'The actual constant matrices have ranks 235 and 116, and the full pencils T (80x35) and Q (43x16) are reconstructed exactly, with no f or correction columns omitted.','evidence':[evidence('data/pencils.npz'),evidence('src/build.py'),evidence('src/verify.py'),evidence('logs/final_verification.log')],'dependencies':['A1']},
 {'id':'C2','status':'computationally_checked','statement':'The all-alpha annihilator has dimension 29, its three source column spaces are a direct sum of dimensions 10,6,13, and the full middle incidence has 67 rows in blocks 30,23,14.','evidence':[evidence('data/blocks.npz'),evidence('data/middle_system.npz'),evidence('data/unmatched.npz'),evidence('src/verify.py'),evidence('logs/final_verification.log')],'dependencies':['C1']},
 {'id':'P1','status':'proved','statement':'For every c,d over the algebraic closure, SC(c)d=0 and c nonzero imply d=0.','proof_type':'Explicit invertible 84x84 Macaulay matrix plus the field argument c_k^2*d_l=0.','evidence':[evidence('REPORT.md','5'),evidence('certificates/unmatched_gamma0.npz'),evidence('src/verify.py'),evidence('logs/final_verification.log')],'dependencies':['C2']},
 {'id':'P2','status':'proved','statement':'The 66x32 linear pencil N(c) has rank32 at every nonzero geometric c.','proof_type':'Polynomial row-module identities proving full constant span on all six first-nonzero-coordinate strata. No finite-field equations are imposed.','evidence':[evidence('REPORT.md','6.1–6.2'),evidence('data/necessary_tensor.npz'),evidence('certificates/index.json'),evidence('src/verify_inputs.py'),evidence('src/verify_dag.cpp'),evidence('logs/N_all_dags_verification.log'),evidence('logs/N_chart0_verification.json'),evidence('logs/final_verification.log')],'dependencies':['C2']},
 {'id':'P3','status':'proved','statement':'For every actual middle-character map from a nonzero source with nonzero p of degree at most7, the y^2 correction coefficient gamma is zero, without a stability or Hom-dimension hypothesis.','proof_type':'For nonzero B block, normalize gamma=1, eliminate ten source coordinates, and contradict P2 with p tensor d; for zero B block, use the explicit 30x6 gamma-coefficient injection.','evidence':[evidence('REPORT.md','4.2'),evidence('REPORT.md','6.3'),evidence('certificates/source_C_gamma_injection.json')],'dependencies':['A1','C1','C2','P2']},
 {'id':'P4','status':'proved','statement':'Every requested Hom-window point has alpha=A(x), degree A at most6. All unmatched correction terms are rigorously excluded.','proof_type':'P3, then P1 when source C is nonzero; when source C is zero a nonzero y-correction gives a second linearly independent complete map, contradicting the one-dimensional Hom-to-K space.','evidence':[evidence('REPORT.md','6.4')],'dependencies':['P1','P3','C1','C2']},
 {'id':'P5','status':'proved','statement':'The requested locus on a1=a2=a3=0 is empty over the algebraic closure, including all source rank-drop boundaries.','proof_type':'Seven exact polynomial row-module certificates show the matched 30x15 pencil is injective on every nonzero B block in that boundary; the zero B block is excluded by the supplied theorem.','evidence':[evidence('REPORT.md','7'),evidence('certificates/index.json'),evidence('logs/matched_boundaries_verification.log'),evidence('logs/final_verification.log')],'dependencies':['A0','P4','C2']},
 {'id':'P6','status':'proved','statement':'The original existence question is equivalent to the residual system (8.1), retaining the complete T and Q ranks and geometric stability.','proof_type':'Exact character block equations and unique auxiliary reconstruction, combined with P4 and P5.','evidence':[evidence('REPORT.md','8.1'),evidence('data/residual_system.npz'),evidence('src/evaluate_f25.py')],'dependencies':['A0','A1','C1','C2','P4','P5']},
 {'id':'C3','status':'computationally_checked','statement':'The specified pure-v F25 diagnostic has Hom dimensions 7 and 4; its seven complete basis maps reconstruct globally and all have generic rank one. It is not a witness.','evidence':[evidence('data/sanity_maps.json'),evidence('src/evaluate_f25.py'),evidence('src/verify_diagnostics.py'),evidence('logs/sanity_maps.log'),evidence('logs/final_verification.log')],'dependencies':['C1']},
 {'id':'C4','status':'computationally_checked','statement':'The four specified connecting-image directions at branch points [9],[14] have T rank35 and Q rank16. This is neither an exhaustive field search nor a geometric stability test.','evidence':[evidence('data/branch_sanity.json'),evidence('src/branch_sanity.py'),evidence('logs/branch_sanity.log'),evidence('logs/final_verification.log')],'dependencies':['A1','C1']},
 {'id':'E1','status':'incomplete_computation','statement':'The matched module calculations on remaining strata0,1,2 and the stratum0 continuation stopped at their specified exploration limits, without a full constant span. These outcomes imply neither emptiness nor existence.','evidence':[evidence('REPORT.md','10.2'),evidence('logs/experiments.json'),evidence('certificates/index.json')],'asserted_groebner_basis':False},
 {'id':'C5','status':'computationally_checked','statement':'The stored unfinished checkpoint polynomials satisfy their membership identities; the continuation input is exactly its listed selection of parent members. No completeness or minimality is asserted.','evidence':[evidence('src/verify_bridge.py'),evidence('logs/checkpoint_membership_verification.log'),evidence('logs/bridge_verification.log'),evidence('certificates/index.json')],'dependencies':['C1','C2']},
 {'id':'OPEN','status':'open','statement':'Whether any stable source survives (8.1) on the three remaining source strata, with full ranks T=34,Q=16 and 3<=degree p<=7. No qualifying source, complete map, or global nonexistence proof is given.','evidence':[evidence('REPORT.md','8'),evidence('REPORT.md','10.3')],'not_settled_by':['P4','P5','E1']}
]
(ROOT/'claims.json').write_text(json.dumps({'objective_status':'partial','main_decision_claim':'OPEN','coefficient_scope':'geometric over algebraic closure of F5, except explicitly F25 diagnostics','claims':claims},indent=2)+'\n')
entries=[]
for name,nodes,n,first in [('N_chart0',1702,32,0)]+[(f'N_stratum{j}',nodes,32,j) for j,nodes in [(1,466),(2,176),(3,96),(4,64),(5,32)]]+[(f'matched_stratum{j}',nodes,15,j) for j,nodes in [(3,991),(4,360),(5,150),(6,75),(7,45),(8,30),(9,15)]]:
 p=ROOT/f'certificates/{name}.dag';nv,nc,ng=map(int,(ROOT/f'data/{name}.txt').open().readline().split())
 entries.append(dict(name=name,status='proved_full_row_module_on_specified_stratum',input=f'data/{name}.txt',coefficient_row_provenance=f'data/{name}.npz',dag=f'certificates/{name}.dag',input_generators=ng,polynomial_variables=nv,module_rank=nc,verified_nodes=nodes,verified_constant_rank=n,first_nonzero_source_coordinate_zero_based=first,all_extension_fields=True,finite_field_equations_imposed=False,bytes=p.stat().st_size,sha256=digest(p)))
for name,nodes in [('matched_chart0',360),('matched_chart0_minimal',408),('matched_stratum1',692),('matched_stratum2',1247)]:
 p=ROOT/f'certificates/{name}.dag';nv,nc,ng=map(int,(ROOT/f'data/{name}.txt').open().readline().split())
 entries.append(dict(name=name,status='verified_membership_checkpoint_incomplete_NOT_an_exclusion',input=f'data/{name}.txt',dag=f'certificates/{name}.dag',input_generators=ng,polynomial_variables=nv,module_rank=nc,verified_nodes=nodes,verified_constant_rank=0,asserted_groebner_basis=False,bytes=p.stat().st_size,sha256=digest(p)))
(ROOT/'certificates/index.json').write_text(json.dumps({'status':'partial','format':'REPORT9.2 and data/FORMATS.md','linear_algebra_certificates':[{'path':'certificates/unmatched_gamma0.npz','status':'verified two-sided inverse','matrix_shape':[84,84]},{'path':'certificates/source_C_gamma_injection.json','status':'verified left inverse','matrix_shape':[30,6]}],'certificates_and_checkpoints':entries},indent=2)+'\n')
exp=[]
for name,sec,kind,log in [('matched_chart0',180,'original remaining stratum0','matched_chart0_cpp.log'),('matched_chart0_minimal',360,'continuation of stratum0; all360 parent members retained','matched_chart0_minimal_cpp.log'),('matched_stratum1',360,'remaining stratum1','matched_stratum1_cpp.log'),('matched_stratum2',360,'remaining stratum2','matched_stratum2_cpp.log')]:
 exp.append(dict(name=name,kind=kind,command=f'.build/module_gb data/{name}.txt certificates/{name}.dag {sec}',exploration_limit_seconds=sec,status='bounded symbolic attempt stopped without full constant span',is_coefficient_field_search=False,conclusion_about_geometric_nonemptiness='none',log='logs/'+log))
(ROOT/'logs/experiments.json').write_text(json.dumps({'warning':'Unfinished symbolic computations are not empty-locus certificates and not asserted Groebner bases.','attempts':exp},indent=2)+'\n')
print('Wrote claim index, certificate/checkpoint metadata, and bounded-attempt descriptions.')
