#define USE_GMP_PACKING
#include "fast_univariate.hpp"
#include <random>
static UP remp(const UP&a,const UP&f){return ud(a,f).second;}
static UP power(UP a,uint64_t n,const UP&f){UP b={1};while(n){if(n&1)b=remp(um(a,b),f);n>>=1;if(n)a=remp(um(a,a),f);}return b;}
static std::mt19937 rng(27092029);
static std::vector<UP> equaldegree(UP f,int d){if(int(f.size())-1==d)return{f};for(int attempt=0;attempt<1000;attempt++){UP a(f.size()-1);for(U&c:a)c=rng()%QQ;UP b=power(a,(QQ-1)/2,f),h={1};for(int j=0;j<d;j++){h=remp(um(h,b),f);if(j+1<d)b=power(b,QQ,f);}UP g=ugfast(f,us(h,{1}));if(g.size()>1&&g.size()<f.size()){auto x=equaldegree(g,d),y=equaldegree(ux(f,g),d);x.insert(x.end(),y.begin(),y.end());return x;}}throw std::runtime_error("factor splitter attempts exhausted; no conclusion");}
static std::vector<UP> factors(UP f){f=uradical(f);UP original=f,h={0,1};int d=1;std::vector<UP>fac;while(2*d<=int(f.size())-1){h=power(h,QQ,f);UP g=ugfast(f,us(h,{0,1}));if(g.size()>1){auto t=equaldegree(g,d);fac.insert(fac.end(),t.begin(),t.end());f=ux(f,g);h=remp(h,f);}d++;}if(f.size()>1)fac.push_back(f);std::sort(fac.begin(),fac.end(),[](const UP&a,const UP&b){return a.size()==b.size()?a<b:a.size()<b.size();});UP p={1};for(auto&g:fac){p=um(p,g);int n=g.size()-1;UP x=remp({0,1},g),y=x;for(int j=1;j<=n;j++){y=power(y,QQ,g);if(n%j==0&&j<n&&ugfast(g,us(y,x))!=UP{1})throw std::runtime_error("factor irreducibility check failed");}if(y!=x)throw std::runtime_error("factor final Frobenius failed");}if(p!=original)throw std::runtime_error("factor product mismatch");return fac;}
int main(int argc,char**argv){try{if(argc<3){std::cerr<<"usage: factor_support output input_polynomial...\n";return 2;}initfield(nullptr);UP f={1};for(int j=2;j<argc;j++){std::ifstream i(argv[j]);int n;i>>n;UP g(n);for(U&c:g)i>>c;if(!i)throw std::runtime_error("bad polynomial file");f=um(f,g);}auto fs=factors(f);std::ofstream o(argv[1]);o<<fs.size()<<"\n";for(auto&p:fs){o<<p.size();for(U c:p)o<<" "<<c;o<<"\n";}std::cout<<"factor_product_and_irreducibility=PASS radical_degree="<<uradical(f).size()-1<<" factor_degrees=";for(auto&p:fs)std::cout<<p.size()-1<<",";std::cout<<"\n";return 0;}catch(std::exception&e){std::cerr<<e.what()<<"\n";return 1;}}
