#define USE_GMP_PACKING
#include "fast_univariate.hpp"
static UP lu(std::istream&i){int n;i>>n;UP a(n);for(U&c:a)i>>c;if(!i)throw std::runtime_error("bad polynomial input");return a;}
static void readF(std::istream&i){std::string name;int n;i>>name>>n;assert(name=="F");for(int k=0;k<n;k++){int v,s;U c;i>>v>>s>>c;if(s==6){assert(!v&&c==1);continue;}F[s].resize(std::max(F[s].size(),size_t(v+1)));F[s][v]=c;}}
static void support_check(UP d,const UP&s){UP g=ugfast(d,s);while(g.size()>1){d=ux(d,g);g=ugfast(d,um(g,g));}if(d.size()!=1)throw std::runtime_error("denominator support incomplete");}
int main(int argc,char**argv){try{if(argc!=10){std::cerr<<"usage: verify_global chart C71 C72 cert71 cert72 support chain71 chain72 unit_bezout\n";return 2;}initfield(nullptr);std::ifstream ch(argv[1]);U r;ch>>r;readF(ch);std::ifstream si(argv[6]);UP support=lu(si);std::array<UP,2>stripped;
 for(int i=0;i<2;i++){std::ifstream ta(argv[2+i]);QA p=loadq(ta);support_check(p.d,support);p.d={1};std::ifstream ce(argv[4+i]);UP N=lu(ce);QA x=loadq(ce);assert(x.d==UP{1});QA product=qraw(p,x);if(product.n[0]!=N)throw std::runtime_error("norm identity constant mismatch");for(int j=1;j<6;j++)if(!product.n[j].empty())throw std::runtime_error("norm identity S remainder");std::cout<<"tail="<<71+i<<" polynomial_identity_P_times_X_equals_N=PASS norm_degree="<<N.size()-1<<std::endl;
 std::ifstream cr(argv[7+i]);int n;cr>>n;UP prev=support;stripped[i]=N;for(int j=0;j<n;j++){UP g=lu(cr);ux(prev,g);stripped[i]=ux(stripped[i],g);prev=um(g,g);}std::cout<<"tail="<<71+i<<" all_removed_factors_supported=PASS stripped_degree="<<stripped[i].size()-1<<std::endl;}
 std::ifstream bz(argv[9]);UP g=lu(bz),u=lu(bz),v=lu(bz);if(g!=UP{1})throw std::runtime_error("nonunit target gcd");if(ua(um(u,stripped[0]),um(v,stripped[1]))!=g)throw std::runtime_error("univariate Bezout identity failure");std::cout<<"r="<<r<<" GLOBAL_COMPLEMENT_EXCLUSION=PASS; all support-zero fibers require their separate full certificates.\n";return 0;}catch(std::exception&e){std::cerr<<e.what()<<"\n";return 1;}}
