import Definitions.Deformations.TruncatedMonomialAlgebra
import Mathlib.Data.Fin.Tuple.Basic

namespace Litt3.Deformations

variable (R : Type*) [CommRing R]

/-- The literal rank-one remainder ideal generated by y³, yz, and z²
in the unchanged unequal-power base quotient. -/
noncomputable def rankOneQuadraticRemainderIdeal (Q T : ℕ) :
    Ideal (TruncatedMonomialAlgebra R (Fin 2) ![Q, T]) :=
  Ideal.span ({truncatedMonomialParameter R (Fin 2) ![Q, T] 0 ^ 3,
    truncatedMonomialParameter R (Fin 2) ![Q, T] 0 *
      truncatedMonomialParameter R (Fin 2) ![Q, T] 1,
    truncatedMonomialParameter R (Fin 2) ![Q, T] 1 ^ 2} :
      Set (TruncatedMonomialAlgebra R (Fin 2) ![Q, T]))

end Litt3.Deformations
