import Mathlib.RingTheory.MvPolynomial.Ideal
import Mathlib.RingTheory.MvPolynomial.Basic
import Mathlib.RingTheory.Ideal.Quotient.Operations

namespace Litt3.Deformations

variable (R I : Type*) [CommRing R]

/-- The literal original variable-power ideal, allowing different
truncation exponents at every original coordinate. -/
noncomputable def truncatedMonomialIdeal (q : I → ℕ) : Ideal (MvPolynomial I R) :=
  Ideal.span ((fun a : I →₀ ℕ => MvPolynomial.monomial a (1 : R)) ''
    Set.range (fun i => Finsupp.single i (q i)))

/-- The actual original polynomial quotient with unequal variable powers. -/
abbrev TruncatedMonomialAlgebra (q : I → ℕ) := MvPolynomial I R ⧸ truncatedMonomialIdeal R I q

/-- Exactly the original exponents removed by the actual variable-power
relations. No basis or length conclusion is included in this definition. -/
def oversizedMonomialExponents (q : I → ℕ) : Set (I →₀ ℕ) :=
  {a | ∃ i, q i ≤ a i}

/-- The unchanged actual variable class in the unequal-power quotient. -/
noncomputable def truncatedMonomialParameter (q : I → ℕ) (i : I) :
    TruncatedMonomialAlgebra R I q :=
  Ideal.Quotient.mk (truncatedMonomialIdeal R I q) (MvPolynomial.X i)

/-- The actual ideal generated by all unchanged variable classes. -/
noncomputable def truncatedMonomialAugmentationIdeal (q : I → ℕ) :
    Ideal (TruncatedMonomialAlgebra R I q) :=
  Ideal.span (Set.range (truncatedMonomialParameter R I q))

end Litt3.Deformations
