import Mathlib.LinearAlgebra.Span.Defs
import Mathlib.Algebra.Algebra.Basic
import Mathlib.Algebra.BigOperators.Group.Finset.Defs

namespace Litt3.Deformations

open scoped BigOperators

variable {R A I : Type*} [CommRing R] [CommRing A] [Algebra R A] [Fintype I]

/-- Actual unrestricted augmentation monomials, before replacing
high powers by any original group relation. -/
noncomputable def generatorMonomial (e : I → A) (alpha : I → ℕ) : A :=
  ∏ i, e i ^ alpha i

noncomputable def generatorMonomialWeight (alpha : I → ℕ) : ℕ := ∑ i, alpha i

/-- The genuine weighted submodule generated by prime powers and
original augmentation monomials. All coefficients are retained. -/
noncomputable def weightedGeneratorFiltration (R : Type*) [CommRing R]
    {A I : Type*} [CommRing A] [Algebra R A] [Fintype I]
    (p : A) (primeWeight : ℕ) (e : I → A) (d : ℕ) : Submodule R A :=
  Submodule.span R {x | ∃ j : ℕ, ∃ alpha : I → ℕ,
    d ≤ primeWeight * j + generatorMonomialWeight alpha ∧
      x = p ^ j * generatorMonomial e alpha}

end Litt3.Deformations
