#!/usr/bin/env python3
"""Assemble the compact proved marked-lattice result, without replaying it."""
from pathlib import Path
import hashlib,json,re,zipfile

ROOT=Path(__file__).resolve().parents[2]
BASE=ROOT.parent/'litt3-computation-data/conceptual_continuation_20260929'
OUT=BASE/'marked_divisor_lattice_complete.zip'
sources=[
 'marked_jacobian_relation_probe_20260929.py',
 'marked_jacobian_small_primary_20260929.py',
 'marked_jacobian_exact_kernel_20260929.py',
 'marked_lattice_shortest_effective_20260929.py',
 'marked_minimal_divisor_check_20260929.py',
 'marked_relation_generator_check_20260929.py',
 'marked_principal_lattice_certificate_20260929.py',
]
receipts=[
 'marked_jacobian_order/receipt.json',
 'marked_jacobian_small_primary/small_primary.json',
 'marked_jacobian_exact_kernel.json',
 'marked_exact_effective_minimum.json','marked_exact_signed_minimum.json',
 'marked_minimal_divisor_check/receipt.json',
 'marked_relation_ideal_generators.json',
 'marked_relation_generator_check/receipt.json',
 'marked_principal_lattice_certificate.json',
 'marked_minimum_phase_packet.json',
]
audits=[
 'MARKED_RELATION_LATTICE_2026_09_29.md',
 'MARKED_PRIMARY_KERNEL_AND_EFFECTIVE_GAUGE_2026_09_29.md',
 'MARKED_SIGNED_SUPPORT_GAUGE_2026_09_29.md',
 'MARKED_PRINCIPAL_RELATION_IDEAL_2026_09_29.md',
]
evidence=json.loads((BASE/'marked_lattice_evidence.json').read_text())
for f in receipts:evidence['receipts'][f]=hashlib.sha256((BASE/f).read_bytes()).hexdigest()
for f in sources:
 p=ROOT/'scripts/arithmetic'/f
 evidence['source']['scripts/arithmetic/'+f]=hashlib.sha256(p.read_bytes()).hexdigest()
evidence['claims']['principal_generator']=[-652173,104828,-133365,8040,4980,-494720,-65556,30252]
evidence['claims']['full_kernel_is_principal_ideal']=True
evidence['claims']['assumed_weil_polynomial']=False
evidence['claims']['modular_phase_relaxation_minimum']=1617894
evidence['checks']=[v for v in evidence['checks'] if v['algorithm'] not in [
 'actual Jacobian principal-generator Horner identity',
 'principal ideal matching lower and upper indices without Weil polynomial']]
evidence['checks'] += [
 {'algorithm':'actual Jacobian principal-generator Horner identity','outcome':'PASS','seconds':62.73},
 {'algorithm':'principal ideal matching lower and upper indices without Weil polynomial','outcome':'PASS'},
]
for command in [
 'sage -python scripts/arithmetic/marked_relation_generator_check_20260929.py BASE/marked_relation_ideal_generators.json BASE/marked_relation_generator_check/receipt.json',
 'sage -python scripts/arithmetic/marked_principal_lattice_certificate_20260929.py BASE BASE/marked_principal_lattice_certificate.json',
]:
 if command not in evidence['commands']:evidence['commands'].append(command)
evidence['generator_source_revision_note']='After its successful run, the unused precondition checking the old lattice-equality input flag was removed. Group operations and the zero test are unchanged; no numerical replay was needed.'
(BASE/'marked_lattice_evidence.json').write_text(json.dumps(evidence,indent=2)+'\n')

files={}
def add(name,path):files[name]=Path(path).read_bytes()
def md(name,path):
 text=Path(path).read_text()
 # Flatten project links for a self-contained report; source and data
 # are mapped in README and claims.json, with no external proof inputs.
 text=re.sub(r'\[([^\]]+)\]\([^\n]*\)',r'\1',text)
 files[name]=text.encode()
md('STATEMENT.md',ROOT/'Theorems/cartier_and_spin/marked_divisor_relation_lattice.md')
md('PROOF.md',ROOT/'Proofs/cartier_and_spin/marked_divisor_relation_lattice.md')
md('PHASE_RELAXATION.md',ROOT/'Proofs/cartier_and_spin/modular_norm_relaxation_nonempty.md')
for f in sources:add('scripts/'+f,ROOT/'scripts/arithmetic'/f)
for f in receipts:add('data/'+f,BASE/f)
for f in audits:md('audits/'+f,ROOT/'Research/audits'/f)
add('data/evidence.json',BASE/'marked_lattice_evidence.json')
add('executed_sources/marked_jacobian_relation_probe_20260929.py',BASE/'executed_sources/marked_jacobian_relation_probe_20260929.py')
generator=(ROOT/'scripts/arithmetic/marked_relation_generator_check_20260929.py').read_text()
files['executed_sources/marked_relation_generator_check_20260929.py']=generator.replace(
 "assert len(input_record['generators'])==1",
 "assert input_record['orbit_lattice_equals_full_I'] and len(input_record['generators'])==1").encode()
files['README.md']=b'''# Complete marked-divisor lattice and exact thresholds

Status: complete for the thirteen-point supported-divisor problem.
The unmarked common-cover problem is unresolved. No actual two-map
realization is claimed. STATEMENT.md fixes the curve, finite-field
coding and every marking. PROOF.md gives the complete argument.

The relation ideal is generated by one eight-coefficient polynomial.
Its direct Jacobian check and matching indices avoid assuming a Weil
polynomial. The first nonpolynomial effective pole is1617894. The first
degree outside k(x), allowing all marked poles, is788052. The former
minimum already admits the modulo-five phase-count relaxation.

Requirements: Sage10.9 (used with Python3.14) for Jacobian/integer
checks; standard Python3 for exact rational sphere enumeration.
All paths below are relative to this unpacked directory.

Fast verification using the supplied actual-group receipts:

    sage -python scripts/marked_principal_lattice_certificate_20260929.py data /tmp/marked-principal.json
    python3 scripts/marked_lattice_shortest_effective_20260929.py data/marked_jacobian_exact_kernel.json /tmp/marked-effective.json
    python3 scripts/marked_lattice_shortest_effective_20260929.py data/marked_jacobian_exact_kernel.json /tmp/marked-signed.json --signed

To recompute the underlying actual-group facts in a new output tree:

    mkdir -p replay/marked_relation_generator_check replay/marked_minimal_divisor_check
    sage -python scripts/marked_jacobian_relation_probe_20260929.py replay/marked_jacobian_order --point-order
    sage -python scripts/marked_jacobian_small_primary_20260929.py replay/marked_jacobian_small_primary
    sage -python scripts/marked_relation_generator_check_20260929.py data/marked_relation_ideal_generators.json replay/marked_relation_generator_check/receipt.json
    sage -python scripts/marked_minimal_divisor_check_20260929.py data/marked_exact_effective_minimum.json replay/marked_minimal_divisor_check/receipt.json
    cp data/marked_jacobian_exact_kernel.json replay/
    sage -python scripts/marked_principal_lattice_certificate_20260929.py replay /tmp/marked-replayed-principal.json

The copied lattice is not assumed correct: the final verifier proves
its equality with the directly checked principal ideal by integer row
operations and matching lower/upper indices. The older assembler is
retained for provenance; its Weil polynomial is not a proof assumption.
No large polynomial representing a million-degree function is needed:
the zero class of its exact effective divisor proves existence.

data/evidence.json records executed checks and source hashes. The
executed_sources folder preserves the two versions changed only in
console text or an unused input precondition after successful runs.
Audits are focused proof/source reviews, not second numerical replays.
The earliest audit contains a conditional ten-prime bound subsequently
shown inapplicable; only the final exact theorem is asserted here.

claims.json maps the statements to minimal evidence. SHA256SUMS hashes
every file except itself. No external files or input archive are needed.
'''
claims={
 'status':'complete marked-support classification; common-cover problem unresolved',
 'exact_point_order':['scripts/marked_jacobian_relation_probe_20260929.py','data/marked_jacobian_order/receipt.json'],
 'small_primary_lower_bounds':['scripts/marked_jacobian_small_primary_20260929.py','data/marked_jacobian_small_primary/small_primary.json'],
 'principal_ideal':['PROOF.md','scripts/marked_relation_generator_check_20260929.py','data/marked_relation_generator_check/receipt.json','scripts/marked_principal_lattice_certificate_20260929.py','data/marked_principal_lattice_certificate.json'],
 'exact_minima':['scripts/marked_lattice_shortest_effective_20260929.py','data/marked_exact_effective_minimum.json','data/marked_exact_signed_minimum.json'],
 'direct_effective_minimizer':['scripts/marked_minimal_divisor_check_20260929.py','data/marked_minimal_divisor_check/receipt.json'],
 'phase_relaxation':['PHASE_RELAXATION.md','data/marked_minimum_phase_packet.json'],
 'not_proved':['unrestricted actual norm invariance','invariant actual comparison exclusion','shared-object extraction','unmarked common-cover decision'],
}
files['claims.json']=(json.dumps(claims,indent=2)+'\n').encode()
files['SHA256SUMS']=(''.join(hashlib.sha256(b).hexdigest()+'  '+n+'\n' for n,b in sorted(files.items()))).encode()
with zipfile.ZipFile(OUT,'w',zipfile.ZIP_DEFLATED,compresslevel=9)as z:
 for n,b in sorted(files.items()):z.writestr(n,b)
with zipfile.ZipFile(OUT)as z:assert z.testzip() is None
print(json.dumps({'archive':str(OUT),'compressed_bytes':OUT.stat().st_size,
 'uncompressed_bytes':sum(map(len,files.values())),'files':len(files),
 'sha256':hashlib.sha256(OUT.read_bytes()).hexdigest()},indent=2))
