#!/usr/bin/env python3
"""Encode the H-row module in a square-zero ideal, preserving membership.

The ideal is generated by row_i(H).v and every v_i*v_j. It contains
every v_i exactly when the H-row module is full. Its radical ALWAYS
contains the v_i, so radical, support or point tests cannot be used.
"""
import argparse
import hashlib
import json
from pathlib import Path

import numpy as np
from sage.all import GF, PolynomialRing


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("tensor",type=Path)
    ap.add_argument("--source-stratum",type=int,choices=range(9),required=True)
    ap.add_argument("--output",type=Path,required=True)
    args = ap.parse_args()
    H = np.load(args.tensor,allow_pickle=False)["H"]
    assert H.shape==(30,15,10)
    k=GF(25,"a",modulus=PolynomialRing(GF(5),"w")([2,4,1]))
    dec=lambda c:k(int(c)%5)+k(int(c)//5)*k.gen()
    j=args.source_stratum
    names=[f"b{i}" for i in range(j+1,10)]+[f"v{i}" for i in range(15)]
    R=PolynomialRing(k,names,order="degrevlex")
    b=[R.zero() if i<j else R.one() if i==j else R(f"b{i}") for i in range(10)]
    v=[R(f"v{i}") for i in range(15)]
    equations=[sum(dec(H[r,c,s])*b[s]*v[c] for c in range(15) for s in range(10)) for r in range(30)]
    equations.extend(v[i]*v[h] for i in range(15) for h in range(i,15))
    out={"status":"PREPARED","variables":names,"equations":[str(f) for f in equations],
         "source_stratum":j,"input_sha256":hashlib.sha256(args.tensor.read_bytes()).hexdigest(),
         "scope":"Ordinary nonradical ideal-membership encoding of the entire H-row module on the normalized geometric source stratum.",
         "decision":"Full row module iff every v0,...,v14 belongs to this exact ideal.",
         "warning":"The reduced geometric support v=0 occurs regardless of module rank. Do not compute the radical or substitute a point search."}
    args.output.write_text(json.dumps(out,separators=(",",":"))+"\n")
    print("PREPARED",len(names),len(equations),flush=True)


if __name__=="__main__":
    main()
