// Exact Lee-weight <=7 relations among xi^j and mu*xi^j over F5.
// Meet in the middle: a radius-three ball against a radius-four ball.
// Arithmetic data are generated by sextic_paired_endpoint_data.py.
#include <array>
#include <cassert>
#include <cstdint>
#include <functional>
#include <iostream>
#include <unordered_map>
#include <unordered_set>
#include "sextic_paired_data.hpp"
using Vec=std::array<uint8_t,7>;
using Word=std::array<uint8_t,58>;
int lee(int x){return x<=2?x:5-x;}
uint64_t pack(const Vec&v){uint64_t key=0,p=1;for(int x:v){key+=p*x;p*=25;}return key;}
uint64_t wordcode(const Word&w){uint64_t code=0;int shift=0;for(int i=0;i<58;++i)if(w[i]){code|=uint64_t(1+i+64*(w[i]-1))<<shift;shift+=8;}return code;}
Word decode(uint64_t x){Word w{};while(x){unsigned a=x&255;x>>=8;assert(a);w[(a-1)%64]=1+(a-1)/64;}return w;}
int main(){
 for(int mu:{5,6,7,11}){
  std::array<std::array<Vec,5>,58> cols;
  for(int j=0;j<58;++j)for(int a=1;a<5;++a)for(int k=0;k<7;++k)
   cols[j][a][k]=mul25[a][mul25[j<29?1:mu][phase[j%29][k]]];
  std::unordered_map<uint64_t,uint64_t> small;small.reserve(350000);
  Word w{};uint64_t smallcount=0,largecount=0,collisions=0;int minimum=8;
  std::unordered_set<uint64_t> relations;
  auto walk=[&](int radius, auto inspect){
   std::function<void(int,int,Vec)> rec=[&](int first,int left,Vec v){
    inspect(v);
    for(int j=first;j<58;++j)for(int a=1;a<5;++a)if(lee(a)<=left){
     Vec v1;for(int k=0;k<7;++k)v1[k]=add25[v[k]][cols[j][a][k]];
     w[j]=a;rec(j+1,left-lee(a),v1);w[j]=0;
    }
   };rec(0,radius,Vec{});
  };
  walk(3,[&](const Vec&v){++smallcount;auto z=small.emplace(pack(v),wordcode(w));assert(z.second);});
  walk(4,[&](const Vec&v){
   ++largecount;auto it=small.find(pack(v));if(it==small.end())return;
   auto old=decode(it->second);Word diff{};int weight=0;
   for(int j=0;j<58;++j){diff[j]=(w[j]+5-old[j])%5;weight+=lee(diff[j]);}
   if(!weight)return;++collisions;minimum=std::min(minimum,weight);
   assert(weight==7);
   // A hash of the literal relation; retain the first witnesses, not every collision.
   uint64_t hash=1469598103934665603ULL;
   for(int j=0;j<58;++j){hash^=diff[j];hash*=1099511628211ULL;}
   if(relations.insert(hash).second && relations.size()<=20){
    std::cout<<"RELATION mu "<<mu<<" weight "<<weight;
    for(int j=0;j<58;++j)if(diff[j])std::cout<<' '<<j<<':'<<int(diff[j]);
    std::cout<<'\n';
   }
  });
  std::cout<<"MU "<<mu<<" BALL3 "<<smallcount<<" BALL4 "<<largecount
   <<" COLLISIONS "<<collisions<<" DISTINCT_RELATION_HASHES "<<relations.size()
   <<" MINIMUM "<<minimum<<std::endl;
 }
}
