// Exact necessary trace matching for paired sextic endpoints and epsilon in F625.
// Input header is generated by sextic_paired_endpoint_data.py.
#include <array>
#include <vector>
#include <algorithm>
#include <cassert>
#include <cstdint>
#include <iostream>
#include <fstream>
#include "sextic_paired_data.hpp"
using E2=std::array<int,2>;
using S=std::array<int,42>;
E2 eps;
bool first_equation=false;
int ffadd(int a,int b){return add25[a][b];}
E2 scale(E2 a,int b){return {mul25[a[0]][b],mul25[a[1]][b]};}
E2 times(E2 a,E2 b){return {ffadd(mul25[a[0]][b[0]],mul25[9][mul25[a[1]][b[1]]]),ffadd(mul25[a[0]][b[1]],mul25[a[1]][b[0]])};}
void term(S&v,int block,E2 c,int exponent){
 exponent=(exponent%29+29)%29;
 for(int i=0;i<2;++i)for(int j=0;j<7;++j){int k=block*14+i*7+j;v[k]=ffadd(v[k],mul25[c[i]][phase[exponent][j]]);}
}
S syndrome(int side,int label){
 int j=label/2,p=label%2;E2 C,E,U,V;
 for(int i=0;i<2;++i){C[i]=pair_values[0][p][i];E[i]=pair_values[1][p][i];U[i]=pair_values[2][p][i];V[i]=pair_values[3][p][i];}
 E2 W=side?scale(first_equation?C:E,neg25[inv25[22]]):scale(times(eps,first_equation?E:C),inv25[22]);
 int y=mul25[W[1]][inv25[eps[1]]],x=ffadd(neg25[W[0]],mul25[eps[0]][y]);
 // Check W=epsilon*y-x before eliminating the common moments.
 assert(W[0]==ffadd(mul25[eps[0]][y],neg25[x])&&W[1]==mul25[eps[1]][y]);
 S r{};
 if(!side){term(r,0,times(eps,first_equation?C:E),(first_equation?5:8)*j);term(r,1,times(eps,U),17*j);term(r,1,V,4*j);}
 else{term(r,0,scale(first_equation?E:C,4),(first_equation?8:5)*j);term(r,2,U,17*j);term(r,2,times(eps,V),4*j);}
 int k=side?8*j:5*j;
 if(first_equation){k=side?5*j:8*j;int old=x;x=frob25[y];y=frob25[old];k=-k;}
 if(!first_equation){term(r,0,scale(eps,neg25[mul25[22][frob25[x]]]),-k);term(r,0,{mul25[22][frob25[y]],0},-k);}
 else{term(r,0,scale(eps,neg25[mul25[22][y]]),k);term(r,0,{mul25[22][x],0},k);}
 term(r,1,scale(eps,neg25[mul25[22][x]]),16*k);
 term(r,1,{mul25[22][y],0},24*k);
 term(r,2,{neg25[mul25[22][frob25[x]]],0},13*k);
 term(r,2,scale(eps,mul25[22][frob25[y]]),5*k);
 return r;
}
int projection[20][84];uint16_t sum625[625][625];
uint64_t hash(const S&v){
 uint64_t r=0;
 for(int block=0;block<5;++block){int chunk=0,power=1;
  for(int j=0;j<4;++j){int w=0;for(int i=0;i<42;++i)w+=projection[block*4+j][2*i]*(v[i]%5)+projection[block*4+j][2*i+1]*(v[i]/5);
   chunk+=power*(w%5);power*=5;
  }r|=uint64_t(chunk)<<(10*block);
 }return r;
}
uint64_t hashadd(uint64_t a,uint64_t b){uint64_t r=0;for(int j=0;j<5;++j)r|=uint64_t(sum625[(a>>(10*j))&1023][(b>>(10*j))&1023])<<(10*j);return r;}
struct Entry{uint64_t hash;int a,b,c;bool operator<(const Entry&r)const{return hash<r.hash;}};
std::vector<Entry> triples(const std::array<S,58>&v,bool negative){
 std::array<uint64_t,58> hashes;
 for(int i=0;i<58;++i){S x=v[i];if(negative)for(int&c:x)c=neg25[c];hashes[i]=hash(x);}
 std::vector<Entry> r;r.reserve(34220);
 for(int a=0;a<58;++a)for(int b=a;b<58;++b){auto h=hashadd(hashes[a],hashes[b]);for(int c=b;c<58;++c)r.push_back({hashadd(h,hashes[c]),a,b,c});}
 assert(r.size()==34220);std::sort(r.begin(),r.end());return r;
}
bool exact(const Entry&a,const Entry&b,const std::array<S,58>&v,const std::array<S,58>&w){
 for(int i=0;i<42;++i){int s=0;for(int t:{a.a,a.b,a.c})s=ffadd(s,v[t][i]);for(int t:{b.a,b.b,b.c})s=ffadd(s,w[t][i]);if(s)return false;}return true;
}
int main(int argc,char**argv){
 std::ofstream dump;
 for(int i=1;i<argc;++i){if(std::string(argv[i])=="--solve-first")first_equation=true;else dump.open(argv[i],std::ios::binary);}
 uint32_t state=first_equation?0x62e19234:0x5e271403;
 for(auto&r:projection)for(int&x:r){state=1664525U*state+1013904223U;x=state%5;}
 for(int a=0;a<625;++a)for(int b=0;b<625;++b){int x=a,y=b,z=0,p=1;for(int i=0;i<4;++i){z+=p*((x%5+y%5)%5);p*=5;x/=5;y/=5;}sum625[a][b]=z;}
 uint64_t total=0,exact_total=0;int scalars=0,nonempty=0;
 for(int a=0;a<25;++a)for(int b=1;b<25;++b){eps={a,b};++scalars;
  std::array<S,58> v,w;for(int i=0;i<58;++i){v[i]=syndrome(0,i);w[i]=syndrome(1,i);}
  if(dump)for(const auto*table:{&v,&w})for(const auto&row:*table)for(int c:row)dump.put(char(c));
  auto left=triples(v,false),right=triples(w,true);size_t i=0,j=0;uint64_t matches=0;
  while(i<left.size()&&j<right.size()){
   if(left[i].hash<right[j].hash){++i;continue;}if(right[j].hash<left[i].hash){++j;continue;}
   size_t ii=i+1,jj=j+1;while(ii<left.size()&&left[ii].hash==left[i].hash)++ii;while(jj<right.size()&&right[jj].hash==right[j].hash)++jj;
   for(size_t p=i;p<ii;++p)for(size_t q=j;q<jj;++q){++total;if(exact(left[p],right[q],v,w)){++matches;++exact_total;
    if(matches<=4)std::cout<<"MATCH epsilon "<<a<<' '<<b<<" zero "<<left[p].a<<' '<<left[p].b<<' '<<left[p].c<<" infinity "<<right[q].a<<' '<<right[q].b<<' '<<right[q].c<<'\n';
   }}i=ii;j=jj;
  }
  if(matches){++nonempty;std::cout<<"NONEMPTY "<<a<<' '<<b<<" count "<<matches<<'\n';}
  if(scalars%25==0)std::cout<<"CHECKED "<<scalars<<" hash_matches "<<total<<" exact_matches "<<exact_total<<std::endl;
 }
 assert(scalars==600);std::cout<<"COMPLETE scalars "<<scalars<<" each_side_triples 34220 hash_matches "<<total<<" exact_matches "<<exact_total<<" nonempty_scalars "<<nonempty<<std::endl;
}
