"""Exact rank factorization of the universal first-two-equation minor.
Independent symbolic expansion and verification are in verify_factorization.py.
This factorization uses only standard-library arithmetic and retained terms.
"""
import sys,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
sys.path[:0]=[str(ROOT/'structural/src')]
from polynomial_core import ADD,MUL,INV,NEG
p=json.load(open(ROOT/'full/evidence/residual_expansion.json'))
qs=sorted(set(tuple(m[:14])for m,c in p['terms']));hs=sorted(set(tuple(m[14:])for m,c in p['terms']));qi={m:i for i,m in enumerate(qs)};hi={m:i for i,m in enumerate(hs)}
M=[[0]*len(hs)for _ in qs]
for m,c in p['terms']:M[qi[tuple(m[:14])]][hi[tuple(m[14:])]]=c
A=[r[:]for r in M];rank=0;piv=[]
for j in range(len(hs)):
 k=next((k for k in range(rank,len(qs))if A[k][j]),None)
 if k is None:continue
 A[k],A[rank]=A[rank],A[k];iv=INV[A[rank][j]];A[rank]=[MUL[x][iv]for x in A[rank]]
 for i in range(len(qs)):
  if i!=rank and A[i][j]:
   x=A[i][j];A[i]=[ADD[t][NEG[MUL[x][y]]]for t,y in zip(A[i],A[rank])]
 piv.append(j);rank+=1
U=[[r[j]for j in piv]for r in M];V=A[:rank]
for i in range(len(qs)):
 for j in range(len(hs)):
  x=0
  for k in range(rank):x=ADD[x][MUL[U[i][k]][V[k][j]]]
  assert x==M[i][j]
# Each factor is homogeneous for independent phase/type transformations.
wH=[5]*4+[8]*3+[-5]*4+[-8]*3;tH=[0,1,2,3,0,1,2]*2
weights=[]
for row in V:
 ww={(sum(x*y for x,y in zip(m,wH))%29,sum(x*y for x,y in zip(m,tH))%4)for m,c in zip(hs,row)if c}
 assert len(ww)==1
 weights.append(list(ww.pop()))
data={'rank':rank,'Q_monomials':[list(m)for m in qs],'H_monomials':[list(m)for m in hs], 'Q_features':[[[i,U[i][k]]for i in range(len(qs))if U[i][k]]for k in range(rank)],'H_features':[[[j,c]for j,c in enumerate(row)if c]for row in V],'H_weights':weights}
(ROOT/'full/evidence/residual_factorization.json').write_text(json.dumps(data,sort_keys=True,separators=(',',':'))+'\n')
# Standalone exact C++ data; generated, not handwritten.
text=['#pragma once','// Generated by factor_residual.py; coefficients are F25 codes.','namespace factors {',f'constexpr int rank={rank}, monoms={len(qs)};']
for name,matrix in [('QM',qs),('HM',hs)]:
 text.append(f'constexpr unsigned char {name}[{len(matrix)}][14]={{'+','.join('{'+','.join(map(str,r))+'}'for r in matrix)+'};')
for name,matrix in [('QC',[[U[i][k]for i in range(len(qs))]for k in range(rank)]),('HC',V),('HW',weights)]:
 text.append(f'constexpr unsigned char {name}[{len(matrix)}][{len(matrix[0])}]={{'+','.join('{'+','.join(map(str,r))+'}'for r in matrix)+'};')
text+=['}'];(ROOT/'full/src/factor_data.hpp').write_text('\n'.join(text)+'\n')
print(json.dumps({'status':'PASS','rank':rank,'original_terms':len(p['terms']),'Q_monomials':len(qs),'H_monomials':len(hs),'Q_feature_terms':sum(bool(c)for row in U for c in row),'H_feature_terms':sum(bool(c)for row in V for c in row),'all_coefficient_products_verified':True}))
