

# This file was *autogenerated* from the file routes/global/53_X_AUTOMORPHISM_CERTIFICATE.sage
from sage.all_cmdline import *   # import sage library

_sage_const_5 = Integer(5); _sage_const_7 = Integer(7); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_0 = Integer(0); _sage_const_8 = Integer(8); _sage_const_30 = Integer(30); _sage_const_134 = Integer(134); _sage_const_6 = Integer(6); _sage_const_4 = Integer(4); _sage_const_20 = Integer(20); _sage_const_50 = Integer(50); _sage_const_125 = Integer(125); _sage_const_25 = Integer(25)# Exact certificate for Lemma 53.1.
# Run with: sage routes/global/53_X_AUTOMORPHISM_CERTIFICATE.sage

F5 = GF(_sage_const_5 )
R5 = PolynomialRing(F5, names=('x',)); (x,) = R5._first_ngens(1)
f = x**_sage_const_7  - x + _sage_const_1 

# The first three point counts determine the genus-three Weil polynomial.
counts = []
for n in [_sage_const_1 , _sage_const_2 , _sage_const_3 ]:
    Kn = GF(_sage_const_5 **n, name='a')
    count = _sage_const_1   # the point at infinity
    for xx in Kn:
        value = xx**_sage_const_7  - xx + _sage_const_1 
        count += _sage_const_1  if value == _sage_const_0  else (_sage_const_2  if value.is_square() else _sage_const_0 )
    counts.append(count)

assert counts == [_sage_const_8 , _sage_const_30 , _sage_const_134 ]
RT = PolynomialRing(ZZ, names=('T',)); (T,) = RT._first_ngens(1)
weil = T**_sage_const_6  + _sage_const_2 *T**_sage_const_5  + _sage_const_4 *T**_sage_const_4  + _sage_const_8 *T**_sage_const_3  + _sage_const_20 *T**_sage_const_2  + _sage_const_50 *T + _sage_const_125 
power_sums = [_sage_const_5 **n + _sage_const_1  - counts[n - _sage_const_1 ] for n in [_sage_const_1 , _sage_const_2 , _sage_const_3 ]]
assert power_sums == [-_sage_const_2 , -_sage_const_4 , -_sage_const_8 ]
c1 = -power_sums[_sage_const_0 ]
c2 = -(power_sums[_sage_const_1 ] + c1*power_sums[_sage_const_0 ])/_sage_const_2 
c3 = -(power_sums[_sage_const_2 ] + c1*power_sums[_sage_const_1 ] + c2*power_sums[_sage_const_0 ])/_sage_const_3 
reconstructed = T**_sage_const_6  + c1*T**_sage_const_5  + c2*T**_sage_const_4  + c3*T**_sage_const_3                  + _sage_const_5 *c2*T**_sage_const_2  + _sage_const_25 *c1*T + _sage_const_125 
assert weil == reconstructed
assert weil == (T**_sage_const_2  - _sage_const_3 *T + _sage_const_5 )*(T**_sage_const_2  + T + _sage_const_5 )*(T**_sage_const_2  + _sage_const_4 *T + _sage_const_5 )

# The branch polynomial has one linear and one irreducible degree-six factor,
# so all eight branch points are rational over its degree-six splitting field.
assert sorted(g.degree() for g, multiplicity in f.factor()) == [_sage_const_1 , _sage_const_6 ]
K = f.splitting_field(names=('a',)); (a,) = K._first_ngens(1)
RK = PolynomialRing(K, names=('X',)); (X,) = RK._first_ngens(1)
roots = [root for root, multiplicity in RK(f).roots()]
points = [vector(K, [root, _sage_const_1 ]) for root in roots]
points.append(vector(K, [_sage_const_1 , _sage_const_0 ]))  # infinity
assert len(points) == _sage_const_8 

def projective_key(point):
    if point[_sage_const_0 ] == _sage_const_0 :
        return (K(_sage_const_0 ), K(_sage_const_1 ))
    return (K(_sage_const_1 ), point[_sage_const_1 ]/point[_sage_const_0 ])

def normalized(matrix_value):
    first = next(entry for entry in matrix_value.list() if entry != _sage_const_0 )
    return first**(-_sage_const_1 )*matrix_value

def map_three_points(source, target):
    rows = []
    for source_point, target_point in zip(source, target):
        px, py = source_point
        qx, qy = target_point
        rows.append([qy*px, qy*py, -qx*px, -qx*py])
    kernel = matrix(K, rows).right_kernel()
    if kernel.dimension() != _sage_const_1 :
        return None
    candidate = matrix(K, _sage_const_2 , _sage_const_2 , kernel.basis()[_sage_const_0 ])
    return candidate if candidate.det() != _sage_const_0  else None

branch_set = set(projective_key(point) for point in points)
source_triple = points[:_sage_const_3 ]
stabilizer = {}

from itertools import permutations
for image_indices in permutations(range(_sage_const_8 ), int(_sage_const_3 )):
    target_triple = [points[index] for index in image_indices]
    candidate = map_three_points(source_triple, target_triple)
    if candidate is None:
        continue
    image_set = set(projective_key(candidate*point) for point in points)
    if image_set == branch_set:
        candidate = normalized(candidate)
        stabilizer[tuple(candidate.list())] = candidate

assert len(stabilizer) == _sage_const_1 
assert next(iter(stabilizer.values())) == identity_matrix(K, _sage_const_2 )
print("PASS: Weil polynomial factored and reduced branch stabilizer is trivial")

