"""
Exact finite search for the degree-45 families-preserving endpoint.

For every F_125-isomorphism class of elliptic curves E, every nonzero
T in E(F_125)[28], and every possible high point P != O, the divisor

    (P+T) + (O) - (P) - (T)

determines a degree-two function A_P up to a scalar.  Only the class of
that scalar modulo mu_31 matters for the equation A_P^31 = 1, so there
are four possible level sets.  A degree-45 pair from file 57 would give
two distinct P's whose corresponding level sets meet in at least 44
points.  This script computes the largest such intersection exactly.

It deliberately tests only the necessary 44-point condition.  Therefore
an output below 44 is a certificate of nonexistence; an output at least
44 would merely leave candidates for the full ramification test.
"""


# This file was *autogenerated* from the file routes/global/57_DEGREE45_F125_GRID_SEARCH.sage
from sage.all_cmdline import *   # import sage library

_sage_const_5 = Integer(5); _sage_const_3 = Integer(3); _sage_const_31 = Integer(31); _sage_const_4 = Integer(4); _sage_const_1728 = Integer(1728); _sage_const_0 = Integer(0); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_252 = Integer(252); _sage_const_28 = Integer(28); _sage_const_20 = Integer(20); _sage_const_186 = Integer(186); _sage_const_1256 = Integer(1256); _sage_const_9580970 = Integer(9580970); _sage_const_32 = Integer(32); _sage_const_9 = Integer(9)
K = GF(_sage_const_5 **_sage_const_3 , names=('z',)); (z,) = K._first_ngens(1)
primitive = K.multiplicative_generator()
eta = primitive**_sage_const_31 
quartic_label = {eta**e: e for e in range(_sage_const_4 )}


def elliptic_curve_representatives():
    """One representative of every F_125-isomorphism class (char != 2,3)."""
    curves = []
    j1728 = K(_sage_const_1728 )

    # For j not 0 or 1728 there are the curve and its quadratic twist.
    # The displayed coefficients give the prescribed j-invariant.
    for j in K:
        if j == _sage_const_0  or j == j1728:
            continue
        den = j1728 - j
        a = _sage_const_3 *j/den
        b = _sage_const_2 *j/den
        curves.append(EllipticCurve(K, [a, b]))
        curves.append(EllipticCurve(K,
                                    [primitive**_sage_const_2 *a, primitive**_sage_const_3 *b]))

    # At j=0, twists are indexed by K^*/(K^*)^6, of order gcd(6,124)=2.
    curves.append(EllipticCurve(K, [_sage_const_0 , _sage_const_1 ]))
    curves.append(EllipticCurve(K, [_sage_const_0 , primitive]))

    # At j=1728, twists are indexed by K^*/(K^*)^4, of order four.
    for e in range(_sage_const_4 ):
        curves.append(EllipticCurve(K, [primitive**e, _sage_const_0 ]))

    assert len(curves) == _sage_const_252 
    return curves


def cross_ratio_value(E, P, T, R):
    r"""Value at R of a function with divisor (P+T)+(O)-(P)-(T).

    The function is the reciprocal of the usual Miller line function
    g_{P,T}.  Return None at a zero or pole; such a point never lies over
    mu_31.  The second formula handles the removable 0/0 at -(P+T).
    """
    O = E(_sage_const_0 )
    S = P + T
    if R == O or R == S or R == P or R == T:
        return None

    xP, yP = P[_sage_const_0 ], P[_sage_const_1 ]
    xT, yT = T[_sage_const_0 ], T[_sage_const_1 ]
    xR, yR = R[_sage_const_0 ], R[_sage_const_1 ]

    if S == O:
        # Here T=-P and g_{P,T}=x-x(P).
        return _sage_const_1 /(xR-xP)

    if P == T:
        a = E.a4()
        slope = (_sage_const_3 *xP**_sage_const_2 +a)/(_sage_const_2 *yP)
    else:
        slope = (yT-yP)/(xT-xP)

    line_at_R = yR-yP-slope*(xR-xP)
    vertical_at_R = xR-S[_sage_const_0 ]
    if vertical_at_R != _sage_const_0 :
        return vertical_at_R/line_at_R

    # R= -S is the removable common zero of the line and vertical line.
    # From (y-L)(y+L)=(x-xP)(x-xT)(x-xS), where
    # L=yP+slope*(x-xP), one gets the following regular value for 1/g.
    L_at_R = yP+slope*(xR-xP)
    return (yR+L_at_R)/((xR-xP)*(xR-xT))


def four_level_sets(E, points, P, T):
    """Bit sets for the four cosets of mu_31 attained by A_P."""
    sets = [_sage_const_0 , _sage_const_0 , _sage_const_0 , _sage_const_0 ]
    for idx, R in enumerate(points):
        value = cross_ratio_value(E, P, T, R)
        if value is None:
            continue
        label = quartic_label[value**_sage_const_31 ]
        sets[label] |= (_sage_const_1  << idx)
    excluded = {E(_sage_const_0 ), P+T, P, T}
    assert sum(int(level).bit_count() for level in sets) ==            len(points)-len(excluded)
    return sets


def search():
    global_best = -_sage_const_1 
    witnesses = []
    curves_with_torsion = _sage_const_0 
    torsion_points_tested = _sage_const_0 
    pairs_tested = _sage_const_0 

    for curve_index, E in enumerate(elliptic_curve_representatives()):
        points = list(E.points())
        O = E(_sage_const_0 )
        nonzero_28_torsion = [T for T in points
                              if T != O and _sage_const_28 *T == O]
        if not nonzero_28_torsion:
            continue
        curves_with_torsion += _sage_const_1 

        possible_high_points = [P for P in points if P != O]
        for T in nonzero_28_torsion:
            torsion_points_tested += _sage_const_1 
            level_sets = [four_level_sets(E, points, P, T)
                          for P in possible_high_points]

            for i in range(len(possible_high_points)):
                for j in range(i+_sage_const_1 , len(possible_high_points)):
                    pairs_tested += _sage_const_1 
                    best = _sage_const_0 
                    for left in level_sets[i]:
                        for right in level_sets[j]:
                            overlap = int(left & right).bit_count()
                            if overlap > best:
                                best = overlap
                    if best > global_best:
                        global_best = best
                        witnesses = [(curve_index, E.ainvs(),
                                      E.cardinality(), T,
                                      possible_high_points[i],
                                      possible_high_points[j], best)]
                        print("new maximum", witnesses[-_sage_const_1 ])
                    elif best == global_best:
                        witnesses.append((curve_index, E.ainvs(),
                                          E.cardinality(), T,
                                          possible_high_points[i],
                                          possible_high_points[j], best))

    print("curves", _sage_const_252 )
    print("curves_with_nonzero_rational_28_torsion", curves_with_torsion)
    print("torsion_points_tested", torsion_points_tested)
    print("unordered_high_point_pairs_tested", pairs_tested)
    print("global_maximum_distinct_grid_intersection", global_best)
    print("number_of_maximizers", len(witnesses))
    for witness in witnesses[:_sage_const_20 ]:
        print("maximizer", witness)

    # These totals make an incomplete or altered run fail loudly.
    assert curves_with_torsion == _sage_const_186 
    assert torsion_points_tested == _sage_const_1256 
    assert pairs_tested == _sage_const_9580970 
    assert global_best == _sage_const_32 
    assert len(witnesses) == _sage_const_9 


search()

