"""
Exact finite-field certificate for file 58.

Run with

    sage 58_X_CENTRAL_GLUE_CERTIFICATE.sage

The random seed only makes the search for generators reproducible.  Each
answer is certified after the search: the subgroup found has order equal to
the full l-primary part of the known Jacobian order.
"""


# This file was *autogenerated* from the file routes/global/58_X_CENTRAL_GLUE_CERTIFICATE.sage
from sage.all_cmdline import *   # import sage library

_sage_const_20260904 = Integer(20260904); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4); _sage_const_80 = Integer(80); _sage_const_1 = Integer(1); _sage_const_7 = Integer(7); _sage_const_0 = Integer(0); _sage_const_16 = Integer(16); _sage_const_8 = Integer(8); _sage_const_9 = Integer(9); _sage_const_48 = Integer(48); _sage_const_49 = Integer(49); _sage_const_10 = Integer(10); _sage_const_18 = Integer(18)
from sage.groups.additive_abelian.additive_abelian_wrapper import (
    AdditiveAbelianGroupWrapper,
)

set_random_seed(_sage_const_20260904 )

ZZT = PolynomialRing(ZZ, names=('T',)); (T,) = ZZT._first_ngens(1)
P = (T**_sage_const_2  - _sage_const_3 *T + _sage_const_5 ) * (T**_sage_const_2  + T + _sage_const_5 ) * (T**_sage_const_2  + _sage_const_4 *T + _sage_const_5 )


def sylow_invariants(n, ell, expected, max_trials=_sage_const_80 ):
    """Compute the ell-Sylow subgroup of J_X(F_(5^n))."""
    order = abs(P.resultant(T**n - _sage_const_1 ))
    exponent = valuation(order, ell)
    cofactor = order // ell**exponent

    K = GF(_sage_const_5 **n, names=('a',)); (a,) = K._first_ngens(1)
    Kx = PolynomialRing(K, names=('x',)); (x,) = Kx._first_ngens(1)
    curve = HyperellipticCurve(x**_sage_const_7  - x + _sage_const_1 )
    jacobian_points = curve.jacobian()(K)

    def random_curve_point():
        while True:
            x0 = K.random_element()
            rhs = x0**_sage_const_7  - x0 + _sage_const_1 
            if rhs == _sage_const_0 :
                return curve([x0, K(_sage_const_0 ), K(_sage_const_1 )])
            if rhs.is_square():
                return curve([x0, rhs.sqrt(), K(_sage_const_1 )])

    def random_jacobian_point():
        ans = jacobian_points(_sage_const_0 )
        for _ in range(_sage_const_3 ):
            ans += jacobian_points(random_curve_point())
        return ans

    subgroup = AdditiveAbelianGroupWrapper(jacobian_points, [], [])
    for _ in range(max_trials):
        point = cofactor * random_jacobian_point()
        if point in subgroup:
            continue
        subgroup = AdditiveAbelianGroupWrapper.from_generators(
            subgroup._gen_elements + (point,)
        )
        if subgroup.order() == ell**exponent:
            break

    # This equality, rather than the random search, is the certificate that
    # the whole Sylow subgroup has been found.
    assert subgroup.order() == ell**exponent
    assert tuple(subgroup.invariants()) == expected
    print("n =", n, "ell =", ell, "Sylow invariants =", expected)


sylow_invariants(_sage_const_3 , _sage_const_2 , (_sage_const_2 , _sage_const_16 , _sage_const_16 ))
sylow_invariants(_sage_const_8 , _sage_const_3 , (_sage_const_3 , _sage_const_9 , _sage_const_9 , _sage_const_9 ))
sylow_invariants(_sage_const_48 , _sage_const_7 , (_sage_const_7 , _sage_const_7 , _sage_const_49 , _sage_const_49 ))


# The final finite check in Theorem 57.3.  Generate the ordered spectra from
# Theorem 56.1, impose first the mod-4 and mod-7 congruences, and then mod 3.
spectra_e1 = set()
spectra_e3 = set()
for killed in range(_sage_const_3 ):
    live = [i for i in range(_sage_const_3 ) if i != killed]
    for total in (-_sage_const_9 , -_sage_const_8 , -_sage_const_7 ):
        for a0 in range(-_sage_const_9 , _sage_const_10 ):
            b0 = total + _sage_const_9  - a0
            lam = [_sage_const_0 , _sage_const_0 , _sage_const_0 ]
            lam[killed] = -_sage_const_9 
            lam[live[_sage_const_0 ]] = a0
            lam[live[_sage_const_1 ]] = b0
            if a0**_sage_const_2  + b0**_sage_const_2  <= _sage_const_18 :
                spectra_e1.add(tuple(lam))
    for a0 in (-_sage_const_3 , _sage_const_0 , _sage_const_3 ):
        lam = [_sage_const_0 , _sage_const_0 , _sage_const_0 ]
        lam[killed] = -_sage_const_9 
        lam[live[_sage_const_0 ]] = a0
        lam[live[_sage_const_1 ]] = -a0
        spectra_e3.add(tuple(lam))


def first_two_congruences(lam):
    return (lam[_sage_const_0 ] - lam[_sage_const_1 ]) % _sage_const_4  == _sage_const_0  and (lam[_sage_const_0 ] - lam[_sage_const_2 ]) % _sage_const_7  == _sage_const_0 


remaining_e1 = sorted(filter(first_two_congruences, spectra_e1))
remaining_e3 = sorted(filter(first_two_congruences, spectra_e3))
assert remaining_e1 == [(-_sage_const_9 , _sage_const_3 , -_sage_const_2 ), (-_sage_const_2 , _sage_const_2 , -_sage_const_9 )]
assert remaining_e3 == []
assert all((lam[_sage_const_1 ] - lam[_sage_const_2 ]) % _sage_const_3  != _sage_const_0  for lam in remaining_e1)
print("remaining spectra after all congruences: none")

