

# This file was *autogenerated* from the file routes/global/65_GENUS_TWO_REDESIGN_CERTIFICATE.sage
from sage.all_cmdline import *   # import sage library

_sage_const_5 = Integer(5); _sage_const_4 = Integer(4); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_2 = Integer(2); _sage_const_25 = Integer(25); _sage_const_7 = Integer(7); _sage_const_31 = Integer(31); _sage_const_3 = Integer(3); _sage_const_13 = Integer(13); _sage_const_6 = Integer(6)# Exact certificate for Proposition 65.3.

F = GF(_sage_const_5 )
R = PolynomialRing(F, names=('x',)); (x,) = R._first_ngens(1)
f = x**_sage_const_5  + _sage_const_4 *x**_sage_const_4  + _sage_const_1 
assert gcd(f, f.derivative()) == _sage_const_1 

def point_count(poly, field):
    S = PolynomialRing(field, names=('u',)); (u,) = S._first_ngens(1)
    poly_field = S([field(c) for c in poly.list()])
    count = _sage_const_1                     # the point at infinity
    for a in field:
        value = poly_field(a)
        if value == _sage_const_0 :
            count += _sage_const_1 
        elif value.is_square():
            count += _sage_const_2 
    return count

N1 = point_count(f, F)
N2 = point_count(f, GF(_sage_const_25 ))
assert (N1, N2) == (_sage_const_7 , _sage_const_31 )

Q = PolynomialRing(QQ, names=('T',)); (T,) = Q._first_ngens(1)
s1 = _sage_const_5  + _sage_const_1  - N1
s2 = (N2 - _sage_const_5 **_sage_const_2  - _sage_const_1  + s1**_sage_const_2 ) // _sage_const_2 
P = T**_sage_const_4  - s1*T**_sage_const_3  + s2*T**_sage_const_2  - _sage_const_5 *s1*T + _sage_const_5 **_sage_const_2 
assert P == T**_sage_const_4  + T**_sage_const_3  + _sage_const_3 *T**_sage_const_2  + _sage_const_5 *T + _sage_const_25 

F2 = GF(_sage_const_2 )
R2 = PolynomialRing(F2, names=('T2',)); (T2,) = R2._first_ngens(1)
assert R2(P).is_irreducible()

F13 = GF(_sage_const_13 )
R13 = PolynomialRing(F13, names=('T13',)); (T13,) = R13._first_ngens(1)
assert R13(P) == (T13 + _sage_const_3 )*(T13 + _sage_const_6 )*(T13**_sage_const_2  + _sage_const_5 *T13 + _sage_const_5 )
assert not F13(_sage_const_5 ).is_square()

print("smooth genus-two model; point counts:", N1, N2)
print("Weil polynomial:", P)
print("mod-2 irreducible and mod-13 factorization (1,1,2): verified")

