"""Exact finite-group check for Theorem 81.3.

Run: sage routes/global/81_CUBIC_SIGN_MONODROMY_CERTIFICATE.sage
The proof in the theorem file is independent of this enumeration.
"""


# This file was *autogenerated* from the file routes/global/81_CUBIC_SIGN_MONODROMY_CERTIFICATE.sage
from sage.all_cmdline import *   # import sage library

_sage_const_6 = Integer(6); _sage_const_48 = Integer(48); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_10 = Integer(10); _sage_const_7 = Integer(7); _sage_const_4 = Integer(4); _sage_const_8 = Integer(8); _sage_const_12 = Integer(12); _sage_const_24 = Integer(24)
S = SymmetricGroup(_sage_const_6 )
beta = S("(1,2,3)(4,5,6)")
signed = S.subgroup([beta, S("(1,2)(4,5)"), S("(1,4)")])
assert signed.order() == _sage_const_48 
selection = frozenset([_sage_const_1 , _sage_const_2 , _sage_const_3 ])
groups = [H for H in signed.subgroups() if beta in H]
assert len(groups) == _sage_const_10 

def cyclic_action_is_free(h):
    return all(
        all((h**a)(i) != i for i in range(_sage_const_1 , _sage_const_7 ))
        for a in range(_sage_const_1 , h.order())
    )

four_choice = []
rows = []
for H in groups:
    H0 = H.subgroup([
        h for h in H
        if frozenset(h(i) for i in selection) == selection
    ])
    j = H.order() // H0.order()
    assert j in (_sage_const_1 , _sage_const_2 , _sage_const_4 , _sage_const_8 )
    assert H0.order() in (_sage_const_3 , _sage_const_6 )
    free_orders = sorted(set(
        h.order() for h in H
        if h.order() > _sage_const_1  and cyclic_action_is_free(h)
    ))
    rows.append((H.order(), H.structure_description(), j, free_orders))
    if j == _sage_const_4 :
        assert H.order() in (_sage_const_12 , _sage_const_24 )
        assert free_orders == [_sage_const_3 ]
        three_subgroups = {
            frozenset(H.subgroup([h]))
            for h in H if h.order() == _sage_const_3 
        }
        conjugates = {
            frozenset(H.subgroup([h * beta * h**(-_sage_const_1 )])) for h in H
        }
        assert three_subgroups == conjugates
        four_choice.append((H.order(), H.structure_description()))

assert sorted(four_choice) == [(_sage_const_12 , "A4"), (_sage_const_24 , "S4")]
for row in sorted(rows):
    print(row)
print("PASS: cubic sign degrees, four-choice groups, and inertia checks")

