

# This file was *autogenerated* from the file routes/global/88_WIMAN_EDGE_CHAR5_CERTIFICATE.sage
from sage.all_cmdline import *   # import sage library

_sage_const_5 = Integer(5); _sage_const_6 = Integer(6); _sage_const_2 = Integer(2); _sage_const_4 = Integer(4); _sage_const_12 = Integer(12); _sage_const_1 = Integer(1); _sage_const_3 = Integer(3); _sage_const_0 = Integer(0); _sage_const_60 = Integer(60); _sage_const_76 = Integer(76); _sage_const_80 = Integer(80); _sage_const_46 = Integer(46); _sage_const_50 = Integer(50); _sage_const_26 = Integer(26); _sage_const_25 = Integer(25); _sage_const_10 = Integer(10); _sage_const_8 = Integer(8); _sage_const_11 = Integer(11)# Exact certificate for 88_WIMAN_EDGE_CHAR5_DECK_COUNTEREXAMPLE.md.

k = GF(_sage_const_5 )
R = PolynomialRing(k, order='degrevlex', names=('x', 'y', 'z',)); (x, y, z,) = R._first_ngens(3)

A0 = (x**_sage_const_6  + y**_sage_const_6  + z**_sage_const_6 
      + (x**_sage_const_2 +y**_sage_const_2 +z**_sage_const_2 )*(x**_sage_const_4 +y**_sage_const_4 +z**_sage_const_4 )
      - _sage_const_12 *x**_sage_const_2 *y**_sage_const_2 *z**_sage_const_2 )
B0 = (x**_sage_const_2 -y**_sage_const_2 )*(y**_sage_const_2 -z**_sage_const_2 )*(x**_sage_const_2 -z**_sage_const_2 )

point_ideals = [
    Ideal([x+z, y-z]),
    Ideal([x-z, y+z]),
    Ideal([x+z, y+z]),
    Ideal([x-z, y-z]),
]
node_radical = Ideal([x**_sage_const_2 -z**_sage_const_2 , y**_sage_const_2 -z**_sage_const_2 ])
irrelevant = Ideal([x,y,z])
affine_nodes = [(-_sage_const_1 ,_sage_const_1 ), (_sage_const_1 ,-_sage_const_1 ), (-_sage_const_1 ,-_sage_const_1 ), (_sage_const_1 ,_sage_const_1 )]

# Every nonzero F_5-parameter has precisely the four ordinary nodes.
for tt in [_sage_const_1 ,_sage_const_2 ,_sage_const_3 ,_sage_const_4 ]:
    F = A0 + tt*B0
    jac = Ideal([F.derivative(x), F.derivative(y), F.derivative(z)])
    jac_sat = jac.saturation(irrelevant)[_sage_const_0 ]
    assert jac_sat.radical() == node_radical

    f = F(x,y,_sage_const_1 )
    for aa,bb in affine_nodes:
        hess = matrix(k, [
            [f.derivative(v).derivative(w)(aa,bb,_sage_const_1 ) for w in (x,y)]
            for v in (x,y)
        ])
        assert hess.det() == _sage_const_2 

# Cremona involution T, the linear four-cycle L, and phi=L*T.
T1 = -x**_sage_const_2 +y**_sage_const_2 +z**_sage_const_2 +x*y+x*z+y*z
T2 =  x**_sage_const_2 -y**_sage_const_2 +z**_sage_const_2 +x*y+x*z+y*z
T3 =  x**_sage_const_2 +y**_sage_const_2 -z**_sage_const_2 +x*y+x*z+y*z
phi = (T3, -T2, -T1)
rho = (y,z,x)
mult = -(x+y)**_sage_const_2 *(x+z)**_sage_const_2 *(y+z)**_sage_const_2 

assert A0(*phi) == mult*A0
assert B0(*phi) == mult*B0
assert A0(*rho) == A0
assert B0(*rho) == B0

# phi has projective order five as a rational transformation.
cur = (x,y,z)
for unused in range(_sage_const_5 ):
    cur = tuple(q(*cur) for q in phi)
    common = gcd(list(cur))
    cur = tuple(q//common for q in cur)
assert all(cur[i]*(x,y,z)[_sage_const_0 ] == cur[_sage_const_0 ]*(x,y,z)[i] for i in range(_sage_const_3 ))
assert max(q.degree() for q in cur) == _sage_const_1 

# In the plane, the fixed locus consists of the three base points of T
# and P=(0:2:1). The boundary-cycle argument in the theorem removes the
# three base points on the blowup, leaving P as the unique fixed point.
X,Y,Z = phi
fixed = Ideal([X*y-Y*x, X*z-Z*x, Y*z-Z*y])
fixed_sat = fixed.saturation(irrelevant)[_sage_const_0 ].radical()
fixed_point_ideals = [
    Ideal([x+z, y-z]),
    Ideal([x-z, y+z]),
    Ideal([x+z, y+z]),
    Ideal([x, y-_sage_const_2 *z]),
]
fixed_expected = fixed_point_ideals[_sage_const_0 ]
for ideal in fixed_point_ideals[_sage_const_1 :]:
    fixed_expected = fixed_expected.intersection(ideal)
assert fixed_sat == fixed_expected
assert A0(_sage_const_0 ,_sage_const_2 ,_sage_const_1 ) == _sage_const_0  and B0(_sage_const_0 ,_sage_const_2 ,_sage_const_1 ) == _sage_const_2 

# The boundary permutations are a 5-cycle and a 3-cycle and generate A5.
Gperm = PermutationGroup([[(_sage_const_1 ,_sage_const_2 ,_sage_const_3 ,_sage_const_4 ,_sage_const_5 )], [(_sage_const_1 ,_sage_const_3 ,_sage_const_2 )]])
assert Gperm.order() == _sage_const_60 
assert Gperm.is_isomorphic(AlternatingGroup(_sage_const_5 ))

# Tame Chevalley--Weil packet for signature (2,2,2,3).
G = AlternatingGroup(_sage_const_5 )
branch = [
    G('(1,3)(2,5)'),
    G('(1,2)(3,4)'),
    G('(1,4)(2,5)'),
    G('(3,4,5)'),
]
H5 = G.subgroup([G('(1,2,3,4,5)')])
classes = G.conjugacy_classes()

def class_index(g):
    for ii,CC in enumerate(classes):
        if g in CC:
            return ii
    raise ValueError

def value(chi,g):
    return chi[class_index(g)]

def fixed_dim(chi,U):
    return sum(value(chi,g) for g in U)/U.order()

packet = []
for chi in G.character_table().rows():
    degree = ZZ(chi[_sage_const_0 ])
    if degree == _sage_const_1 :
        continue
    h1_mult = ((len(branch)-_sage_const_2 )*degree
               - sum(fixed_dim(chi,G.subgroup([g])) for g in branch))
    if h1_mult:
        packet.append((degree,ZZ(h1_mult),ZZ(fixed_dim(chi,H5))))
assert packet == [(_sage_const_3 ,_sage_const_2 ,_sage_const_1 ),(_sage_const_3 ,_sage_const_2 ,_sage_const_1 )]

# Cartier on the six-dimensional adjoint space. The matrix is invertible
# for all four nonzero parameters (and is the identity for t=1,4).
S = PolynomialRing(k, names=('u', 'v',)); (u, v,) = S._first_ngens(2)
adjoints = [
    _sage_const_1 -u**_sage_const_2 ,
    v-u**_sage_const_2 *v,
    v**_sage_const_2 -u**_sage_const_2 ,
    v**_sage_const_3 -u**_sage_const_2 *v,
    u-u**_sage_const_3 ,
    u*v**_sage_const_2 -u**_sage_const_3 ,
]
monomials = [u**i*v**j for i in range(_sage_const_4 ) for j in range(_sage_const_4 -i)]
adjoint_matrix = matrix(k, [
    [h.monomial_coefficient(mm) for h in adjoints] for mm in monomials
])

def cartier_numerator(g):
    ans = S.zero()
    for (i,j),cc in g.dict().items():
        if i % _sage_const_5  == _sage_const_4  and j % _sage_const_5  == _sage_const_4 :
            ans += cc*u**((i-_sage_const_4 )//_sage_const_5 )*v**((j-_sage_const_4 )//_sage_const_5 )
    return ans

cartier_matrices = {}
for tt in [_sage_const_1 ,_sage_const_2 ,_sage_const_3 ,_sage_const_4 ]:
    ff = S((A0+tt*B0)(u,v,_sage_const_1 ))
    columns = []
    for h in adjoints:
        image = cartier_numerator(ff**_sage_const_4 *h)
        coeffs = vector(k,[image.monomial_coefficient(mm) for mm in monomials])
        columns.append(adjoint_matrix.solve_right(coeffs))
    CM = matrix(k,columns).transpose()
    assert CM.is_invertible()
    cartier_matrices[tt] = CM
assert cartier_matrices[_sage_const_1 ] == identity_matrix(k,_sage_const_6 )
assert cartier_matrices[_sage_const_4 ] == identity_matrix(k,_sage_const_6 )

def point_counts(tt,nn):
    K = GF(_sage_const_5 **nn,'aa')
    T = PolynomialRing(K, names=('xx', 'yy', 'zz',)); (xx, yy, zz,) = T._first_ngens(3)
    AA = (xx**_sage_const_6  + yy**_sage_const_6  + zz**_sage_const_6 
          + (xx**_sage_const_2 +yy**_sage_const_2 +zz**_sage_const_2 )*(xx**_sage_const_4 +yy**_sage_const_4 +zz**_sage_const_4 )
          - _sage_const_12 *xx**_sage_const_2 *yy**_sage_const_2 *zz**_sage_const_2 )
    BB = (xx**_sage_const_2 -yy**_sage_const_2 )*(yy**_sage_const_2 -zz**_sage_const_2 )*(xx**_sage_const_2 -zz**_sage_const_2 )
    FF = AA+K(tt)*BB
    els = list(K)
    plane = sum(_sage_const_1  for aa in els for bb in els if FF(aa,bb,_sage_const_1 ) == _sage_const_0 )
    plane += sum(_sage_const_1  for aa in els if FF(aa,_sage_const_1 ,_sage_const_0 ) == _sage_const_0 )
    plane += ZZ(FF(_sage_const_1 ,_sage_const_0 ,_sage_const_0 ) == _sage_const_0 )

    # Each node has two tangent branches over F_25, conjugate over F_5.
    # Thus normalization changes the count by -4 for odd nn and +4 for
    # even nn.
    normalized = plane + (_sage_const_4  if nn % _sage_const_2  == _sage_const_0  else -_sage_const_4 )
    return (plane,normalized)

count_table = {
    tt:(point_counts(tt,_sage_const_1 ),point_counts(tt,_sage_const_2 )) for tt in [_sage_const_1 ,_sage_const_2 ,_sage_const_3 ,_sage_const_4 ]
}
assert count_table == {
    _sage_const_1 :((_sage_const_4 ,_sage_const_0 ),(_sage_const_76 ,_sage_const_80 )),
    _sage_const_2 :((_sage_const_4 ,_sage_const_0 ),(_sage_const_46 ,_sage_const_50 )),
    _sage_const_3 :((_sage_const_4 ,_sage_const_0 ),(_sage_const_46 ,_sage_const_50 )),
    _sage_const_4 :((_sage_const_4 ,_sage_const_0 ),(_sage_const_76 ,_sage_const_80 )),
}

PR = PolynomialRing(ZZ, names=('Tvar',)); (Tvar,) = PR._first_ngens(1)
quotient_L = {}
for tt in [_sage_const_1 ,_sage_const_2 ,_sage_const_3 ,_sage_const_4 ]:
    ND1 = count_table[tt][_sage_const_0 ][_sage_const_1 ]
    ND2 = count_table[tt][_sage_const_1 ][_sage_const_1 ]
    trace_D_1 = _sage_const_6 -ND1
    trace_D_2 = _sage_const_26 -ND2
    assert trace_D_1 % _sage_const_3  == _sage_const_0  and trace_D_2 % _sage_const_3  == _sage_const_0 
    trace_X_1 = trace_D_1//_sage_const_3 
    trace_X_2 = trace_D_2//_sage_const_3 
    e2 = (trace_X_1**_sage_const_2 -trace_X_2)//_sage_const_2 
    quotient_L[tt] = (_sage_const_1 -trace_X_1*Tvar+e2*Tvar**_sage_const_2 
                      -_sage_const_5 *trace_X_1*Tvar**_sage_const_3 +_sage_const_25 *Tvar**_sage_const_4 )

assert quotient_L[_sage_const_1 ] == (_sage_const_1 -Tvar+_sage_const_5 *Tvar**_sage_const_2 )**_sage_const_2 
assert quotient_L[_sage_const_4 ] == (_sage_const_1 -Tvar+_sage_const_5 *Tvar**_sage_const_2 )**_sage_const_2 
simple_L = _sage_const_1 -_sage_const_2 *Tvar+_sage_const_6 *Tvar**_sage_const_2 -_sage_const_10 *Tvar**_sage_const_3 +_sage_const_25 *Tvar**_sage_const_4 
assert quotient_L[_sage_const_2 ] == simple_L and quotient_L[_sage_const_3 ] == simple_L

# Exact absolute-simplicity check for t=2,3.
U = PolynomialRing(QQ, names=('uu',)); (uu,) = U._first_ngens(1)
frobenius = uu**_sage_const_4 -_sage_const_2 *uu**_sage_const_3 +_sage_const_6 *uu**_sage_const_2 -_sage_const_10 *uu+_sage_const_25 
assert frobenius.is_irreducible()
assert frobenius.discriminant() == _sage_const_2 **_sage_const_8 *_sage_const_5 **_sage_const_4 *_sage_const_11 
GG = frobenius.galois_group()
assert GG.order() == _sage_const_8  and GG.structure_description() == 'D4'
Kpi = NumberField(frobenius, names=('pi',)); (pi,) = Kpi._first_ngens(1)
assert len(Kpi.automorphisms()) == _sage_const_2 
assert (pi+_sage_const_5 /pi).minpoly().degree() == _sage_const_2 

print('nonzero-parameter counts:', count_table)
print('Cartier matrices:')
for tt in [_sage_const_1 ,_sage_const_2 ,_sage_const_3 ,_sage_const_4 ]:
    print('t =',tt)
    print(cartier_matrices[tt])
print('quotient L-polynomials:', quotient_L)
print('simple Frobenius Galois group:',GG.structure_description())
print('PASS')

