

# This file was *autogenerated* from the file routes/global/EXPLICIT_ORDINARY_GENUS_TWO_DOUBLE_WITH_FROBENIUS_CYCLIC_PRYM_TWO_TORSION_CERTIFICATE.sage
from sage.all_cmdline import *   # import sage library

_sage_const_5 = Integer(5); _sage_const_1 = Integer(1); _sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_6 = Integer(6); _sage_const_4 = Integer(4); _sage_const_0 = Integer(0)# Exact certificate; run with SageMath. No search or external data.
R = PolynomialRing(GF(_sage_const_5 ), 't')
t = R.gen()
f = t*(t-_sage_const_1 )
c = t**_sage_const_3 +t+_sage_const_1 
g = (t-_sage_const_2 )*c
F = f*g
assert c.is_irreducible()
assert F.is_squarefree() and F.degree() == _sage_const_6 
assert g == t**_sage_const_4 +_sage_const_3 *t**_sage_const_3 +t**_sage_const_2 +_sage_const_4 *t+_sage_const_3 
assert F == t**_sage_const_6 +_sage_const_2 *t**_sage_const_5 +_sage_const_3 *t**_sage_const_4 +_sage_const_3 *t**_sage_const_3 +_sage_const_4 *t**_sage_const_2 +_sage_const_2 *t

# Hyperelliptic Hasse--Witt matrices: entry (i,j) is [t^(5*i-j)]F^2.
H_Y = matrix(GF(_sage_const_5 ), _sage_const_2 , _sage_const_2 , lambda i,j: (F**_sage_const_2 )[_sage_const_5 *(i+_sage_const_1 )-(j+_sage_const_1 )])
H_E = (g**_sage_const_2 )[_sage_const_4 ]
assert H_Y == matrix(GF(_sage_const_5 ), [[_sage_const_3 ,_sage_const_1 ],[_sage_const_3 ,_sage_const_4 ]])
assert H_Y.det() == _sage_const_4  and H_E == _sage_const_1 
assert sorted(h.degree() for h,e in g.factor()) == [_sage_const_1 ,_sage_const_3 ]

# A (1,3) permutation of the four branch points cycles their three
# unordered partitions into two pairs, i.e. the nonzero elliptic 2-torsion.
parts = [frozenset((frozenset((_sage_const_0 ,i)), frozenset(set(range(_sage_const_4 ))-{_sage_const_0 ,i})))
         for i in range(_sage_const_1 ,_sage_const_4 )]
fr = (_sage_const_0 ,_sage_const_2 ,_sage_const_3 ,_sage_const_1 )
action = [parts.index(frozenset(frozenset(fr[j] for j in pair)
                              for pair in part)) for part in parts]
assert action == [_sage_const_1 ,_sage_const_2 ,_sage_const_0 ]

# Independent elementary check: the monic quartic has two rational
# points at infinity; its five rational points form an odd-order group.
E_points = _sage_const_2  + sum(_sage_const_1  if g(a) == _sage_const_0  else (_sage_const_2  if g(a).is_square() else _sage_const_0 )
                   for a in GF(_sage_const_5 ))
assert E_points == _sage_const_5 
assert gcd(f,g) == _sage_const_1  and f.is_squarefree()
print('PASS: Y Hasse--Witt =', H_Y.list(), 'det =', H_Y.det())
print('PASS: E Hasse invariant =', H_E, '; #E(F5) =', E_points)
print('PASS: Frobenius on nonzero Prym 2-torsion is the 3-cycle', action)

