"""Exhaustive 64-element doubled two-primary group on the fixed Y.

Cost is exponential in v2(#J)-2g=6, not in 2g=50.
All group elements are checked through reduced Mumford arithmetic.
"""


# This file was *autogenerated* from the file routes/global/FIXED_Y_SMALL_DOUBLED_GROUP_CERTIFICATE.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_56 = Integer(56); _sage_const_0 = Integer(0); _sage_const_50 = Integer(50); _sage_const_3 = Integer(3); _sage_const_1 = Integer(1); _sage_const_51 = Integer(51); _sage_const_125 = Integer(125); _sage_const_25 = Integer(25); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4); _sage_const_64 = Integer(64); _sage_const_22 = Integer(22); _sage_const_24 = Integer(24)
from collections import Counter
from pathlib import Path
import runpy
from time import monotonic
started = monotonic()
data = runpy.run_path(str(Path(__file__).resolve().parent /
                         'FIXED_Y_LOW_DEGREE_TORSION_FROBENIUS_CERTIFICATE.py'))
cardinality = Integer(data['j_125'])
assert cardinality.valuation(_sage_const_2 ) == _sage_const_56 
odd_part = cardinality // _sage_const_2 **_sage_const_56 

# Independent small resultant for det(pi^3+I).
rem = [ZZ(_sage_const_0 ), ZZ(_sage_const_0 ), ZZ(_sage_const_0 )]
for i, coefficient in enumerate(data['p_desc']):
    exponent = _sage_const_50 -i
    rem[exponent % _sage_const_3 ] += coefficient*(-_sage_const_1 )**(exponent//_sage_const_3 )
aa, bb, cc = rem
uu, vv = aa-cc, bb+cc
plus = (aa-bb+cc)*(uu**_sage_const_2 +uu*vv+vv**_sage_const_2 )
assert plus.valuation(_sage_const_2 ) == _sage_const_51 

k = GF(_sage_const_125 , 'a')
R = PolynomialRing(k, 't')
t = R.gen()
L = t**_sage_const_25 +t**_sage_const_5 +t
f = L*(L-_sage_const_1 )*(t-_sage_const_4 )
assert f.degree() == _sage_const_51  and gcd(f, f.derivative()) == _sage_const_1 
assert len(f.roots()) == _sage_const_51   # all Weierstrass points, plus infinity, rational
J = HyperellipticCurve(f).jacobian()(k)
zero = J(_sage_const_0 )

def key(point):
    return (tuple(point[_sage_const_0 ].list()), tuple(point[_sage_const_1 ].list()))

group = {key(zero): zero}
generators = []
for x0 in k:
    value = f(x0)
    if not value or not value.is_square():
        continue
    y0 = value.sqrt()
    point = _sage_const_2 *odd_part*J([t-x0, R(y0)])
    assert _sage_const_64 *point == zero
    if key(point) in group:
        continue
    generators.append(point)
    enlarged = dict(group)
    multiple = point
    while key(multiple) not in group:
        for old in group.values():
            new = old+multiple
            enlarged[key(new)] = new
        multiple += point
    group = enlarged
    assert len(group) <= _sage_const_64 
    if len(group) == _sage_const_64 :
        break

assert len(group) == _sage_const_64 
for point in group.values():
    assert _sage_const_64 *point == zero
    for generator in generators:
        assert key(point+generator) in group
    U, V = point[_sage_const_0 ], point[_sage_const_1 ]
    assert U.is_monic() and U.degree() <= _sage_const_25 
    assert V.degree() < U.degree() and (V**_sage_const_2 -f) % U == _sage_const_0 
degrees = Counter(point[_sage_const_0 ].degree() for point in group.values())
assert degrees == {_sage_const_0 :_sage_const_1 , _sage_const_22 :_sage_const_4 , _sage_const_24 :_sage_const_3 , _sage_const_25 :_sage_const_56 }
assert min(point[_sage_const_0 ].degree() for point in group.values() if point != zero) == _sage_const_22 
print('PASS: complete doubled group size64; reduced degrees', sorted(degrees.items()))
print('Elapsed seconds:', round(monotonic()-started, _sage_const_2 ))

