"""Exact certificate for the checked W3 and three-point Cartier theorem."""


# This file was *autogenerated* from the file routes/global/GENUS9_W3_CARTIER_CERTIFICATE.sage
from sage.all_cmdline import *   # import sage library

_sage_const_18 = Integer(18); _sage_const_2 = Integer(2); _sage_const_17 = Integer(17); _sage_const_29 = Integer(29); _sage_const_16 = Integer(16); _sage_const_57 = Integer(57); _sage_const_15 = Integer(15); _sage_const_124 = Integer(124); _sage_const_14 = Integer(14); _sage_const_3716 = Integer(3716); _sage_const_13 = Integer(13); _sage_const_3083 = Integer(3083); _sage_const_12 = Integer(12); _sage_const_94215 = Integer(94215); _sage_const_11 = Integer(11); _sage_const_141450 = Integer(141450); _sage_const_10 = Integer(10); _sage_const_601875 = Integer(601875); _sage_const_9 = Integer(9); _sage_const_3536250 = Integer(3536250); _sage_const_8 = Integer(8); _sage_const_58884375 = Integer(58884375); _sage_const_7 = Integer(7); _sage_const_48171875 = Integer(48171875); _sage_const_6 = Integer(6); _sage_const_1451562500 = Integer(1451562500); _sage_const_5 = Integer(5); _sage_const_1210937500 = Integer(1210937500); _sage_const_4 = Integer(4); _sage_const_13916015625 = Integer(13916015625); _sage_const_3 = Integer(3); _sage_const_177001953125 = Integer(177001953125); _sage_const_305175781250 = Integer(305175781250); _sage_const_3814697265625 = Integer(3814697265625); _sage_const_171 = Integer(171); _sage_const_1 = Integer(1); _sage_const_25 = Integer(25); _sage_const_32 = Integer(32); _sage_const_34 = Integer(34); _sage_const_39 = Integer(39); _sage_const_0 = Integer(0)
R = PolynomialRing(ZZ, 'T')
T = R.gen()
P = (T**_sage_const_18 -_sage_const_2 *T**_sage_const_17 -_sage_const_29 *T**_sage_const_16 +_sage_const_57 *T**_sage_const_15 -_sage_const_124 *T**_sage_const_14 
     +_sage_const_3716 *T**_sage_const_13 +_sage_const_3083 *T**_sage_const_12 -_sage_const_94215 *T**_sage_const_11 +_sage_const_141450 *T**_sage_const_10 
     +_sage_const_601875 *T**_sage_const_9 +_sage_const_3536250 *T**_sage_const_8 -_sage_const_58884375 *T**_sage_const_7 +_sage_const_48171875 *T**_sage_const_6 
     +_sage_const_1451562500 *T**_sage_const_5 -_sage_const_1210937500 *T**_sage_const_4 +_sage_const_13916015625 *T**_sage_const_3 
     -_sage_const_177001953125 *T**_sage_const_2 -_sage_const_305175781250 *T+_sage_const_3814697265625 )
P2 = P.change_ring(GF(_sage_const_2 ))
assert P2.is_irreducible()
K = GF(_sage_const_2 **_sage_const_18 , 'alpha', modulus=P2)
assert K.gen().multiplicative_order() == _sage_const_171 
S4 = PolynomialRing(Zmod(_sage_const_4 ), 'u')
A4 = S4.quotient(S4(P), 'b')
U = T**_sage_const_17 +T**_sage_const_16 +T**_sage_const_14 +T**_sage_const_10 +T**_sage_const_8 +T**_sage_const_7 +T**_sage_const_6 +T**_sage_const_2 +T
assert (A4.gen()**_sage_const_171 -_sage_const_1 ).lift() == S4(_sage_const_2 *U)
assert gcd(U.change_ring(GF(_sage_const_2 )), P2) == _sage_const_1 
assert gcd((U+_sage_const_1 ).change_ring(GF(_sage_const_2 )), P2) == _sage_const_1 
R5 = PolynomialRing(GF(_sage_const_5 ), 'z')
z = R5.gen()
k = GF(_sage_const_25 , 'a', modulus=z**_sage_const_2 +_sage_const_4 *z+_sage_const_2 )
a = k.gen()
Rc = PolynomialRing(k, 'c')
c = Rc.gen()
Rx = PolynomialRing(Rc, 'x')
x = Rx.gen()
F = (x**_sage_const_10 +(_sage_const_4 *a+_sage_const_2 )*x**_sage_const_9 +(a+_sage_const_4 )*x**_sage_const_8 +(_sage_const_3 *a+_sage_const_1 )*x**_sage_const_7 +_sage_const_3 *a*x**_sage_const_6 
     +_sage_const_4 *a*x**_sage_const_5 +(_sage_const_3 *a+_sage_const_4 )*x**_sage_const_4 +a*x**_sage_const_3 +(_sage_const_3 *a+_sage_const_3 )*x**_sage_const_2 
     +(_sage_const_4 *a+_sage_const_2 )*x+(_sage_const_2 *a+_sage_const_1 ))
Q = F*(x-c)**_sage_const_32 
u, v = Q[_sage_const_34 ], Q[_sage_const_39 ]
assert u % v == (_sage_const_2 *a+_sage_const_1 )*(c+_sage_const_1 )
assert v(-_sage_const_1 ) == _sage_const_4 *a+_sage_const_1  != _sage_const_0 
assert gcd(u, v) == _sage_const_1 
print('PASS: two-step Frobenius criterion and three-point Cartier obstruction.')

