"""Exact bounded certificate; run with Sage 10.9 or compatible Sage.

No external programs, random choices, or floating-point root calculations.
All #E(F5)=5 short-Weierstrass models and all nonzero rational points
are checked. The coefficient of xy in the order-five function is one.
"""


# This file was *autogenerated* from the file routes/global/HOSHI_GENUS6_F5_KUMMER_P_RANK_CERTIFICATE.sage
from sage.all_cmdline import *   # import sage library

_sage_const_5 = Integer(5); _sage_const_6 = Integer(6); _sage_const_1 = Integer(1); _sage_const_8 = Integer(8); _sage_const_4 = Integer(4); _sage_const_3 = Integer(3); _sage_const_27 = Integer(27); _sage_const_2 = Integer(2); _sage_const_0 = Integer(0); _sage_const_44 = Integer(44); _sage_const_158 = Integer(158); _sage_const_572 = Integer(572); _sage_const_3082 = Integer(3082); _sage_const_16574 = Integer(16574); _sage_const_68 = Integer(68); _sage_const_15638 = Integer(15638); _sage_const_122 = Integer(122); _sage_const_2968 = Integer(2968); _sage_const_7 = Integer(7); _sage_const_12 = Integer(12)
from itertools import product

k = GF(_sage_const_5 )
R = PolynomialRing(k, names=('x',)); (x,) = R._first_ngens(1)
S = PowerSeriesRing(k, default_prec=_sage_const_6 , names=('t',)); (t,) = S._first_ngens(1)
Z = PolynomialRing(ZZ, names=('T',)); (T,) = Z._first_ngens(1)
fields = {n: GF(_sage_const_5 **n, name="a") for n in range(_sage_const_1 , _sage_const_8 )}

models = [(a,b) for a,b in product(k,k)
          if _sage_const_4 *a**_sage_const_3 +_sage_const_27 *b**_sage_const_2  != _sage_const_0 
          and EllipticCurve(k,[a,b]).cardinality() == _sage_const_5 ]
assert models == [(k(_sage_const_3 ),k(_sage_const_2 )),(k(_sage_const_3 ),k(_sage_const_3 ))]

expected = {
    (_sage_const_2 ,_sage_const_1 ): ((_sage_const_2 ,_sage_const_44 ,_sage_const_158 ,_sage_const_572 ,_sage_const_3082 ,_sage_const_16574 ),(_sage_const_4 ,_sage_const_3 ,_sage_const_1 ,-_sage_const_4 ,_sage_const_0 ,_sage_const_0 )),
    (_sage_const_2 ,_sage_const_2 ): ((_sage_const_2 ,_sage_const_68 ,_sage_const_158 ,_sage_const_572 ,_sage_const_3082 ,_sage_const_15638 ),(_sage_const_3 ,_sage_const_2 ,_sage_const_1 ,-_sage_const_2 ,_sage_const_0 ,_sage_const_0 )),
    (_sage_const_3 ,_sage_const_3 ): ((_sage_const_8 ,_sage_const_68 ,_sage_const_122 ,_sage_const_572 ,_sage_const_2968 ,_sage_const_15638 ),(_sage_const_2 ,_sage_const_1 ,-_sage_const_2 ,-_sage_const_3 ,_sage_const_0 ,_sage_const_0 )),
    (_sage_const_3 ,_sage_const_4 ): ((_sage_const_8 ,_sage_const_44 ,_sage_const_122 ,_sage_const_572 ,_sage_const_2968 ,_sage_const_16574 ),(_sage_const_4 ,_sage_const_1 ,-_sage_const_3 ,-_sage_const_4 ,_sage_const_0 ,_sage_const_0 )),
}

def order_five_function(a,b,P):
    xp,yp = P[_sage_const_0 ],P[_sage_const_1 ]
    xs,ys = xp+t,S(yp)
    for _ in range(_sage_const_4 ):
        ys = (ys+(xs**_sage_const_3 +a*xs+b)/ys)/_sage_const_2 
    basis = [S(_sage_const_1 ),xs,ys,xs**_sage_const_2 ,xs*ys]
    M = matrix(k,_sage_const_5 ,_sage_const_5 ,lambda i,j:basis[j][i])
    K = M.right_kernel()
    assert K.dimension() == _sage_const_1 
    v = K.basis()[_sage_const_0 ]
    assert v[_sage_const_4 ] != _sage_const_0 
    v = v/v[_sage_const_4 ]
    A,B = v[_sage_const_0 ]+v[_sage_const_1 ]*x+v[_sage_const_3 ]*x**_sage_const_2 , v[_sage_const_2 ]+x
    cubic = x**_sage_const_3 +a*x+b
    assert A(xp)+B(xp)*yp == _sage_const_0 
    assert A(xp)-B(xp)*yp != _sage_const_0 
    # f=A+By: norm and pole order give div(f)=5P-5O exactly.
    assert A**_sage_const_2 -B**_sage_const_2 *cubic == -(x-xp)**_sage_const_5 
    # Exact differential identity df/f=c dx/(2y).
    c = _sage_const_4 *v[_sage_const_3 ]
    assert c != _sage_const_0 
    assert _sage_const_2 *A.derivative() == c*B
    assert _sage_const_2 *B.derivative()*cubic+B*cubic.derivative() == c*A
    return A,B,v,c

def point_count(a,b,A,B,n):
    K = fields[n]
    m = gcd(_sage_const_6 ,K.cardinality()-_sage_const_1 )
    exponent = (K.cardinality()-_sage_const_1 )//m
    # Unique rational point over O on the smooth normalization.
    total = _sage_const_1 
    AK,BK = A.change_ring(K),B.change_ring(K)
    for xx in K:
        rhs = xx**_sage_const_3 +K(a)*xx+K(b)
        if not rhs.is_square():
            continue
        for yy in rhs.sqrt(all=True):
            value = AK(xx)+BK(xx)*yy
            if value == _sage_const_0 :
                # Unique point above P, also after normalization.
                total += _sage_const_1 
            elif value**exponent == _sage_const_1 :
                total += m
    return ZZ(total)

def frobenius_from_counts(counts):
    power_sums = [_sage_const_5 **n+_sage_const_1 -counts[n-_sage_const_1 ] for n in range(_sage_const_1 ,_sage_const_7 )]
    coeff = [ZZ(_sage_const_1 )]
    for m in range(_sage_const_1 ,_sage_const_7 ):
        numerator = -sum(coeff[m-j]*power_sums[j-_sage_const_1 ]
                         for j in range(_sage_const_1 ,m+_sage_const_1 ))
        assert numerator % m == _sage_const_0 
        coeff.append(numerator//m)
    return (sum(coeff[j]*T**(_sage_const_12 -j) for j in range(_sage_const_7 ))
            +sum(_sage_const_5 **(_sage_const_6 -j)*coeff[j]*T**j for j in range(_sage_const_6 )))

checked = _sage_const_0 
for a,b in models:
    E = EllipticCurve(k,[a,b])
    for P in E.points():
        if P.is_zero():
            continue
        assert P.order() == _sage_const_5 
        A,B,v,c = order_five_function(a,b,P)
        counts = tuple(point_count(a,b,A,B,n) for n in range(_sage_const_1 ,_sage_const_7 ))
        required,traces = expected[(ZZ(b),ZZ(P[_sage_const_0 ]))]
        assert counts == required
        F = frobenius_from_counts(counts)
        assert F == prod(T**_sage_const_2 -tr*T+_sage_const_5  for tr in traces)
        assert _sage_const_12 -F.change_ring(k).valuation() == _sage_const_4 
        print("E coefficients",a,b,"P",P,"f coefficients",tuple(v))
        print("counts",counts,"Frobenius",F.factor(),"p-rank",_sage_const_4 )
        if b == _sage_const_2  and P[_sage_const_0 ] == _sage_const_1  and P[_sage_const_1 ] == _sage_const_1 :
            # Additional count not used in reconstruction.
            predicted_sum = _sage_const_0 
            for tr in traces:
                s0,s1 = ZZ(_sage_const_2 ),ZZ(tr)
                for n in range(_sage_const_2 ,_sage_const_8 ):
                    s0,s1 = s1,tr*s1-_sage_const_5 *s0
                predicted_sum += s1
            n7 = point_count(a,b,A,B,_sage_const_7 )
            assert n7 == _sage_const_5 **_sage_const_7 +_sage_const_1 -predicted_sum
            print("independent seventh count",n7)
        checked += _sage_const_1 
assert checked == _sage_const_8 
print("PASS: all eight marked F5 models have genus six and p-rank four.")

