#!/usr/bin/env python3
"""Rebuild the fixed-q input polynomials, compare hashes, then verify the witnesses.
This checks fixed q=64426 only; it does not decide the varying-q schemes.
"""
import argparse,concurrent.futures,hashlib,json,subprocess,tempfile
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
def digest(p):
 h=hashlib.sha256()
 with p.open('rb') as f:
  for b in iter(lambda:f.read(1<<20),b''):h.update(b)
 return h.hexdigest()
def main():
 ap=argparse.ArgumentParser();ap.add_argument('--roots',type=int,nargs='+');ap.add_argument('--jobs',type=int,default=1);ap.add_argument('--threads',type=int,default=4);ap.add_argument('--work',type=Path,default=ROOT/'verified_fibres');a=ap.parse_args();a.work=a.work.resolve()
 roots=a.roots or sorted(int(p.name[1:]) for p in (ROOT/'next').glob('r[0-9]*') if (p/'generated.sha256').exists())
 if not roots:raise RuntimeError('No retained fibre certificates found')
 build=ROOT/'build';build.mkdir(exist_ok=True);a.work.mkdir(parents=True,exist_ok=True)
 for stem in ['fibre_equations','fibre_resultants','res_strip','verify_certificates']:
  cmd=['g++','-std=c++17','-O3','-pthread',str(ROOT/'next'/f'{stem}.cpp'),'-o',str(build/stem)]
  subprocess.run(cmd,check=True)
 def check(r):
  cert=ROOT/'next'/f'r{r}';data=a.work/f'r{r}';data.mkdir(exist_ok=True)
  commands=[['fibre_equations',str(r),str(data),str(a.threads)],['fibre_resultants',str(data),'73',str(a.threads)],['res_strip',str(r),str(data),'73']]
  for cmd in commands:
   with (data/(cmd[0]+'.log')).open('w') as f:subprocess.run([str(build/cmd[0]),*cmd[1:]],cwd=ROOT,check=True,stdout=f,stderr=subprocess.STDOUT)
  checks=[]
  for line in (cert/'generated.sha256').read_text().splitlines():
   expected,name=line.split(None,1);name=name.strip();actual=digest(data/name)
   if actual!=expected:raise RuntimeError(f'Root {r}: byte mismatch for {name}')
   checks.append(name)
  with (data/'verify_certificates.log').open('w') as f:
   subprocess.run([str(build/'verify_certificates'),str(r),str(cert),str(data)],cwd=ROOT,check=True,stdout=f,stderr=subprocess.STDOUT)
  print(f'r={r}: {len(checks)} polynomial files regenerated byte-for-byte; all certificate identities PASS',flush=True)
  return {'root':r,'regenerated_files':checks,'all_hashes_match':True,'certificate_verification':'PASS','scope':'fixed q=64426'}
 with concurrent.futures.ThreadPoolExecutor(max_workers=a.jobs) as ex:results=list(ex.map(check,roots))
 (a.work/'replay_summary.json').write_text(json.dumps({'roots':results,'global_decision':'unresolved'},indent=2)+'\n')
 print('FIXED_Q_REPLAY_PASS',flush=True)
if __name__=='__main__':main()
