// Verify stored certificates, without re-running a gcd or trusting its answer.
#include "../src/residual.hpp"
#include "fast_poly.hpp"
#include "theta_all.hpp"
using RowPoly=std::vector<Poly>;
Rows rload(fs::path p){std::ifstream f(p,std::ios::binary);if(!f)throw std::runtime_error("missing "+p.string());int n=read32(f),m=read32(f);f.close();return read_rows(p,n,m);}
Poly pload(fs::path p){auto v=rload(p);if(v.size()!=1)throw std::runtime_error("not polynomial vector");return Poly(v[0]);}
int jint(fs::path p,std::string key){std::ifstream f(p);std::string s((std::istreambuf_iterator<char>(f)),{});auto i=s.find("\""+key+"\"");if(i==s.npos)throw std::runtime_error("missing key "+key);i=s.find(':',i);return std::stoi(s.substr(i+1));}
Poly restore_unit(Poly a,Poly theta,int eh,int et){for(int power=1;et;power*=5){int digit=et%5;et/=5;Poly b=frobenius_poly(theta,power);for(int k=0;k<digit;k++){Poly c;c.c.resize(a.deg()+b.deg()+1);for(int i=0;i<=b.deg();i++)if(b[i])for(int j=0;j<=a.deg();j++)c.c[i+j]+=b[i]*a[j];c.trim();a=c;}}return a.shift(eh);}
RowPoly eqmod(fs::path p,const Poly& m){auto v=rload(p);RowPoly a(v[0].size());for(int l=0;l<(int)a.size();l++){Poly h;h.c.resize(v.size());for(int i=0;i<(int)v.size();i++)h.c[i]=v[i][l];h.trim();a[l]=h%m;}while(!a.empty()&&!a.back())a.pop_back();return a;}
RowPoly umod(fs::path p,const Poly& m){auto v=rload(p);RowPoly a;for(auto row:v)a.push_back(Poly(row)%m);while(!a.empty()&&!a.back())a.pop_back();return a;}
RowPoly rmul(const RowPoly&a,const RowPoly&b,const Poly&m){if(a.empty()||b.empty())return {};RowPoly c(a.size()+b.size()-1);for(int i=0;i<(int)a.size();i++)if(a[i])for(int j=0;j<(int)b.size();j++)if(b[j])c[i+j]=(c[i+j]+a[i]*b[j])%m;return c;}
int main(int argc,char**argv){try{if(argc<3)throw std::runtime_error("usage: verify_certificates ROOT CERT_DIR [REGENERATED_INPUT_DIR]");int r=std::stoi(argv[1]);fs::path dir=argv[2],data=argc>3?fs::path(argv[3]):dir;input::init();auto it=std::find(input::roots.begin(),input::roots.end(),r);if(it==input::roots.end())throw std::runtime_error("invalid root");F w=F::code(101),q=w.pow(3);auto cr=cramer(reconstruct(F::code(r)));if(q!=F::code(64426)||!q||q==cr.pivot||q==F::code(input::qr[it-input::roots.begin()]))throw std::runtime_error("excluded q");auto theta=theta_for_root(r,q);for(int c:{1,2,3,4,31}){F H=F::code(c);auto s=evaluate_source(cr,H,w);if(theta.eval(H)!=numeric_F6(s)*q*(q-cr.pivot))throw std::runtime_error("Theta/source comparison");}
 std::array<Poly,2> a;for(int k=0;k<2;k++){int n=72+k;std::string name="Res71_"+std::to_string(n);a[k]=pload(data/(name+"_stripped.bin"));auto orig=pload(data/(name+".bin"));int eh=jint(dir/(name+"_stripped.json"),"H_valuation"),et=jint(dir/(name+"_stripped.json"),"Theta_valuation");if(restore_unit(a[k],theta,eh,et)!=orig)throw std::runtime_error("stripping reconstruction");}
 auto s=pload(dir/"bezout_72_73_s.bin"),t=pload(dir/"bezout_72_73_t.bin"),g=pload(dir/"gcd_72_73.bin"),p=pload(dir/"gcd_radical_candidate.bin");if(fmul(s,a[0])+fmul(t,a[1])!=g)throw std::runtime_error("large Bezout");if(fdivrem(a[0],g).second||fdivrem(a[1],g).second)throw std::runtime_error("divisibility");if(frobenius_poly(p,5)!=g)throw std::runtime_error("fifth power");if(gcd(p,p.deriv()).deg()!=0||gcd(p,theta).deg()!=0||!p[0])throw std::runtime_error("squarefree/open checks");
 fs::path quot=dir/"quotient_0";if(pload(quot/"modulus.bin")!=p)throw std::runtime_error("quotient modulus");RowPoly total;std::vector<int> degrees;for(int n=71;n<=73;n++){auto e=eqmod(data/("E"+std::to_string(n)+".bin"),p);degrees.push_back((int)e.size()-1);auto u=umod(quot/("U"+std::to_string(n)+".bin"),p);auto prod=rmul(e,u,p);total.resize(std::max(total.size(),prod.size()));for(int i=0;i<(int)prod.size();i++)total[i]=(total[i]+prod[i])%p;}
 while(!total.empty()&&!total.back())total.pop_back();if(total.size()!=1||total[0]!=Poly(1))throw std::runtime_error("small quotient Bezout");std::cout<<"r="<<r<<" q="<<q<<" VERIFIED: unit-factor identities; large Bezout; degree-"<<p.deg()<<" fifth-power candidate; quotient Bezout=1; actual mu-degrees=";for(int d:degrees)std::cout<<d<<",";std::cout<<"; entire geometric fixed-q fibre empty.\n";
 std::ofstream out(dir/"certificate_verification.json");out<<"{\"root\":"<<r<<",\"q\":"<<q<<",\"source_theta_checks\":5,\"unit_factor_identities\":true,\"large_bezout\":true,\"gcd_divisibilities\":true,\"candidate_fifth_power\":true,\"candidate_degree\":"<<p.deg()<<",\"candidate_squarefree\":true,\"small_quotient_bezout_equals_one\":true,\"fibre_empty_for_all_geometric_H_mu\":true,\"global_varying_q_decision\":\"unresolved\"}\n";
 return 0;}catch(std::exception&e){std::cerr<<"ERROR "<<e.what()<<"\n";return 1;}}
