import Solutions.CartierAndSpin.FunctionSquarePencils
import Solutions.CartierAndSpin.OddPowerSquarePencils

namespace Litt3.CartierAndSpin

open Polynomial

variable {k L : Type*} [Field k] [Field L] [Algebra k L]

/-- Frobenius powers retain the exact weighted square support bound.
The parameter change is the actual perfect-field Frobenius equivalence;
the degree is that of the actual field generated by r, including when
the original ratio r^(p^e) is inseparable. -/
theorem frobenius_function_weighted_square_pencil_finite
    (p e : ℕ) [Fact p.Prime] [CharP k p] [CharP L p] [PerfectField k]
    (hpodd : Odd p) (r : L) (hr : Transcendental k r)
    [FiniteDimensional (IntermediateField.adjoin k {r}) L]
    (g : L) (hg : g ≠ 0) (htwo : (2 : k) ≠ 0) :
    let support : Set k := {theta | IsSquare (g * (r ^ (p ^ e) - algebraMap k L theta))}
    support.Finite ∧ support.ncard ≤
      1 + (Module.finrank (IntermediateField.adjoin k {r}) L).factorization 2 := by
  let linear : Set k := {theta | IsSquare (g * (r - algebraMap k L theta))}
  let power : Set k := {theta | IsSquare (g * (r ^ (p ^ e) - algebraMap k L theta))}
  let f := iterateFrobeniusEquiv k p e
  have hnonzero : ∀ theta : k, r - algebraMap k L theta ≠ 0 := by
    intro theta hz
    apply hr
    rw [sub_eq_zero.mp hz]
    exact isAlgebraic_algebraMap (R := k) (A := L) theta
  have hiff : ∀ theta : k, f theta ∈ power ↔ theta ∈ linear := by
    intro theta
    change IsSquare (g * (r ^ (p ^ e) - algebraMap k L (f theta))) ↔ _
    rw [show f theta = theta ^ (p ^ e) from iterateFrobeniusEquiv_def k p e theta,
      map_pow, ← sub_pow_char_pow]
    exact weighted_odd_power_square_iff g _ _ hpodd.pow (hnonzero theta)
  have heq : power = f '' linear := by
    ext theta
    constructor
    · intro htheta
      refine ⟨f.symm theta, ?_, f.apply_symm_apply theta⟩
      exact (hiff _).mp (by simpa only [f.apply_symm_apply] using htheta)
    · rintro ⟨lambda, hlambda, rfl⟩
      exact (hiff lambda).mpr hlambda
  have hbase := function_weighted_square_pencil_finite r hr g hg htwo
  change linear.Finite ∧ linear.ncard ≤ _ at hbase
  change power.Finite ∧ power.ncard ≤ _
  rw [heq]
  exact ⟨hbase.1.image f, by
    rw [Set.ncard_image_of_injOn f.injective.injOn]
    exact hbase.2⟩

end Litt3.CartierAndSpin
