import Solutions.SharedTensors.PBasisPerfectConstants
import Solutions.SharedTensors.SeparatingPBasisExistence
import Solutions.CartierAndSpin.SeparatingDerivationParameters

namespace Litt3.CartierAndSpin

open Litt3.SharedTensors IntermediateField

variable {k L : Type*} [Field k] [Field L] [Algebra k L]

/-- An actual derivation on a field generated by a pair is determined
by its values on that pair, including inversion in the generated field. -/
theorem generating_pair_derivation_zero
    (D : Derivation k L L) (u v : L)
    (hgen : IntermediateField.adjoin k {u, v} = ⊤)
    (hu : D u = 0) (hv : D v = 0) : ∀ a : L, D a = 0 := by
  intro a
  have ha : a ∈ IntermediateField.adjoin k {u, v} := by rw [hgen]; trivial
  induction ha using IntermediateField.adjoin_induction with
  | mem z hz =>
      rcases Set.mem_insert_iff.mp hz with h | h
      · exact h ▸ hu
      · exact (Set.mem_singleton_iff.mp h) ▸ hv
  | algebraMap c => exact D.map_algebraMap c
  | add x y hx hy hDx hDy => rw [map_add, hDx, hDy, add_zero]
  | mul x y hx hy hDx hDy => rw [D.leibniz, hDx, hDy, smul_zero, smul_zero, add_zero]
  | inv x hx hDx => rw [D.leibniz_inv, hDx, smul_zero]

theorem generating_pair_nonzero_derivation
    (D : Derivation k L L) (u v : L)
    (hgen : IntermediateField.adjoin k {u, v} = ⊤)
    (hnonzero : ∃ a : L, D a ≠ 0) : D u ≠ 0 ∨ D v ≠ 0 := by
  by_contra h
  push_neg at h
  obtain ⟨a, ha⟩ := hnonzero
  exact ha (generating_pair_derivation_zero D u v hgen h.1 h.2 a)

end Litt3.CartierAndSpin
