import Solutions.SharedTensors.AffineMinimalPolynomials
import Mathlib.FieldTheory.IntermediateField.Adjoin.Basic

namespace Litt3.CartierAndSpin

open Polynomial IntermediateField

variable {k L : Type*} [Field k] [Field L] [Algebra k L]

/-- A derivation preserves the actual generated field whenever it sends
the displayed generators into that field. Constants, inverses and every
field operation are handled by genuine adjoin induction. -/
theorem derivation_stable_adjoin (D : Derivation k L L) (s : Set L)
    (hgenerators : ∀ x ∈ s, D x ∈ IntermediateField.adjoin k s) :
    ∀ x ∈ IntermediateField.adjoin k s, D x ∈ IntermediateField.adjoin k s := by
  intro x hx
  induction hx using IntermediateField.adjoin_induction with
  | mem x hx => exact hgenerators x hx
  | algebraMap x => rw [D.map_algebraMap]; exact zero_mem _
  | add x y hx hy hDx hDy =>
      rw [map_add]
      exact add_mem hDx hDy
  | inv x hx hDx =>
      rw [D.leibniz_inv]
      change -(x⁻¹ ^ 2) * D x ∈ _
      exact mul_mem (neg_mem (pow_mem (inv_mem hx) 2)) hDx
  | mul x y hx hy hDx hDy =>
      rw [D.leibniz]
      change x * D y + y * D x ∈ _
      exact add_mem (mul_mem hx hDy) (mul_mem hy hDx)

noncomputable def restrictedIntermediateDerivation (D : Derivation k L L)
    (B : IntermediateField k L) (hstable : ∀ x ∈ B, D x ∈ B) : Derivation k B B where
  toLinearMap :=
    { toFun := fun x => ⟨D x.val, hstable x.val x.property⟩
      map_add' := fun x y => Subtype.ext (D.map_add x.val y.val)
      map_smul' := fun c x => Subtype.ext (D.map_smul c x.val) }
  map_one_eq_zero' := Subtype.ext D.map_one_eq_zero
  leibniz' x y := Subtype.ext (D.leibniz x.val y.val)

theorem restrictedIntermediateDerivation_compatible (D : Derivation k L L)
    (B : IntermediateField k L) (hstable : ∀ x ∈ B, D x ∈ B) (x : B) :
    algebraMap B L (restrictedIntermediateDerivation D B hstable x) =
      D (algebraMap B L x) := rfl

section SeparableElement

variable {B : Type*} [Field B] [Algebra k B] [Algebra B L]

theorem intermediate_polynomial_aeval_mem (E : IntermediateField B L)
    (x : L) (hx : x ∈ E) (P : B[X]) : aeval x P ∈ E := by
  have h := (aeval (⟨x, hx⟩ : E) P).property
  simpa only [← IntermediateField.aeval_coe] using h

/-- A compatible actual derivation sends every separable algebraic element
into the field generated by it and the differential base. The derivative
of its actual minimal polynomial is canceled inside that same field. -/
theorem separable_element_derivation_mem (D : Derivation k B B) (E : Derivation k L L)
    (compatible : ∀ b : B, algebraMap B L (D b) = E (algebraMap B L b))
    (F : IntermediateField B L) (x : L) (hx : x ∈ F) (hsep : IsSeparable B x) :
    E x ∈ F := by
  let P := minpoly B x
  have hroot : aeval x P = 0 := minpoly.aeval B x
  have hdenom : aeval x P.derivative ≠ 0 := hsep.aeval_derivative_ne_zero hroot
  have hdiff := Litt3.SharedTensors.derivation_polynomial_aeval D E compatible x P
  rw [hroot, map_zero] at hdiff
  have hvalue : E x =
      -aeval x (Litt3.SharedTensors.coefficientDifferential D.toLinearMap P) /
        aeval x P.derivative := by
    apply (eq_div_iff hdenom).mpr
    linear_combination -hdiff
  rw [hvalue]
  exact div_mem (neg_mem (intermediate_polynomial_aeval_mem F x hx _))
    (intermediate_polynomial_aeval_mem F x hx _)

end SeparableElement
end Litt3.CartierAndSpin
