"""Prepare one unspecialized root-incidence ideal for Singular.

The Python field/model checks are executable and exact.  The generated
Singular program is an UNEXECUTED prototype, not an exclusion certificate.
No parameter has been specialized in the generated ideal.
"""
from __future__ import annotations
import json, sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
sys.path.insert(0,str(ROOT/'src'))
sys.path.insert(0,str(ROOT/'intersection/src'))
import field as F, poly as U, evaluate as E
from critical_cover import xgcd


def encoded_fields():
    # alpha^4+2alpha^3+alpha^2+2alpha + beta*(alpha^3+alpha^2+1)=0.
    aa=[0,2,1,2,1]
    bb=[1,0,1,1]
    minimum=U.add(U.add(U.mul(aa,aa),U.mul(aa,bb)),U.scale(U.mul(bb,bb),2))
    assert len(minimum)==9 and minimum[-1]==1
    assert all(c<5 for c in minimum)
    gcd, invb, _=xgcd(bb,minimum)
    assert gcd==[1]
    betapoly=U.rem(U.scale(U.mul(aa,invb),4),minimum)
    assert all(c<5 for c in betapoly)
    assert U.evalp(minimum,25)==0 and U.evalp(betapoly,25)==5
    assert not U.rem(U.sub(U.sub(U.mul(betapoly,betapoly),betapoly),[3]),minimum)
    def encode(code: int) -> list[int]:
        assert 0<=code<F.ORDER
        out=[]
        for j in range(4):
            digit=(code//25**j)%25
            piece=U.add([digit%5],U.scale(betapoly,digit//5))
            out=U.add(out,U.shift(piece,j))
        out=U.rem(out,minimum)
        assert all(c<5 for c in out)
        assert U.evalp(out,25)==code
        return out
    basis=[1,5,25,125,625,3125,15625,78125]
    for a in basis:
        for b in basis:
            assert U.rem(U.mul(encode(a),encode(b)),minimum)==encode(F.mul(a,b))
    return minimum,betapoly,encode


def poly_string(p: list[int], variable: str) -> str:
    parts=[]
    for e,c in enumerate(p):
        if c:
            v='' if e==0 else variable if e==1 else variable+'^'+str(e)
            parts.append(str(c) if not v else v if c==1 else str(c)+'*'+v)
    return '+'.join(parts) or '0'


def emit() -> None:
    if sys.flags.optimize:raise RuntimeError('Assertions must be enabled')
    minimum,beta,encode=encoded_fields()
    data=json.loads((ROOT/'data/cube_free.json').read_text())
    def k(c):return '('+poly_string(encode(c),'a')+')'
    def up(p,v='x'):
        return '+'.join(k(c)+('' if e==0 else '*'+v if e==1 else '*'+v+'^'+str(e))
                        for e,c in enumerate(p) if c) or '0'
    def sparse(rows, variables, yshift=False):
        terms=[]
        for powers,code in rows:
            powers=list(powers)
            if yshift:
                # n_i_plus=q*n_i(Y=z/q); this single extra q clears every denominator.
                powers[1]+=1-powers[3]
                assert powers[1]>=0
            t=k(code)
            for name,power in zip(variables,powers):
                assert power>=0
                if power:t+='*'+name+(('^'+str(power)) if power!=1 else '')
            terms.append(t)
        return '+'.join(terms) or '0'
    declarations=[
        '// UNEXECUTED PROTOTYPE. No global decision is claimed.',
        '// Generated by decision/src/prepare_global.py. Characteristic five.',
        'ring build=(5,a),(z,x,m,H,q),(lp(1),dp(4));',
        'minpoly='+poly_string(minimum,'a')+';',
        'poly PP='+up(E.P)+';',
        'poly tt='+up(E.t)+';',
        'poly vv=x-'+k(9)+';',
        'poly dq='+up(data['d_q_ascending'],'q')+';',
        'poly Psi='+sparse(data['Psi'],['H','q'])+';',
        'ideal CY=z^3-q^2*PP;',
        'CY=std(CY);',
        'proc nf(poly p) {return(reduce(p,CY));}',
    ]
    for i in range(2,6):
        declarations.append('poly n'+str(i)+'='+sparse(data['barred_numerators']['g'+str(i)],['H','q','x','z'],True)+';')
    declarations.extend([
        'poly qb=q*z*('+up(data['Qbar_x_polynomial'])+');',
        'poly aa=3*n2; poly bb=2*n3; poly cc=n4; poly dd=n5;',
        'poly ell=dq*q^2*m*vv; poly cap=dq*q^5*tt^3;',
        'poly a5=nf(aa^5); poly b5=nf(bb^5);',
        'poly ee=nf(aa*dd-bb*cc); poly de=nf(bb^2+aa*cc);',
        'poly T0=nf(cc^5-qb*b5+qb^2*a5);',
        'poly U0=nf(2*qb*a5-b5);',
        'poly V0=nf(-dd*b5-2*cc^2*bb^4-3*aa*bb^2*cc^3-2*aa^2*cc^4+qb*(2*a5*dd-aa^4*bb*cc+aa^3*bb^3));',
        'poly W0=nf(aa^2*dd^2-aa*bb*cc*dd+2*bb^2*cc^2+bb^3*dd+aa*cc^3);',
        'poly M0=nf(U0*(2*aa*ee+bb*de)-aa^2*V0);',
        'poly resu=nf(ell^2*T0^2+ell*(T0*V0+cap*(U0^2-2*a5*T0))+aa^3*(T0*W0+cap*M0)+cap^2*aa^10);',
        'poly den=q^15*tt^5*vv;',
        'poly theta=resu/den;',
        'if (den*theta!=resu) {ERROR("nonexact upstairs division");}',
        'poly ta=subst(theta,z,0);',
        'poly tb=subst(diff(theta,z),z,0);',
        'poly tc=3*subst(diff(diff(theta,z),z),z,0);',
        'if (theta!=ta+tb*z+tc*z^2) {ERROR("unreduced upstairs element");}',
        'poly RR=ta^3+q^2*PP*tb^3+q^4*PP^2*tc^3+2*q^2*PP*ta*tb*tc;',
        'matrix XC=coef(RR,x);',
        'list coeffs;',
        'int i; int j; int kk;',
        'for (i=1;i<=141;i++) {coeffs[i]=poly(0);}',
        'for (i=1;i<=ncols(XC);i++) {',
        '  kk=deg(XC[1,i]);',
        '  if ((kk<0)||(kk>140)) {ERROR("wrong x degree");}',
        '  coeffs[kk+1]=XC[2,i];',
        '}',
        'poly expected='+k(244991)+'*q^55*dq^30*H^9*Psi^3;',
        'if (coeffs[141]!=expected) {ERROR("wrong leading coefficient");}',
        '// All 141 coefficients, not merely early square tails, now enter.',
        'ring roots=(5,a),(H,q,m,iv,'+','.join('j'+str(i) for i in range(71))+'),dp;',
        'minpoly='+poly_string(minimum,'a')+';',
        'list rc=imap(build,coeffs);',
        'poly ps=imap(build,Psi);',
        'poly omega=H*q*m*ps*(q-'+k(10149)+')*(q-'+k(118020)+')*(q-'+k(64426)+');',
        'ideal I=iv*omega-1;',
        'int k0; int i0; int lo; int hi; poly eq;',
        'for (k0=0;k0<=140;k0++) {',
        '  eq=rc[k0+1]; lo=0; hi=70;',
        '  if (k0>70) {lo=k0-70;}',
        '  if (k0<70) {hi=k0;}',
        '  for (i0=lo;i0<=hi;i0++) {eq=eq-var(5+i0)*var(5+k0-i0);}',
        '  I=I,eq;',
        '}',
        'option(redSB); option(prot);',
        'ideal G=std(I);',
        'if (reduce(poly(1),G)==0) {',
        '  matrix certificate=lift(I,ideal(1));',
        '  matrix product=matrix(I)*certificate;',
        '  if (product[1,1]!=1) {ERROR("invalid unit certificate");}',
        '  print("UNIT_IDEAL_VERIFIED");',
        '  write("global_unit_certificate.txt",certificate);',
        '} else {',
        '  int dimensionK=vdim(G);',
        '  if (dimensionK<=0) {ERROR("nonzero finite algebra not verified");}',
        '  print("NONZERO_FINITE_ROOT_ALGEBRA");',
        '  print(dimensionK);',
        '  write("global_basis.txt",G);',
        '}',
        'quit;',
    ])
    destination=ROOT/'decision/global_incidence.sing'
    destination.write_text('\n'.join(declarations)+'\n')
    out={
        'status':'PREPARATION_CHECKS_PASS; SINGULAR_PROTOTYPE_UNEXECUTED',
        'alpha_minpoly_ascending_F5':minimum,
        'beta_as_alpha_polynomial_ascending_F5':beta,
        'basis_product_checks':64,
        'transformed_relation':'z^3=q^2 P(x), z=qY',
        'upstairs':'theta_plus=Res_plus/(q^15*t^5*v); Res_plus=q^12*Res_star(Y=z/q)',
        'norm_relation':'R_plus=Norm(theta_plus)=q^6*S_model=q^55*d(q)^36*R',
        'open_condition':'H*q*mu*Psi*(q-10149)*(q-118020)*(q-64426) != 0; codes as input',
        'root_incidence_equations':141,
        'inverse_equations':1,
        'root_incidence_variables':75,
        'new_source_exclusions':0,
        'geometric_witnesses':0,
        'complete_decision':'UNRESOLVED',
    }
    (ROOT/'decision/data/preparation.json').write_text(json.dumps(out,indent=2)+'\n')
    print(json.dumps(out,indent=2))

if __name__=='__main__':emit()
