import Mathlib.RingTheory.MvPolynomial.Groebner
import Mathlib.RingTheory.Ideal.Quotient.Basic
import Mathlib.RingTheory.Ideal.Quotient.Operations
import Mathlib.LinearAlgebra.Dimension.OrzechProperty
import Mathlib.LinearAlgebra.FiniteDimensional.Lemmas

namespace Litt3.Atlases

variable {K σ : Type*} [Field K]

/-- The actual standard monomials for the leading monomial ideal.
Zero polynomials are ignored, so a derived zero equation adds no constraint. -/
def standardMonomials (m : MonomialOrder σ) (G : Set (MvPolynomial σ K)) :
    Set (σ →₀ ℕ) :=
  {d | ∀ g ∈ G, g ≠ 0 → ¬m.degree g ≤ d}

/-- Actual polynomial quotient images of the standard monomials. -/
noncomputable def standardMonomialImages (m : MonomialOrder σ) (G : Set (MvPolynomial σ K))
    (I : Ideal (MvPolynomial σ K)) (d : standardMonomials m G) :
    MvPolynomial σ K ⧸ I :=
  Ideal.Quotient.mkₐ K I (MvPolynomial.monomial d.val 1)

/-- The usual leading-divisibility definition of a Groebner basis,
on actual polynomials in the original ideal. -/
def IsGroebnerBasisFor (m : MonomialOrder σ) (G : Set (MvPolynomial σ K))
    (I : Ideal (MvPolynomial σ K)) : Prop :=
  G ⊆ I ∧ ∀ f ∈ I, f ≠ 0 → ∃ g ∈ G, g ≠ 0 ∧ m.degree g ≤ m.degree f

/-- The actual ideal generated by leading monomials of nonzero
polynomials from a specified set. -/
noncomputable def leadingMonomialIdeal (m : MonomialOrder σ)
    (S : Set (MvPolynomial σ K)) : Ideal (MvPolynomial σ K) :=
  Ideal.span {t | ∃ f ∈ S, f ≠ 0 ∧ t = MvPolynomial.monomial (m.degree f) 1}

end Litt3.Atlases
