import Solutions.Jacobians.AffineDivisorSectionValues
import Solutions.Jacobians.DivisorSheafGlobalGenerators
import Solutions.Jacobians.FractionalIdealUnitGenerators

open CategoryTheory Opposite AlgebraicGeometry TopologicalSpace
open scoped nonZeroDivisors

namespace Litt3.Jacobians

universe u
variable {X : Scheme.{u}} [IsIntegral X] [JacobsonSpace X] [ClosedPointDVRStalks X]
  {U : X.Opens} (hU : IsAffineOpen U)
  [IsDedekindDomain Γ(X, U)] [Nonempty U] (hfield : ¬IsField Γ(X, U))
  (D : Divisor (Litt3.SharedTensors.ClosedPoint X))
  (e : actualSchemeDivisorSheaf X D ≅ SheafOfModules.unit X.ringCatSheaf)

/-- An ACTUAL global sheaf trivialization trivializes the ACTUAL
fractional-ideal module on every ORIGINAL affine chart, through the proved
original section/ideal comparison. -/
noncomputable def actualAffineDivisorTrivialIdealEquiv :
    letI := functionField_isFractionRing_of_isAffineOpen X U hU
    (((actualDedekindSectionFractionalIdeal Γ(X, U) X.functionField
      (actualAffineChartDivisorRestriction hU hfield D)).val :
        FractionalIdeal (Γ(X, U))⁰ X.functionField) : Submodule Γ(X, U) X.functionField) ≃ₗ[Γ(X, U)]
      Γ(X, U) :=
  (actualAffineDivisorSectionsFractionalIdealEquiv hU hfield D).symm ≪≫ₗ
    actualDivisorSheafTrivialSectionEquiv X D e (op U)

/-- The actual affine ideal generator induced by a genuine global
trivialization is ALWAYS the SAME original global rational function,
without separately chosen local generators or transition assumptions. -/
theorem actualAffineDivisorTrivialIdealEquiv_generator_value :
    (actualAffineDivisorTrivialIdealEquiv hU hfield D e |>.symm 1).val =
      actualDivisorSheafGlobalGenerator X D e := by
  classical
  change (actualAffineDivisorSectionsFractionalIdealEquiv hU hfield D
    (actualDivisorSheafUnitGenerator X D e (op U))).val = _
  rw [actualAffineDivisorSectionsFractionalIdealEquiv_value]
  let x : U := Classical.arbitrary U
  change (actualSchemeRationalFunctionOpenIso X U).hom.hom
      (actualDivisorSheafUnitGenerator X D e (op U)).val = _
  rw [← actualRationalFunctionEvaluation_eq_open X U x.val x.property]
  exact actualDivisorSheafGlobalGenerator_on_open X D e U x.val x.property

/-- EVERY actual affine divisor ideal of a genuinely trivial global
divisor SHEAF is generated by ONE derived ORIGINAL global rational
function. No merely local-principal or abstract class equality is substituted. -/
theorem actualAffineDivisorIdeal_eq_span_global_generator :
    letI := functionField_isFractionRing_of_isAffineOpen X U hU
    (actualDedekindSectionFractionalIdeal Γ(X, U) X.functionField
      (actualAffineChartDivisorRestriction hU hfield D)).val =
        FractionalIdeal.spanSingleton (Γ(X, U))⁰
          (actualDivisorSheafGlobalGenerator X D e) := by
  letI := functionField_isFractionRing_of_isAffineOpen X U hU
  have h := fractionalIdeal_eq_span_of_inverse_unit
    (actualDedekindSectionFractionalIdeal Γ(X, U) X.functionField
      (actualAffineChartDivisorRestriction hU hfield D)).val
    (actualAffineDivisorTrivialIdealEquiv hU hfield D e)
  rw [actualAffineDivisorTrivialIdealEquiv_generator_value] at h
  exact h

end Litt3.Jacobians
